/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a7873391a571
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { EasyAPIError } from "./easy-api-error.js";

export type ErrorEnvelopeData = {
  error: models.ErrorT;
};

export class ErrorEnvelope extends EasyAPIError {
  error: models.ErrorT;

  /** The original data that was passed to this error instance. */
  data$: ErrorEnvelopeData;

  constructor(
    err: ErrorEnvelopeData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ErrorEnvelope";
  }
}

/** @internal */
export const ErrorEnvelope$inboundSchema: z.ZodMiniType<
  ErrorEnvelope,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => models.ErrorT$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrorEnvelope(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
