/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4031260e046
 */

import { bankAccountsGetBalances } from "../funcs/bank-accounts-get-balances.js";
import { bankAccountsListTransactions } from "../funcs/bank-accounts-list-transactions.js";
import { bankAccountsList } from "../funcs/bank-accounts-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Accounts extends ClientSDK {
  /**
   * List all AIS-connected bank accounts for the tenant
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetV1BankAccountsResponse> {
    return unwrapAsync(bankAccountsList(
      this,
      options,
    ));
  }

  /**
   * Get current balances for one AIS-connected bank account
   */
  async getBalances(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1BankAccountsIdBalancesResponse> {
    return unwrapAsync(bankAccountsGetBalances(
      this,
      id,
      options,
    ));
  }

  /**
   * Get date-windowed transactions for one AIS-connected bank account
   */
  async listTransactions(
    request: operations.GetV1BankAccountsIdTransactionsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1BankAccountsIdTransactionsResponse> {
    return unwrapAsync(bankAccountsListTransactions(
      this,
      request,
      options,
    ));
  }
}
