/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bda42bf2c95c
 */

import { legislationActsGetVersion } from "../funcs/legislation-acts-get-version.js";
import { legislationActsGet } from "../funcs/legislation-acts-get.js";
import { legislationActsListChanges } from "../funcs/legislation-acts-list-changes.js";
import { legislationActsListVersions } from "../funcs/legislation-acts-list-versions.js";
import { legislationActsList } from "../funcs/legislation-acts-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Acts extends ClientSDK {
  /**
   * List consolidated normative acts
   */
  async list(
    request?: operations.GetV1LegislationActsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetV1LegislationActsResponse, { cursor: string }>
  > {
    return unwrapResultIterator(legislationActsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Poll the acts change-feed since a given timestamp
   */
  async listChanges(
    request: operations.GetV1LegislationActsChangesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1LegislationActsChangesResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(legislationActsListChanges(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an act's current consolidated form
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationActsIdResponse> {
    return unwrapAsync(legislationActsGet(
      this,
      id,
      options,
    ));
  }

  /**
   * List an act's point-in-time versions
   */
  async listVersions(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationActsIdVersionsResponse> {
    return unwrapAsync(legislationActsListVersions(
      this,
      id,
      options,
    ));
  }

  /**
   * Get an act's body as it read on a given version date
   */
  async getVersion(
    id: string,
    version: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationActsIdVersionsVersionResponse> {
    return unwrapAsync(legislationActsGetVersion(
      this,
      id,
      version,
      options,
    ));
  }
}
