/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0b72bf54cc1b
 */

import { bankGetTreasury } from "../funcs/bank-get-treasury.js";
import { bankListInstitutions } from "../funcs/bank-list-institutions.js";
import { bankValidateIban } from "../funcs/bank-validate-iban.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Accounts } from "./accounts.js";

export class Bank extends ClientSDK {
  private _accounts?: Accounts;
  get accounts(): Accounts {
    return (this._accounts ??= new Accounts(this._options));
  }

  /**
   * Validate an IBAN's structure and resolve its RO bank code
   */
  async validateIban(
    iban: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1BankIbanIbanResponse> {
    return unwrapAsync(bankValidateIban(
      this,
      iban,
      options,
    ));
  }

  /**
   * Look up ANAF treasury IBANs for a CUI
   */
  async getTreasury(
    cui: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1BankTreasuryCuiResponse> {
    return unwrapAsync(bankGetTreasury(
      this,
      cui,
      options,
    ));
  }

  /**
   * List the bank institutions available for a connection
   */
  async listInstitutions(
    options?: RequestOptions,
  ): Promise<operations.GetV1BankInstitutionsResponse> {
    return unwrapAsync(bankListInstitutions(
      this,
      options,
    ));
  }
}
