/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bfb7cb6dd91e
 */

import { legislationBillsGet } from "../funcs/legislation-bills-get.js";
import { legislationBillsListChanges } from "../funcs/legislation-bills-list-changes.js";
import { legislationBillsListDocuments } from "../funcs/legislation-bills-list-documents.js";
import { legislationBillsListStages } from "../funcs/legislation-bills-list-stages.js";
import { legislationBillsList } from "../funcs/legislation-bills-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Bills extends ClientSDK {
  /**
   * List parliamentary bills
   */
  async list(
    request?: operations.GetV1LegislationBillsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.GetV1LegislationBillsResponse, { cursor: string }>
  > {
    return unwrapResultIterator(legislationBillsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Poll the bills change-feed since a given timestamp
   */
  async listChanges(
    request: operations.GetV1LegislationBillsChangesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1LegislationBillsChangesResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(legislationBillsListChanges(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single parliamentary bill
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationBillsIdResponse> {
    return unwrapAsync(legislationBillsGet(
      this,
      id,
      options,
    ));
  }

  /**
   * Get a bill's legislative stage history
   */
  async listStages(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationBillsIdStagesResponse> {
    return unwrapAsync(legislationBillsListStages(
      this,
      id,
      options,
    ));
  }

  /**
   * Get a bill's associated documents
   */
  async listDocuments(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationBillsIdDocumentsResponse> {
    return unwrapAsync(legislationBillsListDocuments(
      this,
      id,
      options,
    ));
  }
}
