/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7bf531b021cd
 */

import { companyBalanceByYear } from "../funcs/company-balance-by-year.js";
import { companyBalance } from "../funcs/company-balance.js";
import { companyBatchGet } from "../funcs/company-batch-get.js";
import { companyGet } from "../funcs/company-get.js";
import { companyLitigation } from "../funcs/company-litigation.js";
import { companyVatStatus } from "../funcs/company-vat-status.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Company extends ClientSDK {
  /**
   * Look up a company's identity and VAT status by CUI
   */
  async get(
    cui: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1CompanyCuiResponse> {
    return unwrapAsync(companyGet(
      this,
      cui,
      options,
    ));
  }

  /**
   * Get a company's ANAF bilanț for a single filing year
   */
  async balanceByYear(
    cui: string,
    year: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1CompanyCuiBalanceYearResponse> {
    return unwrapAsync(companyBalanceByYear(
      this,
      cui,
      year,
      options,
    ));
  }

  /**
   * Get a company's last filed bilanț years in one call
   */
  async balance(
    cui: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1CompanyCuiBalanceResponse> {
    return unwrapAsync(companyBalance(
      this,
      cui,
      options,
    ));
  }

  /**
   * Get a company's focused VAT/registry status by CUI
   */
  async vatStatus(
    cui: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1CompanyCuiVatStatusResponse> {
    return unwrapAsync(companyVatStatus(
      this,
      cui,
      options,
    ));
  }

  /**
   * Find ECRIS court cases matching this company's legal name
   */
  async litigation(
    request: operations.GetV1CompanyCuiLitigationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1CompanyCuiLitigationResponse> {
    return unwrapAsync(companyLitigation(
      this,
      request,
      options,
    ));
  }

  /**
   * Look up up to 100 companies by CUI in one call
   */
  async batchGet(
    body: operations.PostV1CompanyBatchRequestBody,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1CompanyBatchResponse> {
    return unwrapAsync(companyBatchGet(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }
}
