/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5992fff3b5cd
 */

import { connectionsCreate } from "../funcs/connections-create.js";
import { connectionsGet } from "../funcs/connections-get.js";
import { connectionsList } from "../funcs/connections-list.js";
import { connectionsRevoke } from "../funcs/connections-revoke.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Connections extends ClientSDK {
  /**
   * Request a gov connection (returns the dashboard consent URL)
   */
  async create(
    body: operations.PostV1ConnectionsRequestBody,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1ConnectionsResponse> {
    return unwrapAsync(connectionsCreate(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }

  /**
   * List the tenant's gov connections
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetV1ConnectionsResponse> {
    return unwrapAsync(connectionsList(
      this,
      options,
    ));
  }

  /**
   * Get one gov connection's metadata
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1ConnectionsIdResponse> {
    return unwrapAsync(connectionsGet(
      this,
      id,
      options,
    ));
  }

  /**
   * Revoke a gov connection and wipe its vault credential
   */
  async revoke(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.DeleteV1ConnectionsIdResponse> {
    return unwrapAsync(connectionsRevoke(
      this,
      id,
      options,
    ));
  }
}
