/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b364d96e2063
 */

import { regesContractsCreate } from "../funcs/reges-contracts-create.js";
import { regesContractsTerminate } from "../funcs/reges-contracts-terminate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contracts extends ClientSDK {
  /**
   * Register a REGES employment contract, async
   */
  async create(
    body: operations.PostV1RegesContractsRequestBody,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1RegesContractsResponse> {
    return unwrapAsync(regesContractsCreate(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Terminate a REGES employment contract, async
   */
  async terminate(
    request: operations.PostV1RegesContractsIdTerminateRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1RegesContractsIdTerminateResponse> {
    return unwrapAsync(regesContractsTerminate(
      this,
      request,
      options,
    ));
  }
}
