/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 70d95793e166
 */

import { efacturaDownloadZip } from "../funcs/efactura-download-zip.js";
import { efacturaDownload } from "../funcs/efactura-download.js";
import { efacturaListMessages } from "../funcs/efactura-list-messages.js";
import { efacturaStatus } from "../funcs/efactura-status.js";
import { efacturaUpload } from "../funcs/efactura-upload.js";
import { efacturaValidate } from "../funcs/efactura-validate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Efactura extends ClientSDK {
  /**
   * Upload a UBL/JSON invoice to e-Factura
   */
  async upload(
    body: operations.PostV1EfacturaInvoicesRequestBody,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1EfacturaInvoicesResponse> {
    return unwrapAsync(efacturaUpload(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get an invoice's e-Factura clearance state
   */
  async status(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1EfacturaInvoicesIdResponse> {
    return unwrapAsync(efacturaStatus(
      this,
      id,
      options,
    ));
  }

  /**
   * Get a signed download URL for an invoice's e-Factura result
   */
  async download(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1EfacturaInvoicesIdDownloadResponse> {
    return unwrapAsync(efacturaDownload(
      this,
      id,
      options,
    ));
  }

  /**
   * Download an invoice's e-Factura result zip through a signed link
   */
  async downloadZip(
    request: operations.GetV1EfacturaInvoicesIdZipRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1EfacturaInvoicesIdZipResponse> {
    return unwrapAsync(efacturaDownloadZip(
      this,
      request,
      options,
    ));
  }

  /**
   * List e-Factura messages for a connected company
   */
  async listMessages(
    days?: number | undefined,
    cui?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1EfacturaMessagesResponse> {
    return unwrapAsync(efacturaListMessages(
      this,
      days,
      cui,
      options,
    ));
  }

  /**
   * Validate a UBL invoice offline, and with ?online=true also at ANAF (no ANAF connection required)
   */
  async validate(
    request: operations.PostV1EfacturaValidateRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV1EfacturaValidateResponse> {
    return unwrapAsync(efacturaValidate(
      this,
      request,
      options,
    ));
  }
}
