/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c13a0923df24
 */

import { regesEmployeesList } from "../funcs/reges-employees-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Employees extends ClientSDK {
  /**
   * List REGES employees for a connected company (CNP masked)
   */
  async list(
    cui?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1RegesEmployeesResponse> {
    return unwrapAsync(regesEmployeesList(
      this,
      cui,
      options,
    ));
  }
}
