/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ffadceca44c1
 */

import { etransportCreate } from "../funcs/etransport-create.js";
import { etransportGet } from "../funcs/etransport-get.js";
import { etransportModify } from "../funcs/etransport-modify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Etransport extends ClientSDK {
  /**
   * Create an e-Transport declaration
   */
  async create(
    body: operations.PostV1EtransportDeclarationsRequestBody,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV1EtransportDeclarationsResponse> {
    return unwrapAsync(etransportCreate(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Modify an e-Transport declaration by UIT
   */
  async modify(
    uit: string,
    body: operations.PatchV1EtransportDeclarationsUitRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PatchV1EtransportDeclarationsUitResponse> {
    return unwrapAsync(etransportModify(
      this,
      uit,
      body,
      options,
    ));
  }

  /**
   * Query an e-Transport declaration by UIT
   */
  async get(
    uit: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1EtransportDeclarationsUitResponse> {
    return unwrapAsync(etransportGet(
      this,
      uit,
      options,
    ));
  }
}
