/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: db68e7313216
 */

import { fxConvert } from "../funcs/fx-convert.js";
import { fxListRates } from "../funcs/fx-list-rates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Fx extends ClientSDK {
  /**
   * List the latest BNR reference rates
   */
  async listRates(
    options?: RequestOptions,
  ): Promise<operations.GetV1FxRatesResponse> {
    return unwrapAsync(fxListRates(
      this,
      options,
    ));
  }

  /**
   * Convert an amount between currencies at the latest rates
   */
  async convert(
    request: operations.GetV1FxConvertRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1FxConvertResponse> {
    return unwrapAsync(fxConvert(
      this,
      request,
      options,
    ));
  }
}
