/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0f16083c1f96
 */

import { geoGetParcel } from "../funcs/geo-get-parcel.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Geo extends ClientSDK {
  /**
   * Look up a cadastral parcel by coordinates or INSPIRE id
   */
  async getParcel(
    request?: operations.GetV1GeoParcelsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1GeoParcelsResponse> {
    return unwrapAsync(geoGetParcel(
      this,
      request,
      options,
    ));
  }
}
