/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d2e0a0845caf
 */

import { healthCheck } from "../funcs/health-check.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Health extends ClientSDK {
  /**
   * Report db/redis/ANAF reachability
   */
  async check(
    options?: RequestOptions,
  ): Promise<operations.GetV1HealthResponse> {
    return unwrapAsync(healthCheck(
      this,
      options,
    ));
  }
}
