/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ed817c4ea3a4
 */

import { regesJobsGet } from "../funcs/reges-jobs-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Jobs extends ClientSDK {
  /**
   * Get a REGES async job's status
   */
  async get(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1RegesJobsIdResponse> {
    return unwrapAsync(regesJobsGet(
      this,
      id,
      options,
    ));
  }
}
