/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 810b7bde8848
 */

import { ClientSDK } from "../lib/sdks.js";
import { Acts } from "./acts.js";
import { Bills } from "./bills.js";
import { MonitorulOficial } from "./monitorul-oficial.js";

export class Legislation extends ClientSDK {
  private _bills?: Bills;
  get bills(): Bills {
    return (this._bills ??= new Bills(this._options));
  }

  private _acts?: Acts;
  get acts(): Acts {
    return (this._acts ??= new Acts(this._options));
  }

  private _monitorulOficial?: MonitorulOficial;
  get monitorulOficial(): MonitorulOficial {
    return (this._monitorulOficial ??= new MonitorulOficial(this._options));
  }
}
