/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eeeab1031f91
 */

import { meGet } from "../funcs/me-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Me extends ClientSDK {
  /**
   * Get the resolved business, tier, effective scopes, and limits
   */
  async get(
    options?: RequestOptions,
  ): Promise<operations.GetV1MeResponse> {
    return unwrapAsync(meGet(
      this,
      options,
    ));
  }
}
