/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f0eb9a0c376
 */

import { legislationMonitorulOficialGetAct } from "../funcs/legislation-monitorul-oficial-get-act.js";
import { legislationMonitorulOficialListChanges } from "../funcs/legislation-monitorul-oficial-list-changes.js";
import { legislationMonitorulOficialListIssues } from "../funcs/legislation-monitorul-oficial-list-issues.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class MonitorulOficial extends ClientSDK {
  /**
   * List Monitorul Oficial issues
   */
  async listIssues(
    request?:
      | operations.GetV1LegislationMonitorulOficialIssuesRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1LegislationMonitorulOficialIssuesResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(legislationMonitorulOficialListIssues(
      this,
      request,
      options,
    ));
  }

  /**
   * Poll the Monitorul Oficial change-feed since a given timestamp
   */
  async listChanges(
    request: operations.GetV1LegislationMonitorulOficialChangesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1LegislationMonitorulOficialChangesResponse,
      { cursor: string }
    >
  > {
    return unwrapResultIterator(legislationMonitorulOficialListChanges(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an act as it appeared in Monitorul Oficial
   */
  async getAct(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1LegislationMonitorulOficialActsIdResponse> {
    return unwrapAsync(legislationMonitorulOficialGetAct(
      this,
      id,
      options,
    ));
  }
}
