/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a41be9dca097
 */

import { procurementGetContract } from "../funcs/procurement-get-contract.js";
import { procurementGetCpvAnalysis } from "../funcs/procurement-get-cpv-analysis.js";
import { procurementListCompanyContracts } from "../funcs/procurement-list-company-contracts.js";
import { procurementListCompanyDirectPurchases } from "../funcs/procurement-list-company-direct-purchases.js";
import { procurementListCompanyTenders } from "../funcs/procurement-list-company-tenders.js";
import { procurementListCpvContracts } from "../funcs/procurement-list-cpv-contracts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Procurement extends ClientSDK {
  /**
   * List a company's public procurement contracts by CUI
   */
  async listCompanyContracts(
    request: operations.GetV1ProcurementCompanyCuiContractsRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1ProcurementCompanyCuiContractsResponse,
      { offset: number }
    >
  > {
    return unwrapResultIterator(procurementListCompanyContracts(
      this,
      request,
      options,
    ));
  }

  /**
   * List a company's public procurement tenders by CUI
   */
  async listCompanyTenders(
    request: operations.GetV1ProcurementCompanyCuiTendersRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1ProcurementCompanyCuiTendersResponse,
      { offset: number }
    >
  > {
    return unwrapResultIterator(procurementListCompanyTenders(
      this,
      request,
      options,
    ));
  }

  /**
   * List a company's public procurement direct purchases by CUI
   */
  async listCompanyDirectPurchases(
    request: operations.GetV1ProcurementCompanyCuiDirectPurchasesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1ProcurementCompanyCuiDirectPurchasesResponse,
      { offset: number }
    >
  > {
    return unwrapResultIterator(procurementListCompanyDirectPurchases(
      this,
      request,
      options,
    ));
  }

  /**
   * List public procurement contracts for a CPV code
   */
  async listCpvContracts(
    request: operations.GetV1ProcurementCpvCpvContractsRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GetV1ProcurementCpvCpvContractsResponse,
      { offset: number }
    >
  > {
    return unwrapResultIterator(procurementListCpvContracts(
      this,
      request,
      options,
    ));
  }

  /**
   * Get market analysis for a CPV code
   */
  async getCpvAnalysis(
    request: operations.GetV1ProcurementCpvCpvAnalysisRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1ProcurementCpvCpvAnalysisResponse> {
    return unwrapAsync(procurementGetCpvAnalysis(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single public procurement contract's detail by number
   */
  async getContract(
    number: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1ProcurementContractsNumberResponse> {
    return unwrapAsync(procurementGetContract(
      this,
      number,
      options,
    ));
  }
}
