/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 768ad8196259
 */

import { ClientSDK } from "../lib/sdks.js";
import { Contracts } from "./contracts.js";
import { Employees } from "./employees.js";
import { Jobs } from "./jobs.js";

export class Reges extends ClientSDK {
  private _contracts?: Contracts;
  get contracts(): Contracts {
    return (this._contracts ??= new Contracts(this._options));
  }

  private _jobs?: Jobs;
  get jobs(): Jobs {
    return (this._jobs ??= new Jobs(this._options));
  }

  private _employees?: Employees;
  get employees(): Employees {
    return (this._employees ??= new Employees(this._options));
  }
}
