/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 784571af2f69
 */

import { ClientSDK } from "../lib/sdks.js";
import { Bank } from "./bank.js";
import { Company } from "./company.js";
import { Connections } from "./connections.js";
import { Efactura } from "./efactura.js";
import { Etransport } from "./etransport.js";
import { Fx } from "./fx.js";
import { Geo } from "./geo.js";
import { Health } from "./health.js";
import { Justice } from "./justice.js";
import { Legislation } from "./legislation.js";
import { Me } from "./me.js";
import { Procurement } from "./procurement.js";
import { Reges } from "./reges.js";
import { Search } from "./search.js";
import { Spv } from "./spv.js";
import { Stats } from "./stats.js";
import { Vat } from "./vat.js";

export class EasyApi extends ClientSDK {
  private _health?: Health;
  get health(): Health {
    return (this._health ??= new Health(this._options));
  }

  private _me?: Me;
  get me(): Me {
    return (this._me ??= new Me(this._options));
  }

  private _company?: Company;
  get company(): Company {
    return (this._company ??= new Company(this._options));
  }

  private _vat?: Vat;
  get vat(): Vat {
    return (this._vat ??= new Vat(this._options));
  }

  private _fx?: Fx;
  get fx(): Fx {
    return (this._fx ??= new Fx(this._options));
  }

  private _justice?: Justice;
  get justice(): Justice {
    return (this._justice ??= new Justice(this._options));
  }

  private _legislation?: Legislation;
  get legislation(): Legislation {
    return (this._legislation ??= new Legislation(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }

  private _connections?: Connections;
  get connections(): Connections {
    return (this._connections ??= new Connections(this._options));
  }

  private _efactura?: Efactura;
  get efactura(): Efactura {
    return (this._efactura ??= new Efactura(this._options));
  }

  private _etransport?: Etransport;
  get etransport(): Etransport {
    return (this._etransport ??= new Etransport(this._options));
  }

  private _reges?: Reges;
  get reges(): Reges {
    return (this._reges ??= new Reges(this._options));
  }

  private _bank?: Bank;
  get bank(): Bank {
    return (this._bank ??= new Bank(this._options));
  }

  private _procurement?: Procurement;
  get procurement(): Procurement {
    return (this._procurement ??= new Procurement(this._options));
  }

  private _spv?: Spv;
  get spv(): Spv {
    return (this._spv ??= new Spv(this._options));
  }

  private _geo?: Geo;
  get geo(): Geo {
    return (this._geo ??= new Geo(this._options));
  }

  private _stats?: Stats;
  get stats(): Stats {
    return (this._stats ??= new Stats(this._options));
  }
}
