/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b88871d87236
 */

import { searchCompanies } from "../funcs/search-companies.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Search companies by name
   */
  async companies(
    request: operations.GetV1SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1SearchResponse> {
    return unwrapAsync(searchCompanies(
      this,
      request,
      options,
    ));
  }
}
