/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0f9e20e5b994
 */

import { spvDownloadDocument } from "../funcs/spv-download-document.js";
import { spvGetEtvaDecont } from "../funcs/spv-get-etva-decont.js";
import { spvListMessages } from "../funcs/spv-list-messages.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Spv extends ClientSDK {
  /**
   * List SPV inbox messages
   */
  async listMessages(
    days?: number | undefined,
    cif?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV1SpvMessagesResponse> {
    return unwrapAsync(spvListMessages(
      this,
      days,
      cif,
      options,
    ));
  }

  /**
   * Download one SPV document as a binary stream
   */
  async downloadDocument(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1SpvDocumentsIdResponse> {
    return unwrapAsync(spvDownloadDocument(
      this,
      id,
      options,
    ));
  }

  /**
   * Fetch the e-TVA pre-completed VAT return for a period
   */
  async getEtvaDecont(
    cif: string,
    perioada: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1SpvEtvaDecontResponse> {
    return unwrapAsync(spvGetEtvaDecont(
      this,
      cif,
      perioada,
      options,
    ));
  }
}
