/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f1f181d5ec73
 */

import { vatValidateVies } from "../funcs/vat-validate-vies.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Vat extends ClientSDK {
  /**
   * Validate an EU VAT number against VIES
   */
  async validateVies(
    countryCode: string,
    vatNumber: string,
    options?: RequestOptions,
  ): Promise<operations.GetV1VatViesCountryCodeVatNumberResponse> {
    return unwrapAsync(vatValidateVies(
      this,
      countryCode,
      vatNumber,
      options,
    ));
  }
}
