/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 150274416467
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @digitap/easyapi SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx healthCheck.example.ts
 */

import { EasyApi } from "@digitap/easyapi";

const easyApi = new EasyApi();

async function main() {
  const result = await easyApi.health.check();

  console.log(result);
}

main().catch(console.error);
