/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bba6ebee4d7d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteV1ConnectionsIdRequest = {
  id: string;
};

export type DeleteV1ConnectionsIdData = {
  id: string;
  status: "revoked";
};

/**
 * Success
 */
export type DeleteV1ConnectionsIdResponseBody = {
  data: DeleteV1ConnectionsIdData;
};

export type DeleteV1ConnectionsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: DeleteV1ConnectionsIdResponseBody;
};

/** @internal */
export type DeleteV1ConnectionsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteV1ConnectionsIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV1ConnectionsIdRequest$Outbound,
  DeleteV1ConnectionsIdRequest
> = z.object({
  id: z.string(),
});

export function deleteV1ConnectionsIdRequestToJSON(
  deleteV1ConnectionsIdRequest: DeleteV1ConnectionsIdRequest,
): string {
  return JSON.stringify(
    DeleteV1ConnectionsIdRequest$outboundSchema.parse(
      deleteV1ConnectionsIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV1ConnectionsIdData$inboundSchema: z.ZodMiniType<
  DeleteV1ConnectionsIdData,
  unknown
> = z.object({
  id: types.string(),
  status: types.literal("revoked"),
});

export function deleteV1ConnectionsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1ConnectionsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1ConnectionsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1ConnectionsIdData' from JSON`,
  );
}

/** @internal */
export const DeleteV1ConnectionsIdResponseBody$inboundSchema: z.ZodMiniType<
  DeleteV1ConnectionsIdResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => DeleteV1ConnectionsIdData$inboundSchema),
});

export function deleteV1ConnectionsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1ConnectionsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1ConnectionsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1ConnectionsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteV1ConnectionsIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV1ConnectionsIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => DeleteV1ConnectionsIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function deleteV1ConnectionsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV1ConnectionsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV1ConnectionsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV1ConnectionsIdResponse' from JSON`,
  );
}
