/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c3570ba4b7e1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1GeoParcelsRequest = {
  lat?: number | undefined;
  lng?: number | undefined;
  inspireId?: string | undefined;
};

export type Parcel = {
  inspireId: string;
  nationalCadastralReference: string | null;
  label: string | null;
  areaSqm: number | null;
  geometry?: any | undefined;
  county: string | null;
  uat: string | null;
};

export type GetV1GeoParcelsData = {
  parcels: Array<Parcel>;
  source: "ancpi-inspire";
};

/**
 * Success
 */
export type GetV1GeoParcelsResponseBody = {
  data: GetV1GeoParcelsData;
};

export type GetV1GeoParcelsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1GeoParcelsResponseBody;
};

/** @internal */
export type GetV1GeoParcelsRequest$Outbound = {
  lat?: number | undefined;
  lng?: number | undefined;
  inspireId?: string | undefined;
};

/** @internal */
export const GetV1GeoParcelsRequest$outboundSchema: z.ZodMiniType<
  GetV1GeoParcelsRequest$Outbound,
  GetV1GeoParcelsRequest
> = z.object({
  lat: z.optional(z.number()),
  lng: z.optional(z.number()),
  inspireId: z.optional(z.string()),
});

export function getV1GeoParcelsRequestToJSON(
  getV1GeoParcelsRequest: GetV1GeoParcelsRequest,
): string {
  return JSON.stringify(
    GetV1GeoParcelsRequest$outboundSchema.parse(getV1GeoParcelsRequest),
  );
}

/** @internal */
export const Parcel$inboundSchema: z.ZodMiniType<Parcel, unknown> = z.object({
  inspireId: types.string(),
  nationalCadastralReference: types.nullable(types.string()),
  label: types.nullable(types.string()),
  areaSqm: types.nullable(types.number()),
  geometry: types.optional(z.any()),
  county: types.nullable(types.string()),
  uat: types.nullable(types.string()),
});

export function parcelFromJSON(
  jsonString: string,
): SafeParseResult<Parcel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Parcel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Parcel' from JSON`,
  );
}

/** @internal */
export const GetV1GeoParcelsData$inboundSchema: z.ZodMiniType<
  GetV1GeoParcelsData,
  unknown
> = z.object({
  parcels: z.array(z.lazy(() => Parcel$inboundSchema)),
  source: types.literal("ancpi-inspire"),
});

export function getV1GeoParcelsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1GeoParcelsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1GeoParcelsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1GeoParcelsData' from JSON`,
  );
}

/** @internal */
export const GetV1GeoParcelsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1GeoParcelsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1GeoParcelsData$inboundSchema),
});

export function getV1GeoParcelsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1GeoParcelsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1GeoParcelsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1GeoParcelsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1GeoParcelsResponse$inboundSchema: z.ZodMiniType<
  GetV1GeoParcelsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1GeoParcelsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1GeoParcelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1GeoParcelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1GeoParcelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1GeoParcelsResponse' from JSON`,
  );
}
