/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2655eb27c0d5
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetV1ConnectionsService = {
  Efactura: "efactura",
  Etransport: "etransport",
  Reges: "reges",
  Spv: "spv",
  Bank: "bank",
} as const;
export type GetV1ConnectionsService = OpenEnum<typeof GetV1ConnectionsService>;

export const GetV1ConnectionsStatus = {
  Pending: "pending",
  Active: "active",
  Error: "error",
  Revoked: "revoked",
} as const;
export type GetV1ConnectionsStatus = OpenEnum<typeof GetV1ConnectionsStatus>;

export type Connection = {
  id: string;
  cui: string;
  service: GetV1ConnectionsService;
  status: GetV1ConnectionsStatus;
  expiresAt: Date | null;
  lastRefreshedAt: Date | null;
  createdAt: Date;
};

export type GetV1ConnectionsData = {
  connections: Array<Connection>;
};

/**
 * Success
 */
export type GetV1ConnectionsResponseBody = {
  data: GetV1ConnectionsData;
};

export type GetV1ConnectionsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ConnectionsResponseBody;
};

/** @internal */
export const GetV1ConnectionsService$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsService,
  unknown
> = openEnums.inboundSchema(GetV1ConnectionsService);

/** @internal */
export const GetV1ConnectionsStatus$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsStatus,
  unknown
> = openEnums.inboundSchema(GetV1ConnectionsStatus);

/** @internal */
export const Connection$inboundSchema: z.ZodMiniType<Connection, unknown> = z
  .object({
    id: types.string(),
    cui: types.string(),
    service: GetV1ConnectionsService$inboundSchema,
    status: GetV1ConnectionsStatus$inboundSchema,
    expiresAt: types.nullable(types.date()),
    lastRefreshedAt: types.nullable(types.date()),
    createdAt: types.date(),
  });

export function connectionFromJSON(
  jsonString: string,
): SafeParseResult<Connection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connection' from JSON`,
  );
}

/** @internal */
export const GetV1ConnectionsData$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsData,
  unknown
> = z.object({
  connections: z.array(z.lazy(() => Connection$inboundSchema)),
});

export function getV1ConnectionsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConnectionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConnectionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConnectionsData' from JSON`,
  );
}

/** @internal */
export const GetV1ConnectionsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1ConnectionsData$inboundSchema),
});

export function getV1ConnectionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConnectionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConnectionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConnectionsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ConnectionsResponse$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1ConnectionsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1ConnectionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConnectionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConnectionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConnectionsResponse' from JSON`,
  );
}
