/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8a6e3b96ad2f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1CompanyCuiBalanceRequest = {
  cui: string;
};

export type GetV1CompanyCuiBalanceLine = {
  indicator: string;
  value: number;
};

export type Year = {
  cui: string;
  year: number;
  available: boolean;
  lines: Array<GetV1CompanyCuiBalanceLine>;
  checkedAt: Date;
};

export type GetV1CompanyCuiBalanceData = {
  cui: string;
  years: Array<Year>;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1CompanyCuiBalanceResponseBody = {
  data: GetV1CompanyCuiBalanceData;
};

export type GetV1CompanyCuiBalanceResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1CompanyCuiBalanceResponseBody;
};

/** @internal */
export type GetV1CompanyCuiBalanceRequest$Outbound = {
  cui: string;
};

/** @internal */
export const GetV1CompanyCuiBalanceRequest$outboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceRequest$Outbound,
  GetV1CompanyCuiBalanceRequest
> = z.object({
  cui: z.string(),
});

export function getV1CompanyCuiBalanceRequestToJSON(
  getV1CompanyCuiBalanceRequest: GetV1CompanyCuiBalanceRequest,
): string {
  return JSON.stringify(
    GetV1CompanyCuiBalanceRequest$outboundSchema.parse(
      getV1CompanyCuiBalanceRequest,
    ),
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceLine$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceLine,
  unknown
> = z.object({
  indicator: types.string(),
  value: types.number(),
});

export function getV1CompanyCuiBalanceLineFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceLine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiBalanceLine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceLine' from JSON`,
  );
}

/** @internal */
export const Year$inboundSchema: z.ZodMiniType<Year, unknown> = z.object({
  cui: types.string(),
  year: types.number(),
  available: types.boolean(),
  lines: z.array(z.lazy(() => GetV1CompanyCuiBalanceLine$inboundSchema)),
  checkedAt: types.date(),
});

export function yearFromJSON(
  jsonString: string,
): SafeParseResult<Year, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Year$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Year' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceData$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceData,
  unknown
> = z.object({
  cui: types.string(),
  years: z.array(z.lazy(() => Year$inboundSchema)),
  checkedAt: types.date(),
});

export function getV1CompanyCuiBalanceDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiBalanceData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceData' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceResponseBody$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1CompanyCuiBalanceData$inboundSchema),
});

export function getV1CompanyCuiBalanceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1CompanyCuiBalanceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceResponse$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1CompanyCuiBalanceResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1CompanyCuiBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceResponse' from JSON`,
  );
}
