/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bb814cc70505
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetV1ProcurementCompanyCuiContractsRole = {
  Authority: "authority",
  Supplier: "supplier",
  Both: "both",
} as const;
export type GetV1ProcurementCompanyCuiContractsRole = ClosedEnum<
  typeof GetV1ProcurementCompanyCuiContractsRole
>;

export type GetV1ProcurementCompanyCuiContractsRequest = {
  cui: string;
  role?: GetV1ProcurementCompanyCuiContractsRole | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  cpv?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type GetV1ProcurementCompanyCuiContractsSummary = {
  contractCount: number;
  authority: number;
  supplier: number;
  totalValue: number | null;
};

export type GetV1ProcurementCompanyCuiContractsContract = {
  contractNumber: string;
  date: string;
  authorityCui: number;
  authorityName: string;
  supplierCui: number | null;
  supplierName: string | null;
  cpvCode: string;
  description: string;
  value: number;
  procedureType: string;
  link: string | null;
  source: string;
  sourceUrl: string;
};

export type GetV1ProcurementCompanyCuiContractsData = {
  total: number;
  summary: GetV1ProcurementCompanyCuiContractsSummary;
  contracts: Array<GetV1ProcurementCompanyCuiContractsContract>;
};

/**
 * Success
 */
export type GetV1ProcurementCompanyCuiContractsResponseBody = {
  data: GetV1ProcurementCompanyCuiContractsData;
};

export type GetV1ProcurementCompanyCuiContractsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ProcurementCompanyCuiContractsResponseBody;
};

/** @internal */
export const GetV1ProcurementCompanyCuiContractsRole$outboundSchema:
  z.ZodMiniEnum<typeof GetV1ProcurementCompanyCuiContractsRole> = z.enum(
    GetV1ProcurementCompanyCuiContractsRole,
  );

/** @internal */
export type GetV1ProcurementCompanyCuiContractsRequest$Outbound = {
  cui: string;
  role?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  cpv?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const GetV1ProcurementCompanyCuiContractsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ProcurementCompanyCuiContractsRequest$Outbound,
    GetV1ProcurementCompanyCuiContractsRequest
  > = z.object({
    cui: z.string(),
    role: z.optional(GetV1ProcurementCompanyCuiContractsRole$outboundSchema),
    dateFrom: z.optional(z.string()),
    dateTo: z.optional(z.string()),
    cpv: z.optional(z.string()),
    limit: z._default(z.int(), 25),
    offset: z._default(z.int(), 0),
  });

export function getV1ProcurementCompanyCuiContractsRequestToJSON(
  getV1ProcurementCompanyCuiContractsRequest:
    GetV1ProcurementCompanyCuiContractsRequest,
): string {
  return JSON.stringify(
    GetV1ProcurementCompanyCuiContractsRequest$outboundSchema.parse(
      getV1ProcurementCompanyCuiContractsRequest,
    ),
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiContractsSummary$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiContractsSummary, unknown> = z.object(
    {
      contractCount: types.number(),
      authority: types.number(),
      supplier: types.number(),
      totalValue: types.nullable(types.number()),
    },
  );

export function getV1ProcurementCompanyCuiContractsSummaryFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiContractsSummary,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiContractsSummary$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiContractsSummary' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiContractsContract$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiContractsContract, unknown> = z.pipe(
    z.object({
      contract_number: types.string(),
      date: types.string(),
      authority_cui: types.number(),
      authority_name: types.string(),
      supplier_cui: types.nullable(types.number()),
      supplier_name: types.nullable(types.string()),
      cpv_code: types.string(),
      description: types.string(),
      value: types.number(),
      procedure_type: types.string(),
      link: types.nullable(types.string()),
      source: types.string(),
      source_url: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "contract_number": "contractNumber",
        "authority_cui": "authorityCui",
        "authority_name": "authorityName",
        "supplier_cui": "supplierCui",
        "supplier_name": "supplierName",
        "cpv_code": "cpvCode",
        "procedure_type": "procedureType",
        "source_url": "sourceUrl",
      });
    }),
  );

export function getV1ProcurementCompanyCuiContractsContractFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiContractsContract,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiContractsContract$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiContractsContract' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiContractsData$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiContractsData, unknown> = z.object({
    total: types.number(),
    summary: z.lazy(() =>
      GetV1ProcurementCompanyCuiContractsSummary$inboundSchema
    ),
    contracts: z.array(
      z.lazy(() => GetV1ProcurementCompanyCuiContractsContract$inboundSchema),
    ),
  });

export function getV1ProcurementCompanyCuiContractsDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiContractsData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiContractsData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiContractsData' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiContractsResponseBody$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiContractsResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1ProcurementCompanyCuiContractsData$inboundSchema),
    });

export function getV1ProcurementCompanyCuiContractsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiContractsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiContractsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiContractsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiContractsResponse$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiContractsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1ProcurementCompanyCuiContractsResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1ProcurementCompanyCuiContractsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiContractsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiContractsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiContractsResponse' from JSON`,
  );
}
