/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6e962797dbca
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1JusticeCasesChangesRequest = {
  number?: string | undefined;
  party?: string | undefined;
  object?: string | undefined;
  court?: string | undefined;
  registeredFrom?: string | undefined;
  registeredTo?: string | undefined;
  modifiedSince: string;
  modifiedUntil?: string | undefined;
};

export type GetV1JusticeCasesChangesParty = {
  name: string;
  role: string | null;
};

export type GetV1JusticeCasesChangesHearing = {
  date: string | null;
  time: string | null;
  solution: string | null;
  panel: string | null;
  solutionSummary: string | null;
  pronouncedAt: string | null;
  documentType: string | null;
  documentNumber: string | null;
  documentDate: string | null;
};

export type GetV1JusticeCasesChangesAppeal = {
  filedAt: string | null;
  filedBy: string | null;
  type: string | null;
};

export type GetV1JusticeCasesChangesCase = {
  number: string;
  oldNumber: string | null;
  date: string | null;
  modifiedAt: string | null;
  court: string | null;
  department: string | null;
  category: string | null;
  stage: string | null;
  subject: string | null;
  parties: Array<GetV1JusticeCasesChangesParty>;
  hearings: Array<GetV1JusticeCasesChangesHearing>;
  appeals: Array<GetV1JusticeCasesChangesAppeal>;
};

export type GetV1JusticeCasesChangesData = {
  cases: Array<GetV1JusticeCasesChangesCase>;
  count: number;
  truncated: boolean;
  source: string;
  criminalMattersExcluded: true;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1JusticeCasesChangesResponseBody = {
  data: GetV1JusticeCasesChangesData;
};

export type GetV1JusticeCasesChangesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1JusticeCasesChangesResponseBody;
};

/** @internal */
export type GetV1JusticeCasesChangesRequest$Outbound = {
  number?: string | undefined;
  party?: string | undefined;
  object?: string | undefined;
  court?: string | undefined;
  registeredFrom?: string | undefined;
  registeredTo?: string | undefined;
  modifiedSince: string;
  modifiedUntil?: string | undefined;
};

/** @internal */
export const GetV1JusticeCasesChangesRequest$outboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesRequest$Outbound,
  GetV1JusticeCasesChangesRequest
> = z.object({
  number: z.optional(z.string()),
  party: z.optional(z.string()),
  object: z.optional(z.string()),
  court: z.optional(z.string()),
  registeredFrom: z.optional(z.string()),
  registeredTo: z.optional(z.string()),
  modifiedSince: z.string(),
  modifiedUntil: z.optional(z.string()),
});

export function getV1JusticeCasesChangesRequestToJSON(
  getV1JusticeCasesChangesRequest: GetV1JusticeCasesChangesRequest,
): string {
  return JSON.stringify(
    GetV1JusticeCasesChangesRequest$outboundSchema.parse(
      getV1JusticeCasesChangesRequest,
    ),
  );
}

/** @internal */
export const GetV1JusticeCasesChangesParty$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesParty,
  unknown
> = z.object({
  name: types.string(),
  role: types.nullable(types.string()),
});

export function getV1JusticeCasesChangesPartyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesParty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesChangesParty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesParty' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesChangesHearing$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesHearing,
  unknown
> = z.object({
  date: types.nullable(types.string()),
  time: types.nullable(types.string()),
  solution: types.nullable(types.string()),
  panel: types.nullable(types.string()),
  solutionSummary: types.nullable(types.string()),
  pronouncedAt: types.nullable(types.string()),
  documentType: types.nullable(types.string()),
  documentNumber: types.nullable(types.string()),
  documentDate: types.nullable(types.string()),
});

export function getV1JusticeCasesChangesHearingFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesHearing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesChangesHearing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesHearing' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesChangesAppeal$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesAppeal,
  unknown
> = z.object({
  filedAt: types.nullable(types.string()),
  filedBy: types.nullable(types.string()),
  type: types.nullable(types.string()),
});

export function getV1JusticeCasesChangesAppealFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesAppeal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesChangesAppeal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesAppeal' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesChangesCase$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesCase,
  unknown
> = z.object({
  number: types.string(),
  oldNumber: types.nullable(types.string()),
  date: types.nullable(types.string()),
  modifiedAt: types.nullable(types.string()),
  court: types.nullable(types.string()),
  department: types.nullable(types.string()),
  category: types.nullable(types.string()),
  stage: types.nullable(types.string()),
  subject: types.nullable(types.string()),
  parties: z.array(z.lazy(() => GetV1JusticeCasesChangesParty$inboundSchema)),
  hearings: z.array(
    z.lazy(() => GetV1JusticeCasesChangesHearing$inboundSchema),
  ),
  appeals: z.array(z.lazy(() => GetV1JusticeCasesChangesAppeal$inboundSchema)),
});

export function getV1JusticeCasesChangesCaseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesCase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesChangesCase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesCase' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesChangesData$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesData,
  unknown
> = z.object({
  cases: z.array(z.lazy(() => GetV1JusticeCasesChangesCase$inboundSchema)),
  count: types.number(),
  truncated: types.boolean(),
  source: types.string(),
  criminalMattersExcluded: types.literal(true),
  checkedAt: types.date(),
});

export function getV1JusticeCasesChangesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesChangesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesData' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesChangesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1JusticeCasesChangesData$inboundSchema),
});

export function getV1JusticeCasesChangesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1JusticeCasesChangesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesChangesResponse$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesChangesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1JusticeCasesChangesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1JusticeCasesChangesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesChangesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesChangesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesChangesResponse' from JSON`,
  );
}
