/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e777c28f0725
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1StatsMatrixRequest = {
  matrix: string;
  filters?: { [k: string]: string } | undefined;
};

export type GetV1StatsMatrixData = {
  matrix: string;
  name: string | null;
  periods: Array<string>;
  data?: any | undefined;
  source: "ins-tempo";
};

/**
 * Success
 */
export type GetV1StatsMatrixResponseBody = {
  data: GetV1StatsMatrixData;
};

export type GetV1StatsMatrixResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1StatsMatrixResponseBody;
};

/** @internal */
export type GetV1StatsMatrixRequest$Outbound = {
  matrix: string;
  filters?: { [k: string]: string } | undefined;
};

/** @internal */
export const GetV1StatsMatrixRequest$outboundSchema: z.ZodMiniType<
  GetV1StatsMatrixRequest$Outbound,
  GetV1StatsMatrixRequest
> = z.object({
  matrix: z.string(),
  filters: z.optional(z.record(z.string(), z.string())),
});

export function getV1StatsMatrixRequestToJSON(
  getV1StatsMatrixRequest: GetV1StatsMatrixRequest,
): string {
  return JSON.stringify(
    GetV1StatsMatrixRequest$outboundSchema.parse(getV1StatsMatrixRequest),
  );
}

/** @internal */
export const GetV1StatsMatrixData$inboundSchema: z.ZodMiniType<
  GetV1StatsMatrixData,
  unknown
> = z.object({
  matrix: types.string(),
  name: types.nullable(types.string()),
  periods: z.array(types.string()),
  data: types.optional(z.any()),
  source: types.literal("ins-tempo"),
});

export function getV1StatsMatrixDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1StatsMatrixData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1StatsMatrixData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1StatsMatrixData' from JSON`,
  );
}

/** @internal */
export const GetV1StatsMatrixResponseBody$inboundSchema: z.ZodMiniType<
  GetV1StatsMatrixResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1StatsMatrixData$inboundSchema),
});

export function getV1StatsMatrixResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1StatsMatrixResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1StatsMatrixResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1StatsMatrixResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1StatsMatrixResponse$inboundSchema: z.ZodMiniType<
  GetV1StatsMatrixResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1StatsMatrixResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1StatsMatrixResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1StatsMatrixResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1StatsMatrixResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1StatsMatrixResponse' from JSON`,
  );
}
