/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a375e2239924
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const MinConfidence = {
  Exact: "exact",
  Strong: "strong",
  Weak: "weak",
} as const;
export type MinConfidence = ClosedEnum<typeof MinConfidence>;

export type GetV1CompanyCuiLitigationRequest = {
  cui: string;
  modifiedSince?: string | undefined;
  court?: string | undefined;
  minConfidence?: MinConfidence | undefined;
};

export type GetV1CompanyCuiLitigationCompany = {
  cui: string;
  name: string;
};

export const Skipped = {
  NaturalPersonEntity: "natural_person_entity",
  NoDistinctiveName: "no_distinctive_name",
} as const;
export type Skipped = OpenEnum<typeof Skipped>;

export type Queried = {
  party: string | null;
  skipped?: Skipped | undefined;
};

export type GetV1CompanyCuiLitigationCaseParty = {
  name: string;
  role: string | null;
};

export type GetV1CompanyCuiLitigationHearing = {
  date: string | null;
  time: string | null;
  solution: string | null;
  panel: string | null;
  solutionSummary: string | null;
  pronouncedAt: string | null;
  documentType: string | null;
  documentNumber: string | null;
  documentDate: string | null;
};

export type GetV1CompanyCuiLitigationAppeal = {
  filedAt: string | null;
  filedBy: string | null;
  type: string | null;
};

export type GetV1CompanyCuiLitigationCase = {
  number: string;
  oldNumber: string | null;
  date: string | null;
  modifiedAt: string | null;
  court: string | null;
  department: string | null;
  category: string | null;
  stage: string | null;
  subject: string | null;
  parties: Array<GetV1CompanyCuiLitigationCaseParty>;
  hearings: Array<GetV1CompanyCuiLitigationHearing>;
  appeals: Array<GetV1CompanyCuiLitigationAppeal>;
};

export const Confidence = {
  Exact: "exact",
  Strong: "strong",
  Weak: "weak",
} as const;
export type Confidence = OpenEnum<typeof Confidence>;

export type GetV1CompanyCuiLitigationParty = {
  name: string;
  role: string | null;
};

export type MatchMatch = {
  confidence: Confidence;
  party: GetV1CompanyCuiLitigationParty;
};

export type Match = {
  case: GetV1CompanyCuiLitigationCase;
  match: MatchMatch;
};

export type GetV1CompanyCuiLitigationData = {
  company: GetV1CompanyCuiLitigationCompany;
  queried: Queried;
  matches: Array<Match>;
  truncated: boolean;
  source: string;
  criminalMattersExcluded: true;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1CompanyCuiLitigationResponseBody = {
  data: GetV1CompanyCuiLitigationData;
};

export type GetV1CompanyCuiLitigationResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1CompanyCuiLitigationResponseBody;
};

/** @internal */
export const MinConfidence$outboundSchema: z.ZodMiniEnum<typeof MinConfidence> =
  z.enum(MinConfidence);

/** @internal */
export type GetV1CompanyCuiLitigationRequest$Outbound = {
  cui: string;
  modifiedSince?: string | undefined;
  court?: string | undefined;
  minConfidence: string;
};

/** @internal */
export const GetV1CompanyCuiLitigationRequest$outboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationRequest$Outbound,
  GetV1CompanyCuiLitigationRequest
> = z.object({
  cui: z.string(),
  modifiedSince: z.optional(z.string()),
  court: z.optional(z.string()),
  minConfidence: z._default(MinConfidence$outboundSchema, "strong"),
});

export function getV1CompanyCuiLitigationRequestToJSON(
  getV1CompanyCuiLitigationRequest: GetV1CompanyCuiLitigationRequest,
): string {
  return JSON.stringify(
    GetV1CompanyCuiLitigationRequest$outboundSchema.parse(
      getV1CompanyCuiLitigationRequest,
    ),
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationCompany$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationCompany,
  unknown
> = z.object({
  cui: types.string(),
  name: types.string(),
});

export function getV1CompanyCuiLitigationCompanyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationCompany, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationCompany$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationCompany' from JSON`,
  );
}

/** @internal */
export const Skipped$inboundSchema: z.ZodMiniType<Skipped, unknown> = openEnums
  .inboundSchema(Skipped);

/** @internal */
export const Queried$inboundSchema: z.ZodMiniType<Queried, unknown> = z.object({
  party: types.nullable(types.string()),
  skipped: types.optional(Skipped$inboundSchema),
});

export function queriedFromJSON(
  jsonString: string,
): SafeParseResult<Queried, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Queried$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Queried' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationCaseParty$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationCaseParty,
  unknown
> = z.object({
  name: types.string(),
  role: types.nullable(types.string()),
});

export function getV1CompanyCuiLitigationCasePartyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationCaseParty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1CompanyCuiLitigationCaseParty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationCaseParty' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationHearing$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationHearing,
  unknown
> = z.object({
  date: types.nullable(types.string()),
  time: types.nullable(types.string()),
  solution: types.nullable(types.string()),
  panel: types.nullable(types.string()),
  solutionSummary: types.nullable(types.string()),
  pronouncedAt: types.nullable(types.string()),
  documentType: types.nullable(types.string()),
  documentNumber: types.nullable(types.string()),
  documentDate: types.nullable(types.string()),
});

export function getV1CompanyCuiLitigationHearingFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationHearing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationHearing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationHearing' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationAppeal$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationAppeal,
  unknown
> = z.object({
  filedAt: types.nullable(types.string()),
  filedBy: types.nullable(types.string()),
  type: types.nullable(types.string()),
});

export function getV1CompanyCuiLitigationAppealFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationAppeal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationAppeal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationAppeal' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationCase$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationCase,
  unknown
> = z.object({
  number: types.string(),
  oldNumber: types.nullable(types.string()),
  date: types.nullable(types.string()),
  modifiedAt: types.nullable(types.string()),
  court: types.nullable(types.string()),
  department: types.nullable(types.string()),
  category: types.nullable(types.string()),
  stage: types.nullable(types.string()),
  subject: types.nullable(types.string()),
  parties: z.array(
    z.lazy(() => GetV1CompanyCuiLitigationCaseParty$inboundSchema),
  ),
  hearings: z.array(
    z.lazy(() => GetV1CompanyCuiLitigationHearing$inboundSchema),
  ),
  appeals: z.array(z.lazy(() => GetV1CompanyCuiLitigationAppeal$inboundSchema)),
});

export function getV1CompanyCuiLitigationCaseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationCase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationCase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationCase' from JSON`,
  );
}

/** @internal */
export const Confidence$inboundSchema: z.ZodMiniType<Confidence, unknown> =
  openEnums.inboundSchema(Confidence);

/** @internal */
export const GetV1CompanyCuiLitigationParty$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationParty,
  unknown
> = z.object({
  name: types.string(),
  role: types.nullable(types.string()),
});

export function getV1CompanyCuiLitigationPartyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationParty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationParty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationParty' from JSON`,
  );
}

/** @internal */
export const MatchMatch$inboundSchema: z.ZodMiniType<MatchMatch, unknown> = z
  .object({
    confidence: Confidence$inboundSchema,
    party: z.lazy(() => GetV1CompanyCuiLitigationParty$inboundSchema),
  });

export function matchMatchFromJSON(
  jsonString: string,
): SafeParseResult<MatchMatch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MatchMatch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MatchMatch' from JSON`,
  );
}

/** @internal */
export const Match$inboundSchema: z.ZodMiniType<Match, unknown> = z.object({
  case: z.lazy(() => GetV1CompanyCuiLitigationCase$inboundSchema),
  match: z.lazy(() => MatchMatch$inboundSchema),
});

export function matchFromJSON(
  jsonString: string,
): SafeParseResult<Match, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Match$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Match' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationData$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationData,
  unknown
> = z.object({
  company: z.lazy(() => GetV1CompanyCuiLitigationCompany$inboundSchema),
  queried: z.lazy(() => Queried$inboundSchema),
  matches: z.array(z.lazy(() => Match$inboundSchema)),
  truncated: types.boolean(),
  source: types.string(),
  criminalMattersExcluded: types.literal(true),
  checkedAt: types.date(),
});

export function getV1CompanyCuiLitigationDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationData' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationResponseBody$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1CompanyCuiLitigationData$inboundSchema),
});

export function getV1CompanyCuiLitigationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1CompanyCuiLitigationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiLitigationResponse$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiLitigationResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1CompanyCuiLitigationResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1CompanyCuiLitigationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiLitigationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiLitigationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiLitigationResponse' from JSON`,
  );
}
