/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b33cf65488fe
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ProcurementCpvCpvContractsRequest = {
  cpv: string;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type GetV1ProcurementCpvCpvContractsSummary = {
  contractCount: number;
  authority: number;
  supplier: number;
  totalValue: number | null;
};

export type GetV1ProcurementCpvCpvContractsContract = {
  contractNumber: string;
  date: string;
  authorityCui: number;
  authorityName: string;
  supplierCui: number | null;
  supplierName: string | null;
  cpvCode: string;
  description: string;
  value: number;
  procedureType: string;
  link: string | null;
  source: string;
  sourceUrl: string;
};

export type GetV1ProcurementCpvCpvContractsData = {
  total: number;
  summary: GetV1ProcurementCpvCpvContractsSummary;
  contracts: Array<GetV1ProcurementCpvCpvContractsContract>;
};

/**
 * Success
 */
export type GetV1ProcurementCpvCpvContractsResponseBody = {
  data: GetV1ProcurementCpvCpvContractsData;
};

export type GetV1ProcurementCpvCpvContractsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ProcurementCpvCpvContractsResponseBody;
};

/** @internal */
export type GetV1ProcurementCpvCpvContractsRequest$Outbound = {
  cpv: string;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const GetV1ProcurementCpvCpvContractsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ProcurementCpvCpvContractsRequest$Outbound,
    GetV1ProcurementCpvCpvContractsRequest
  > = z.object({
    cpv: z.string(),
    dateFrom: z.optional(z.string()),
    dateTo: z.optional(z.string()),
    limit: z._default(z.int(), 25),
    offset: z._default(z.int(), 0),
  });

export function getV1ProcurementCpvCpvContractsRequestToJSON(
  getV1ProcurementCpvCpvContractsRequest:
    GetV1ProcurementCpvCpvContractsRequest,
): string {
  return JSON.stringify(
    GetV1ProcurementCpvCpvContractsRequest$outboundSchema.parse(
      getV1ProcurementCpvCpvContractsRequest,
    ),
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvContractsSummary$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCpvCpvContractsSummary, unknown> = z.object({
    contractCount: types.number(),
    authority: types.number(),
    supplier: types.number(),
    totalValue: types.nullable(types.number()),
  });

export function getV1ProcurementCpvCpvContractsSummaryFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ProcurementCpvCpvContractsSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvContractsSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ProcurementCpvCpvContractsSummary' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvContractsContract$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCpvCpvContractsContract, unknown> = z.pipe(
    z.object({
      contract_number: types.string(),
      date: types.string(),
      authority_cui: types.number(),
      authority_name: types.string(),
      supplier_cui: types.nullable(types.number()),
      supplier_name: types.nullable(types.string()),
      cpv_code: types.string(),
      description: types.string(),
      value: types.number(),
      procedure_type: types.string(),
      link: types.nullable(types.string()),
      source: types.string(),
      source_url: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "contract_number": "contractNumber",
        "authority_cui": "authorityCui",
        "authority_name": "authorityName",
        "supplier_cui": "supplierCui",
        "supplier_name": "supplierName",
        "cpv_code": "cpvCode",
        "procedure_type": "procedureType",
        "source_url": "sourceUrl",
      });
    }),
  );

export function getV1ProcurementCpvCpvContractsContractFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCpvCpvContractsContract,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvContractsContract$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCpvCpvContractsContract' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvContractsData$inboundSchema: z.ZodMiniType<
  GetV1ProcurementCpvCpvContractsData,
  unknown
> = z.object({
  total: types.number(),
  summary: z.lazy(() => GetV1ProcurementCpvCpvContractsSummary$inboundSchema),
  contracts: z.array(
    z.lazy(() => GetV1ProcurementCpvCpvContractsContract$inboundSchema),
  ),
});

export function getV1ProcurementCpvCpvContractsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ProcurementCpvCpvContractsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvContractsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ProcurementCpvCpvContractsData' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvContractsResponseBody$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCpvCpvContractsResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1ProcurementCpvCpvContractsData$inboundSchema),
    });

export function getV1ProcurementCpvCpvContractsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCpvCpvContractsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvContractsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCpvCpvContractsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvContractsResponse$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCpvCpvContractsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1ProcurementCpvCpvContractsResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1ProcurementCpvCpvContractsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCpvCpvContractsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvContractsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCpvCpvContractsResponse' from JSON`,
  );
}
