/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 347b56e0f597
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1RegesEmployeesRequest = {
  cui?: string | undefined;
};

export type Employee = {
  id: string;
  fullName: string;
  cnpMasked: string;
  contractStatus: string;
  startDate: Date | null;
};

export type GetV1RegesEmployeesData = {
  employees: Array<Employee>;
};

/**
 * Success
 */
export type GetV1RegesEmployeesResponseBody = {
  data: GetV1RegesEmployeesData;
};

export type GetV1RegesEmployeesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1RegesEmployeesResponseBody;
};

/** @internal */
export type GetV1RegesEmployeesRequest$Outbound = {
  cui?: string | undefined;
};

/** @internal */
export const GetV1RegesEmployeesRequest$outboundSchema: z.ZodMiniType<
  GetV1RegesEmployeesRequest$Outbound,
  GetV1RegesEmployeesRequest
> = z.object({
  cui: z.optional(z.string()),
});

export function getV1RegesEmployeesRequestToJSON(
  getV1RegesEmployeesRequest: GetV1RegesEmployeesRequest,
): string {
  return JSON.stringify(
    GetV1RegesEmployeesRequest$outboundSchema.parse(getV1RegesEmployeesRequest),
  );
}

/** @internal */
export const Employee$inboundSchema: z.ZodMiniType<Employee, unknown> = z
  .object({
    id: types.string(),
    fullName: types.string(),
    cnpMasked: types.string(),
    contractStatus: types.string(),
    startDate: types.nullable(types.date()),
  });

export function employeeFromJSON(
  jsonString: string,
): SafeParseResult<Employee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Employee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Employee' from JSON`,
  );
}

/** @internal */
export const GetV1RegesEmployeesData$inboundSchema: z.ZodMiniType<
  GetV1RegesEmployeesData,
  unknown
> = z.object({
  employees: z.array(z.lazy(() => Employee$inboundSchema)),
});

export function getV1RegesEmployeesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1RegesEmployeesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1RegesEmployeesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1RegesEmployeesData' from JSON`,
  );
}

/** @internal */
export const GetV1RegesEmployeesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1RegesEmployeesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1RegesEmployeesData$inboundSchema),
});

export function getV1RegesEmployeesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1RegesEmployeesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1RegesEmployeesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1RegesEmployeesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1RegesEmployeesResponse$inboundSchema: z.ZodMiniType<
  GetV1RegesEmployeesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1RegesEmployeesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1RegesEmployeesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1RegesEmployeesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1RegesEmployeesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1RegesEmployeesResponse' from JSON`,
  );
}
