/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: beda596358d3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetV1ProcurementCompanyCuiTendersRole = {
  Authority: "authority",
  Supplier: "supplier",
  Both: "both",
} as const;
export type GetV1ProcurementCompanyCuiTendersRole = ClosedEnum<
  typeof GetV1ProcurementCompanyCuiTendersRole
>;

export type GetV1ProcurementCompanyCuiTendersRequest = {
  cui: string;
  role?: GetV1ProcurementCompanyCuiTendersRole | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  cpv?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type GetV1ProcurementCompanyCuiTendersSummary = {
  contractCount: number;
  authority: number;
  supplier: number;
  totalValue: number | null;
};

export type GetV1ProcurementCompanyCuiTendersContract = {
  contractNumber: string;
  date: string;
  authorityCui: number;
  authorityName: string;
  supplierCui: number | null;
  supplierName: string | null;
  cpvCode: string;
  description: string;
  value: number;
  procedureType: string;
  link: string | null;
  source: string;
  sourceUrl: string;
};

export type GetV1ProcurementCompanyCuiTendersData = {
  total: number;
  summary: GetV1ProcurementCompanyCuiTendersSummary;
  contracts: Array<GetV1ProcurementCompanyCuiTendersContract>;
};

/**
 * Success
 */
export type GetV1ProcurementCompanyCuiTendersResponseBody = {
  data: GetV1ProcurementCompanyCuiTendersData;
};

export type GetV1ProcurementCompanyCuiTendersResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ProcurementCompanyCuiTendersResponseBody;
};

/** @internal */
export const GetV1ProcurementCompanyCuiTendersRole$outboundSchema:
  z.ZodMiniEnum<typeof GetV1ProcurementCompanyCuiTendersRole> = z.enum(
    GetV1ProcurementCompanyCuiTendersRole,
  );

/** @internal */
export type GetV1ProcurementCompanyCuiTendersRequest$Outbound = {
  cui: string;
  role?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  cpv?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const GetV1ProcurementCompanyCuiTendersRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ProcurementCompanyCuiTendersRequest$Outbound,
    GetV1ProcurementCompanyCuiTendersRequest
  > = z.object({
    cui: z.string(),
    role: z.optional(GetV1ProcurementCompanyCuiTendersRole$outboundSchema),
    dateFrom: z.optional(z.string()),
    dateTo: z.optional(z.string()),
    cpv: z.optional(z.string()),
    limit: z._default(z.int(), 25),
    offset: z._default(z.int(), 0),
  });

export function getV1ProcurementCompanyCuiTendersRequestToJSON(
  getV1ProcurementCompanyCuiTendersRequest:
    GetV1ProcurementCompanyCuiTendersRequest,
): string {
  return JSON.stringify(
    GetV1ProcurementCompanyCuiTendersRequest$outboundSchema.parse(
      getV1ProcurementCompanyCuiTendersRequest,
    ),
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiTendersSummary$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiTendersSummary, unknown> = z.object({
    contractCount: types.number(),
    authority: types.number(),
    supplier: types.number(),
    totalValue: types.nullable(types.number()),
  });

export function getV1ProcurementCompanyCuiTendersSummaryFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiTendersSummary,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiTendersSummary$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiTendersSummary' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiTendersContract$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiTendersContract, unknown> = z.pipe(
    z.object({
      contract_number: types.string(),
      date: types.string(),
      authority_cui: types.number(),
      authority_name: types.string(),
      supplier_cui: types.nullable(types.number()),
      supplier_name: types.nullable(types.string()),
      cpv_code: types.string(),
      description: types.string(),
      value: types.number(),
      procedure_type: types.string(),
      link: types.nullable(types.string()),
      source: types.string(),
      source_url: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "contract_number": "contractNumber",
        "authority_cui": "authorityCui",
        "authority_name": "authorityName",
        "supplier_cui": "supplierCui",
        "supplier_name": "supplierName",
        "cpv_code": "cpvCode",
        "procedure_type": "procedureType",
        "source_url": "sourceUrl",
      });
    }),
  );

export function getV1ProcurementCompanyCuiTendersContractFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiTendersContract,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiTendersContract$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiTendersContract' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiTendersData$inboundSchema: z.ZodMiniType<
  GetV1ProcurementCompanyCuiTendersData,
  unknown
> = z.object({
  total: types.number(),
  summary: z.lazy(() => GetV1ProcurementCompanyCuiTendersSummary$inboundSchema),
  contracts: z.array(
    z.lazy(() => GetV1ProcurementCompanyCuiTendersContract$inboundSchema),
  ),
});

export function getV1ProcurementCompanyCuiTendersDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ProcurementCompanyCuiTendersData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiTendersData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ProcurementCompanyCuiTendersData' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiTendersResponseBody$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiTendersResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1ProcurementCompanyCuiTendersData$inboundSchema),
    });

export function getV1ProcurementCompanyCuiTendersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiTendersResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiTendersResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiTendersResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiTendersResponse$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiTendersResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1ProcurementCompanyCuiTendersResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1ProcurementCompanyCuiTendersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiTendersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiTendersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiTendersResponse' from JSON`,
  );
}
