/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8448d6b8954a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationBillsIdStagesRequest = {
  id: string;
};

export const GetV1LegislationBillsIdStagesChamber = {
  Cdep: "cdep",
  Senat: "senat",
} as const;
export type GetV1LegislationBillsIdStagesChamber = OpenEnum<
  typeof GetV1LegislationBillsIdStagesChamber
>;

export type Votes = {
  for: number;
  against: number;
  abstain: number;
  notVoting: number | null;
};

export type DocumentRef = {
  documentId: string | null;
  label: string;
  url: string;
};

export const GetV1LegislationBillsIdStagesSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationBillsIdStagesSourceKind = OpenEnum<
  typeof GetV1LegislationBillsIdStagesSourceKind
>;

export type GetV1LegislationBillsIdStagesItem = {
  seq: number;
  chamber: GetV1LegislationBillsIdStagesChamber;
  stage: string;
  stageOn: string;
  outcome: string | null;
  committee: string | null;
  votes: Votes | null;
  documentRefs: Array<DocumentRef>;
  contentHash: string;
  sourceKind: GetV1LegislationBillsIdStagesSourceKind;
};

export type GetV1LegislationBillsIdStagesData = {
  items: Array<GetV1LegislationBillsIdStagesItem>;
};

/**
 * Success
 */
export type GetV1LegislationBillsIdStagesResponseBody = {
  data: GetV1LegislationBillsIdStagesData;
};

export type GetV1LegislationBillsIdStagesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationBillsIdStagesResponseBody;
};

/** @internal */
export type GetV1LegislationBillsIdStagesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1LegislationBillsIdStagesRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdStagesRequest$Outbound,
  GetV1LegislationBillsIdStagesRequest
> = z.object({
  id: z.string(),
});

export function getV1LegislationBillsIdStagesRequestToJSON(
  getV1LegislationBillsIdStagesRequest: GetV1LegislationBillsIdStagesRequest,
): string {
  return JSON.stringify(
    GetV1LegislationBillsIdStagesRequest$outboundSchema.parse(
      getV1LegislationBillsIdStagesRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationBillsIdStagesChamber$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdStagesChamber,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsIdStagesChamber);

/** @internal */
export const Votes$inboundSchema: z.ZodMiniType<Votes, unknown> = z.pipe(
  z.object({
    for: types.number(),
    against: types.number(),
    abstain: types.number(),
    not_voting: types.nullable(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "not_voting": "notVoting",
    });
  }),
);

export function votesFromJSON(
  jsonString: string,
): SafeParseResult<Votes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Votes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Votes' from JSON`,
  );
}

/** @internal */
export const DocumentRef$inboundSchema: z.ZodMiniType<DocumentRef, unknown> = z
  .pipe(
    z.object({
      document_id: types.nullable(types.string()),
      label: types.string(),
      url: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "document_id": "documentId",
      });
    }),
  );

export function documentRefFromJSON(
  jsonString: string,
): SafeParseResult<DocumentRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentRef' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdStagesSourceKind$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsIdStagesSourceKind, unknown> = openEnums
    .inboundSchema(GetV1LegislationBillsIdStagesSourceKind);

/** @internal */
export const GetV1LegislationBillsIdStagesItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdStagesItem,
  unknown
> = z.pipe(
  z.object({
    seq: types.number(),
    chamber: GetV1LegislationBillsIdStagesChamber$inboundSchema,
    stage: types.string(),
    stage_on: types.string(),
    outcome: types.nullable(types.string()),
    committee: types.nullable(types.string()),
    votes: types.nullable(z.lazy(() => Votes$inboundSchema)),
    document_refs: z.array(z.lazy(() => DocumentRef$inboundSchema)),
    content_hash: types.string(),
    source_kind: GetV1LegislationBillsIdStagesSourceKind$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "stage_on": "stageOn",
      "document_refs": "documentRefs",
      "content_hash": "contentHash",
      "source_kind": "sourceKind",
    });
  }),
);

export function getV1LegislationBillsIdStagesItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdStagesItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdStagesItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdStagesItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdStagesData$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdStagesData,
  unknown
> = z.object({
  items: z.array(z.lazy(() => GetV1LegislationBillsIdStagesItem$inboundSchema)),
});

export function getV1LegislationBillsIdStagesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdStagesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdStagesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdStagesData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdStagesResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsIdStagesResponseBody, unknown> = z.object({
    data: z.lazy(() => GetV1LegislationBillsIdStagesData$inboundSchema),
  });

export function getV1LegislationBillsIdStagesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationBillsIdStagesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdStagesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationBillsIdStagesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdStagesResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdStagesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() =>
      GetV1LegislationBillsIdStagesResponseBody$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationBillsIdStagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdStagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdStagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdStagesResponse' from JSON`,
  );
}
