/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2969f39051b6
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1VatViesCountryCodeVatNumberRequest = {
  countryCode: string;
  vatNumber: string;
};

export type GetV1VatViesCountryCodeVatNumberData = {
  countryCode: string;
  vatNumber: string;
  valid: boolean;
  name: string | null;
  address: string | null;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1VatViesCountryCodeVatNumberResponseBody = {
  data: GetV1VatViesCountryCodeVatNumberData;
};

export type GetV1VatViesCountryCodeVatNumberResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1VatViesCountryCodeVatNumberResponseBody;
};

/** @internal */
export type GetV1VatViesCountryCodeVatNumberRequest$Outbound = {
  countryCode: string;
  vatNumber: string;
};

/** @internal */
export const GetV1VatViesCountryCodeVatNumberRequest$outboundSchema:
  z.ZodMiniType<
    GetV1VatViesCountryCodeVatNumberRequest$Outbound,
    GetV1VatViesCountryCodeVatNumberRequest
  > = z.object({
    countryCode: z.string(),
    vatNumber: z.string(),
  });

export function getV1VatViesCountryCodeVatNumberRequestToJSON(
  getV1VatViesCountryCodeVatNumberRequest:
    GetV1VatViesCountryCodeVatNumberRequest,
): string {
  return JSON.stringify(
    GetV1VatViesCountryCodeVatNumberRequest$outboundSchema.parse(
      getV1VatViesCountryCodeVatNumberRequest,
    ),
  );
}

/** @internal */
export const GetV1VatViesCountryCodeVatNumberData$inboundSchema: z.ZodMiniType<
  GetV1VatViesCountryCodeVatNumberData,
  unknown
> = z.object({
  countryCode: types.string(),
  vatNumber: types.string(),
  valid: types.boolean(),
  name: types.nullable(types.string()),
  address: types.nullable(types.string()),
  checkedAt: types.date(),
});

export function getV1VatViesCountryCodeVatNumberDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1VatViesCountryCodeVatNumberData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1VatViesCountryCodeVatNumberData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1VatViesCountryCodeVatNumberData' from JSON`,
  );
}

/** @internal */
export const GetV1VatViesCountryCodeVatNumberResponseBody$inboundSchema:
  z.ZodMiniType<GetV1VatViesCountryCodeVatNumberResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1VatViesCountryCodeVatNumberData$inboundSchema),
    });

export function getV1VatViesCountryCodeVatNumberResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1VatViesCountryCodeVatNumberResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1VatViesCountryCodeVatNumberResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1VatViesCountryCodeVatNumberResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1VatViesCountryCodeVatNumberResponse$inboundSchema:
  z.ZodMiniType<GetV1VatViesCountryCodeVatNumberResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1VatViesCountryCodeVatNumberResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1VatViesCountryCodeVatNumberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1VatViesCountryCodeVatNumberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1VatViesCountryCodeVatNumberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1VatViesCountryCodeVatNumberResponse' from JSON`,
  );
}
