/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f11c453e989
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Institution = {
  id: string;
  name: string;
  bic?: string | null | undefined;
  logo?: string | null | undefined;
  countries?: Array<string> | undefined;
  maxAccessValidForDays?: number | null | undefined;
};

export type GetV1BankInstitutionsData = {
  institutions: Array<Institution>;
  count: number;
};

/**
 * Success
 */
export type GetV1BankInstitutionsResponseBody = {
  data: GetV1BankInstitutionsData;
};

export type GetV1BankInstitutionsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1BankInstitutionsResponseBody;
};

/** @internal */
export const Institution$inboundSchema: z.ZodMiniType<Institution, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      bic: z.optional(z.nullable(types.string())),
      logo: z.optional(z.nullable(types.string())),
      countries: types.optional(z.array(types.string())),
      max_access_valid_for_days: z.optional(z.nullable(types.number())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "max_access_valid_for_days": "maxAccessValidForDays",
      });
    }),
  );

export function institutionFromJSON(
  jsonString: string,
): SafeParseResult<Institution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Institution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Institution' from JSON`,
  );
}

/** @internal */
export const GetV1BankInstitutionsData$inboundSchema: z.ZodMiniType<
  GetV1BankInstitutionsData,
  unknown
> = z.object({
  institutions: z.array(z.lazy(() => Institution$inboundSchema)),
  count: types.number(),
});

export function getV1BankInstitutionsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankInstitutionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankInstitutionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankInstitutionsData' from JSON`,
  );
}

/** @internal */
export const GetV1BankInstitutionsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1BankInstitutionsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1BankInstitutionsData$inboundSchema),
});

export function getV1BankInstitutionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankInstitutionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankInstitutionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankInstitutionsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1BankInstitutionsResponse$inboundSchema: z.ZodMiniType<
  GetV1BankInstitutionsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1BankInstitutionsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1BankInstitutionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankInstitutionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankInstitutionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankInstitutionsResponse' from JSON`,
  );
}
