/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a614a9eb2859
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1BankAccountsIdTransactionsRequest = {
  id: string;
  from?: string | undefined;
  to?: string | undefined;
};

export type GetV1BankAccountsIdTransactionsAmount = {
  value: string;
  currency: string;
};

export const GetV1BankAccountsIdTransactionsStatus = {
  Booked: "booked",
  Pending: "pending",
} as const;
export type GetV1BankAccountsIdTransactionsStatus = OpenEnum<
  typeof GetV1BankAccountsIdTransactionsStatus
>;

export type Transaction = {
  accountId: string;
  transactionId: string | null;
  bookingDate: string | null;
  valueDate: string | null;
  amount: GetV1BankAccountsIdTransactionsAmount;
  creditorName: string | null;
  creditorIban: string | null;
  debtorName: string | null;
  debtorIban: string | null;
  remittanceInfo: string | null;
  status: GetV1BankAccountsIdTransactionsStatus;
  consentExpiresAt: string | null;
  source: "aggregator";
};

export type GetV1BankAccountsIdTransactionsData = {
  accountId: string;
  transactions: Array<Transaction>;
  count: number;
};

/**
 * Success
 */
export type GetV1BankAccountsIdTransactionsResponseBody = {
  data: GetV1BankAccountsIdTransactionsData;
};

export type GetV1BankAccountsIdTransactionsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1BankAccountsIdTransactionsResponseBody;
};

/** @internal */
export type GetV1BankAccountsIdTransactionsRequest$Outbound = {
  id: string;
  from?: string | undefined;
  to?: string | undefined;
};

/** @internal */
export const GetV1BankAccountsIdTransactionsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1BankAccountsIdTransactionsRequest$Outbound,
    GetV1BankAccountsIdTransactionsRequest
  > = z.object({
    id: z.string(),
    from: z.optional(z.string()),
    to: z.optional(z.string()),
  });

export function getV1BankAccountsIdTransactionsRequestToJSON(
  getV1BankAccountsIdTransactionsRequest:
    GetV1BankAccountsIdTransactionsRequest,
): string {
  return JSON.stringify(
    GetV1BankAccountsIdTransactionsRequest$outboundSchema.parse(
      getV1BankAccountsIdTransactionsRequest,
    ),
  );
}

/** @internal */
export const GetV1BankAccountsIdTransactionsAmount$inboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdTransactionsAmount,
  unknown
> = z.object({
  value: types.string(),
  currency: types.string(),
});

export function getV1BankAccountsIdTransactionsAmountFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankAccountsIdTransactionsAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BankAccountsIdTransactionsAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankAccountsIdTransactionsAmount' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdTransactionsStatus$inboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdTransactionsStatus,
  unknown
> = openEnums.inboundSchema(GetV1BankAccountsIdTransactionsStatus);

/** @internal */
export const Transaction$inboundSchema: z.ZodMiniType<Transaction, unknown> = z
  .object({
    accountId: types.string(),
    transactionId: types.nullable(types.string()),
    bookingDate: types.nullable(types.string()),
    valueDate: types.nullable(types.string()),
    amount: z.lazy(() => GetV1BankAccountsIdTransactionsAmount$inboundSchema),
    creditorName: types.nullable(types.string()),
    creditorIban: types.nullable(types.string()),
    debtorName: types.nullable(types.string()),
    debtorIban: types.nullable(types.string()),
    remittanceInfo: types.nullable(types.string()),
    status: GetV1BankAccountsIdTransactionsStatus$inboundSchema,
    consentExpiresAt: types.nullable(types.string()),
    source: types.literal("aggregator"),
  });

export function transactionFromJSON(
  jsonString: string,
): SafeParseResult<Transaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transaction' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdTransactionsData$inboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdTransactionsData,
  unknown
> = z.object({
  accountId: types.string(),
  transactions: z.array(z.lazy(() => Transaction$inboundSchema)),
  count: types.number(),
});

export function getV1BankAccountsIdTransactionsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankAccountsIdTransactionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BankAccountsIdTransactionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankAccountsIdTransactionsData' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdTransactionsResponseBody$inboundSchema:
  z.ZodMiniType<GetV1BankAccountsIdTransactionsResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1BankAccountsIdTransactionsData$inboundSchema),
    });

export function getV1BankAccountsIdTransactionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1BankAccountsIdTransactionsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BankAccountsIdTransactionsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1BankAccountsIdTransactionsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdTransactionsResponse$inboundSchema:
  z.ZodMiniType<GetV1BankAccountsIdTransactionsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1BankAccountsIdTransactionsResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1BankAccountsIdTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1BankAccountsIdTransactionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BankAccountsIdTransactionsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1BankAccountsIdTransactionsResponse' from JSON`,
  );
}
