/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: efb1b78920cc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1SpvEtvaDecontRequest = {
  cif: string;
  perioada: string;
};

export type GetV1SpvEtvaDecontData = {
  cif: string;
  perioada: string;
  decont?: any | undefined;
};

/**
 * Success
 */
export type GetV1SpvEtvaDecontResponseBody = {
  data: GetV1SpvEtvaDecontData;
};

export type GetV1SpvEtvaDecontResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1SpvEtvaDecontResponseBody;
};

/** @internal */
export type GetV1SpvEtvaDecontRequest$Outbound = {
  cif: string;
  perioada: string;
};

/** @internal */
export const GetV1SpvEtvaDecontRequest$outboundSchema: z.ZodMiniType<
  GetV1SpvEtvaDecontRequest$Outbound,
  GetV1SpvEtvaDecontRequest
> = z.object({
  cif: z.string(),
  perioada: z.string(),
});

export function getV1SpvEtvaDecontRequestToJSON(
  getV1SpvEtvaDecontRequest: GetV1SpvEtvaDecontRequest,
): string {
  return JSON.stringify(
    GetV1SpvEtvaDecontRequest$outboundSchema.parse(getV1SpvEtvaDecontRequest),
  );
}

/** @internal */
export const GetV1SpvEtvaDecontData$inboundSchema: z.ZodMiniType<
  GetV1SpvEtvaDecontData,
  unknown
> = z.object({
  cif: types.string(),
  perioada: types.string(),
  decont: types.optional(z.any()),
});

export function getV1SpvEtvaDecontDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvEtvaDecontData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvEtvaDecontData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvEtvaDecontData' from JSON`,
  );
}

/** @internal */
export const GetV1SpvEtvaDecontResponseBody$inboundSchema: z.ZodMiniType<
  GetV1SpvEtvaDecontResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1SpvEtvaDecontData$inboundSchema),
});

export function getV1SpvEtvaDecontResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvEtvaDecontResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvEtvaDecontResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvEtvaDecontResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1SpvEtvaDecontResponse$inboundSchema: z.ZodMiniType<
  GetV1SpvEtvaDecontResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1SpvEtvaDecontResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1SpvEtvaDecontResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvEtvaDecontResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvEtvaDecontResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvEtvaDecontResponse' from JSON`,
  );
}
