/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c8eb49234700
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1EfacturaInvoicesIdRequest = {
  id: string;
};

export type GetV1EfacturaInvoicesIdData = {
  id: string;
  idIncarcare: string;
  state: string;
  downloadId: string | null;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1EfacturaInvoicesIdResponseBody = {
  data: GetV1EfacturaInvoicesIdData;
};

export type GetV1EfacturaInvoicesIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1EfacturaInvoicesIdResponseBody;
};

/** @internal */
export type GetV1EfacturaInvoicesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1EfacturaInvoicesIdRequest$outboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdRequest$Outbound,
  GetV1EfacturaInvoicesIdRequest
> = z.object({
  id: z.string(),
});

export function getV1EfacturaInvoicesIdRequestToJSON(
  getV1EfacturaInvoicesIdRequest: GetV1EfacturaInvoicesIdRequest,
): string {
  return JSON.stringify(
    GetV1EfacturaInvoicesIdRequest$outboundSchema.parse(
      getV1EfacturaInvoicesIdRequest,
    ),
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdData$inboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdData,
  unknown
> = z.object({
  id: types.string(),
  idIncarcare: types.string(),
  state: types.string(),
  downloadId: types.nullable(types.string()),
  checkedAt: types.date(),
});

export function getV1EfacturaInvoicesIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaInvoicesIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1EfacturaInvoicesIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaInvoicesIdData' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdResponseBody$inboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1EfacturaInvoicesIdData$inboundSchema),
});

export function getV1EfacturaInvoicesIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaInvoicesIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EfacturaInvoicesIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaInvoicesIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdResponse$inboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1EfacturaInvoicesIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1EfacturaInvoicesIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaInvoicesIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1EfacturaInvoicesIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaInvoicesIdResponse' from JSON`,
  );
}
