/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f0d0a6c9b597
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1SpvMessagesRequest = {
  days?: number | undefined;
  cif?: string | undefined;
};

export type GetV1SpvMessagesMessage = {
  id: string;
  detail: string;
  type: string;
  cui: string;
  date: string;
};

export type GetV1SpvMessagesData = {
  messages: Array<GetV1SpvMessagesMessage>;
  serial: string | null;
  cui: string;
};

/**
 * Success
 */
export type GetV1SpvMessagesResponseBody = {
  data: GetV1SpvMessagesData;
};

export type GetV1SpvMessagesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1SpvMessagesResponseBody;
};

/** @internal */
export type GetV1SpvMessagesRequest$Outbound = {
  days: number;
  cif?: string | undefined;
};

/** @internal */
export const GetV1SpvMessagesRequest$outboundSchema: z.ZodMiniType<
  GetV1SpvMessagesRequest$Outbound,
  GetV1SpvMessagesRequest
> = z.object({
  days: z._default(z.int(), 60),
  cif: z.optional(z.string()),
});

export function getV1SpvMessagesRequestToJSON(
  getV1SpvMessagesRequest: GetV1SpvMessagesRequest,
): string {
  return JSON.stringify(
    GetV1SpvMessagesRequest$outboundSchema.parse(getV1SpvMessagesRequest),
  );
}

/** @internal */
export const GetV1SpvMessagesMessage$inboundSchema: z.ZodMiniType<
  GetV1SpvMessagesMessage,
  unknown
> = z.object({
  id: types.string(),
  detail: types.string(),
  type: types.string(),
  cui: types.string(),
  date: types.string(),
});

export function getV1SpvMessagesMessageFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvMessagesMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvMessagesMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvMessagesMessage' from JSON`,
  );
}

/** @internal */
export const GetV1SpvMessagesData$inboundSchema: z.ZodMiniType<
  GetV1SpvMessagesData,
  unknown
> = z.object({
  messages: z.array(z.lazy(() => GetV1SpvMessagesMessage$inboundSchema)),
  serial: types.nullable(types.string()),
  cui: types.string(),
});

export function getV1SpvMessagesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvMessagesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvMessagesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvMessagesData' from JSON`,
  );
}

/** @internal */
export const GetV1SpvMessagesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1SpvMessagesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1SpvMessagesData$inboundSchema),
});

export function getV1SpvMessagesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvMessagesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvMessagesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvMessagesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1SpvMessagesResponse$inboundSchema: z.ZodMiniType<
  GetV1SpvMessagesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1SpvMessagesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1SpvMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvMessagesResponse' from JSON`,
  );
}
