/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 020a549f72eb
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ProcurementContractsNumberRequest = {
  number: string;
};

export type GetV1ProcurementContractsNumberData = {
  contractNumber: string;
  date: string;
  authorityCui: number;
  authorityName: string;
  supplierCui: number | null;
  supplierName: string | null;
  cpvCode: string;
  description: string;
  value: number;
  procedureType: string;
  link: string | null;
  source: string;
  sourceUrl: string;
  authorityAddress: string | null;
  authorityCity: string | null;
  supplierAddress: string | null;
  supplierCity: string | null;
  currency: string | null;
  lots: Array<any> | null;
  publicationDate: string | null;
  tenderDate: string | null;
  awardDate: string | null;
};

/**
 * Success
 */
export type GetV1ProcurementContractsNumberResponseBody = {
  data: GetV1ProcurementContractsNumberData;
};

export type GetV1ProcurementContractsNumberResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ProcurementContractsNumberResponseBody;
};

/** @internal */
export type GetV1ProcurementContractsNumberRequest$Outbound = {
  number: string;
};

/** @internal */
export const GetV1ProcurementContractsNumberRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ProcurementContractsNumberRequest$Outbound,
    GetV1ProcurementContractsNumberRequest
  > = z.object({
    number: z.string(),
  });

export function getV1ProcurementContractsNumberRequestToJSON(
  getV1ProcurementContractsNumberRequest:
    GetV1ProcurementContractsNumberRequest,
): string {
  return JSON.stringify(
    GetV1ProcurementContractsNumberRequest$outboundSchema.parse(
      getV1ProcurementContractsNumberRequest,
    ),
  );
}

/** @internal */
export const GetV1ProcurementContractsNumberData$inboundSchema: z.ZodMiniType<
  GetV1ProcurementContractsNumberData,
  unknown
> = z.pipe(
  z.object({
    contract_number: types.string(),
    date: types.string(),
    authority_cui: types.number(),
    authority_name: types.string(),
    supplier_cui: types.nullable(types.number()),
    supplier_name: types.nullable(types.string()),
    cpv_code: types.string(),
    description: types.string(),
    value: types.number(),
    procedure_type: types.string(),
    link: types.nullable(types.string()),
    source: types.string(),
    source_url: types.string(),
    authority_address: types.nullable(types.string()),
    authority_city: types.nullable(types.string()),
    supplier_address: types.nullable(types.string()),
    supplier_city: types.nullable(types.string()),
    currency: types.nullable(types.string()),
    lots: types.nullable(z.array(z.any())),
    publication_date: types.nullable(types.string()),
    tender_date: types.nullable(types.string()),
    award_date: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "contract_number": "contractNumber",
      "authority_cui": "authorityCui",
      "authority_name": "authorityName",
      "supplier_cui": "supplierCui",
      "supplier_name": "supplierName",
      "cpv_code": "cpvCode",
      "procedure_type": "procedureType",
      "source_url": "sourceUrl",
      "authority_address": "authorityAddress",
      "authority_city": "authorityCity",
      "supplier_address": "supplierAddress",
      "supplier_city": "supplierCity",
      "publication_date": "publicationDate",
      "tender_date": "tenderDate",
      "award_date": "awardDate",
    });
  }),
);

export function getV1ProcurementContractsNumberDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ProcurementContractsNumberData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementContractsNumberData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ProcurementContractsNumberData' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementContractsNumberResponseBody$inboundSchema:
  z.ZodMiniType<GetV1ProcurementContractsNumberResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1ProcurementContractsNumberData$inboundSchema),
    });

export function getV1ProcurementContractsNumberResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementContractsNumberResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementContractsNumberResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementContractsNumberResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementContractsNumberResponse$inboundSchema:
  z.ZodMiniType<GetV1ProcurementContractsNumberResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1ProcurementContractsNumberResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1ProcurementContractsNumberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementContractsNumberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementContractsNumberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementContractsNumberResponse' from JSON`,
  );
}
