/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9e4b93498739
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Rate = {
  currency: string;
  rate: number;
};

export const GetV1FxRatesSource = {
  Bnr: "BNR",
  Ecb: "ECB",
} as const;
export type GetV1FxRatesSource = OpenEnum<typeof GetV1FxRatesSource>;

export type GetV1FxRatesData = {
  base: "RON";
  date: string;
  rates: Array<Rate>;
  source: GetV1FxRatesSource;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1FxRatesResponseBody = {
  data: GetV1FxRatesData;
};

export type GetV1FxRatesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1FxRatesResponseBody;
};

/** @internal */
export const Rate$inboundSchema: z.ZodMiniType<Rate, unknown> = z.object({
  currency: types.string(),
  rate: types.number(),
});

export function rateFromJSON(
  jsonString: string,
): SafeParseResult<Rate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Rate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Rate' from JSON`,
  );
}

/** @internal */
export const GetV1FxRatesSource$inboundSchema: z.ZodMiniType<
  GetV1FxRatesSource,
  unknown
> = openEnums.inboundSchema(GetV1FxRatesSource);

/** @internal */
export const GetV1FxRatesData$inboundSchema: z.ZodMiniType<
  GetV1FxRatesData,
  unknown
> = z.object({
  base: types.literal("RON"),
  date: types.string(),
  rates: z.array(z.lazy(() => Rate$inboundSchema)),
  source: GetV1FxRatesSource$inboundSchema,
  checkedAt: types.date(),
});

export function getV1FxRatesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1FxRatesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1FxRatesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1FxRatesData' from JSON`,
  );
}

/** @internal */
export const GetV1FxRatesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1FxRatesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1FxRatesData$inboundSchema),
});

export function getV1FxRatesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1FxRatesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1FxRatesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1FxRatesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1FxRatesResponse$inboundSchema: z.ZodMiniType<
  GetV1FxRatesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1FxRatesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1FxRatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1FxRatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1FxRatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1FxRatesResponse' from JSON`,
  );
}
