/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 554561105eb4
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1BankTreasuryCuiRequest = {
  cui: string;
};

export type Iban = {
  iban: string;
  treasuryUnit: string;
  beneficiary: string | null;
};

export type GetV1BankTreasuryCuiResult = {
  cui: string;
  ibans: Array<Iban>;
  source: "anaf";
};

export type GetV1BankTreasuryCuiData = {
  result: GetV1BankTreasuryCuiResult;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1BankTreasuryCuiResponseBody = {
  data: GetV1BankTreasuryCuiData;
};

export type GetV1BankTreasuryCuiResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1BankTreasuryCuiResponseBody;
};

/** @internal */
export type GetV1BankTreasuryCuiRequest$Outbound = {
  cui: string;
};

/** @internal */
export const GetV1BankTreasuryCuiRequest$outboundSchema: z.ZodMiniType<
  GetV1BankTreasuryCuiRequest$Outbound,
  GetV1BankTreasuryCuiRequest
> = z.object({
  cui: z.string(),
});

export function getV1BankTreasuryCuiRequestToJSON(
  getV1BankTreasuryCuiRequest: GetV1BankTreasuryCuiRequest,
): string {
  return JSON.stringify(
    GetV1BankTreasuryCuiRequest$outboundSchema.parse(
      getV1BankTreasuryCuiRequest,
    ),
  );
}

/** @internal */
export const Iban$inboundSchema: z.ZodMiniType<Iban, unknown> = z.object({
  iban: types.string(),
  treasuryUnit: types.string(),
  beneficiary: types.nullable(types.string()),
});

export function ibanFromJSON(
  jsonString: string,
): SafeParseResult<Iban, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Iban$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Iban' from JSON`,
  );
}

/** @internal */
export const GetV1BankTreasuryCuiResult$inboundSchema: z.ZodMiniType<
  GetV1BankTreasuryCuiResult,
  unknown
> = z.object({
  cui: types.string(),
  ibans: z.array(z.lazy(() => Iban$inboundSchema)),
  source: types.literal("anaf"),
});

export function getV1BankTreasuryCuiResultFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankTreasuryCuiResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankTreasuryCuiResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankTreasuryCuiResult' from JSON`,
  );
}

/** @internal */
export const GetV1BankTreasuryCuiData$inboundSchema: z.ZodMiniType<
  GetV1BankTreasuryCuiData,
  unknown
> = z.object({
  result: z.lazy(() => GetV1BankTreasuryCuiResult$inboundSchema),
  checkedAt: types.date(),
});

export function getV1BankTreasuryCuiDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankTreasuryCuiData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankTreasuryCuiData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankTreasuryCuiData' from JSON`,
  );
}

/** @internal */
export const GetV1BankTreasuryCuiResponseBody$inboundSchema: z.ZodMiniType<
  GetV1BankTreasuryCuiResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1BankTreasuryCuiData$inboundSchema),
});

export function getV1BankTreasuryCuiResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankTreasuryCuiResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankTreasuryCuiResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankTreasuryCuiResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1BankTreasuryCuiResponse$inboundSchema: z.ZodMiniType<
  GetV1BankTreasuryCuiResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1BankTreasuryCuiResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1BankTreasuryCuiResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankTreasuryCuiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankTreasuryCuiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankTreasuryCuiResponse' from JSON`,
  );
}
