/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bf350e2ef0be
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetV1HealthStatus = {
  Ok: "ok",
  Degraded: "degraded",
  Down: "down",
} as const;
export type GetV1HealthStatus = OpenEnum<typeof GetV1HealthStatus>;

export const Db = {
  Ok: "ok",
  Degraded: "degraded",
  Down: "down",
} as const;
export type Db = OpenEnum<typeof Db>;

export const Redis = {
  Ok: "ok",
  Degraded: "degraded",
  Down: "down",
} as const;
export type Redis = OpenEnum<typeof Redis>;

export const Anaf = {
  Ok: "ok",
  Degraded: "degraded",
  Down: "down",
} as const;
export type Anaf = OpenEnum<typeof Anaf>;

export type Checks = {
  db: Db;
  redis: Redis;
  anaf: Anaf;
};

export type GetV1HealthData = {
  status: GetV1HealthStatus;
  checks: Checks;
};

/**
 * Success
 */
export type GetV1HealthResponseBody = {
  data: GetV1HealthData;
};

export type GetV1HealthResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1HealthResponseBody;
};

/** @internal */
export const GetV1HealthStatus$inboundSchema: z.ZodMiniType<
  GetV1HealthStatus,
  unknown
> = openEnums.inboundSchema(GetV1HealthStatus);

/** @internal */
export const Db$inboundSchema: z.ZodMiniType<Db, unknown> = openEnums
  .inboundSchema(Db);

/** @internal */
export const Redis$inboundSchema: z.ZodMiniType<Redis, unknown> = openEnums
  .inboundSchema(Redis);

/** @internal */
export const Anaf$inboundSchema: z.ZodMiniType<Anaf, unknown> = openEnums
  .inboundSchema(Anaf);

/** @internal */
export const Checks$inboundSchema: z.ZodMiniType<Checks, unknown> = z.object({
  db: Db$inboundSchema,
  redis: Redis$inboundSchema,
  anaf: Anaf$inboundSchema,
});

export function checksFromJSON(
  jsonString: string,
): SafeParseResult<Checks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Checks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Checks' from JSON`,
  );
}

/** @internal */
export const GetV1HealthData$inboundSchema: z.ZodMiniType<
  GetV1HealthData,
  unknown
> = z.object({
  status: GetV1HealthStatus$inboundSchema,
  checks: z.lazy(() => Checks$inboundSchema),
});

export function getV1HealthDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1HealthData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1HealthData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1HealthData' from JSON`,
  );
}

/** @internal */
export const GetV1HealthResponseBody$inboundSchema: z.ZodMiniType<
  GetV1HealthResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1HealthData$inboundSchema),
});

export function getV1HealthResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1HealthResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1HealthResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1HealthResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1HealthResponse$inboundSchema: z.ZodMiniType<
  GetV1HealthResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1HealthResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1HealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1HealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1HealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1HealthResponse' from JSON`,
  );
}
