/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ba992e3bfb41
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetV1LegislationBillsChamber = {
  Cdep: "cdep",
  Senat: "senat",
} as const;
export type GetV1LegislationBillsChamber = ClosedEnum<
  typeof GetV1LegislationBillsChamber
>;

export type GetV1LegislationBillsRequest = {
  chamber?: GetV1LegislationBillsChamber | undefined;
  status?: string | undefined;
  updatedSince?: Date | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
};

export const GetV1LegislationBillsChamberFirst = {
  Cdep: "cdep",
  Senat: "senat",
} as const;
export type GetV1LegislationBillsChamberFirst = OpenEnum<
  typeof GetV1LegislationBillsChamberFirst
>;

export type GetV1LegislationBillsRegistration = {
  plx: string | null;
  l: string | null;
  e: string | null;
  bpi: string | null;
  senatB: string | null;
};

export type GetV1LegislationBillsInitiator = {
  name: string;
  function: string | null;
};

export const GetV1LegislationBillsAmendStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationBillsAmendStatus = OpenEnum<
  typeof GetV1LegislationBillsAmendStatus
>;

export type GetV1LegislationBillsAmend = {
  id: string | null;
  status: GetV1LegislationBillsAmendStatus;
  reason: string | null;
  reference: string;
};

export const GetV1LegislationBillsMoReferenceStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationBillsMoReferenceStatus = OpenEnum<
  typeof GetV1LegislationBillsMoReferenceStatus
>;

export type GetV1LegislationBillsLink = {
  id: string | null;
  status: GetV1LegislationBillsMoReferenceStatus;
  reason: string | null;
};

export type GetV1LegislationBillsMoReference = {
  part: number | null;
  number: string | null;
  issuedOn: string | null;
  link: GetV1LegislationBillsLink;
};

export const GetV1LegislationBillsSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationBillsSourceKind = OpenEnum<
  typeof GetV1LegislationBillsSourceKind
>;

export type GetV1LegislationBillsItem = {
  id: string;
  chamberFirst: GetV1LegislationBillsChamberFirst;
  registration: GetV1LegislationBillsRegistration;
  title: string;
  initiators: Array<GetV1LegislationBillsInitiator>;
  domainTags: Array<string>;
  currentStage: string;
  status: string;
  registeredOn: string;
  lastActivityOn: string | null;
  amends: Array<GetV1LegislationBillsAmend>;
  moReference: GetV1LegislationBillsMoReference | null;
  sourceUrl: string;
  sourceKind: GetV1LegislationBillsSourceKind;
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string | null;
};

export type GetV1LegislationBillsData = {
  items: Array<GetV1LegislationBillsItem>;
  nextCursor: string | null;
};

/**
 * Success
 */
export type GetV1LegislationBillsResponseBody = {
  data: GetV1LegislationBillsData;
};

export type GetV1LegislationBillsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationBillsResponseBody;
};

/** @internal */
export const GetV1LegislationBillsChamber$outboundSchema: z.ZodMiniEnum<
  typeof GetV1LegislationBillsChamber
> = z.enum(GetV1LegislationBillsChamber);

/** @internal */
export type GetV1LegislationBillsRequest$Outbound = {
  chamber?: string | undefined;
  status?: string | undefined;
  updated_since?: string | undefined;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const GetV1LegislationBillsRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationBillsRequest$Outbound,
  GetV1LegislationBillsRequest
> = z.pipe(
  z.object({
    chamber: z.optional(GetV1LegislationBillsChamber$outboundSchema),
    status: z.optional(z.string()),
    updatedSince: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
  }),
  z.transform((v) => {
    return remap$(v, {
      updatedSince: "updated_since",
    });
  }),
);

export function getV1LegislationBillsRequestToJSON(
  getV1LegislationBillsRequest: GetV1LegislationBillsRequest,
): string {
  return JSON.stringify(
    GetV1LegislationBillsRequest$outboundSchema.parse(
      getV1LegislationBillsRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationBillsChamberFirst$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsChamberFirst,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsChamberFirst);

/** @internal */
export const GetV1LegislationBillsRegistration$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsRegistration,
  unknown
> = z.pipe(
  z.object({
    plx: types.nullable(types.string()),
    l: types.nullable(types.string()),
    e: types.nullable(types.string()),
    bpi: types.nullable(types.string()),
    senat_b: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "senat_b": "senatB",
    });
  }),
);

export function getV1LegislationBillsRegistrationFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsRegistration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsRegistration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsRegistration' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsInitiator$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsInitiator,
  unknown
> = z.object({
  name: types.string(),
  function: types.nullable(types.string()),
});

export function getV1LegislationBillsInitiatorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsInitiator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsInitiator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsInitiator' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsAmendStatus$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsAmendStatus,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsAmendStatus);

/** @internal */
export const GetV1LegislationBillsAmend$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsAmend,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationBillsAmendStatus$inboundSchema,
  reason: types.nullable(types.string()),
  reference: types.string(),
});

export function getV1LegislationBillsAmendFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsAmend, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsAmend$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsAmend' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsMoReferenceStatus$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsMoReferenceStatus, unknown> = openEnums
    .inboundSchema(GetV1LegislationBillsMoReferenceStatus);

/** @internal */
export const GetV1LegislationBillsLink$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsLink,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationBillsMoReferenceStatus$inboundSchema,
  reason: types.nullable(types.string()),
});

export function getV1LegislationBillsLinkFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsLink' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsMoReference$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsMoReference,
  unknown
> = z.pipe(
  z.object({
    part: types.nullable(types.number()),
    number: types.nullable(types.string()),
    issued_on: types.nullable(types.string()),
    link: z.lazy(() => GetV1LegislationBillsLink$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issued_on": "issuedOn",
    });
  }),
);

export function getV1LegislationBillsMoReferenceFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsMoReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsMoReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsMoReference' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsSourceKind$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsSourceKind,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsSourceKind);

/** @internal */
export const GetV1LegislationBillsItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    chamber_first: GetV1LegislationBillsChamberFirst$inboundSchema,
    registration: z.lazy(() => GetV1LegislationBillsRegistration$inboundSchema),
    title: types.string(),
    initiators: z.array(
      z.lazy(() => GetV1LegislationBillsInitiator$inboundSchema),
    ),
    domain_tags: z.array(types.string()),
    current_stage: types.string(),
    status: types.string(),
    registered_on: types.string(),
    last_activity_on: types.nullable(types.string()),
    amends: z.array(z.lazy(() => GetV1LegislationBillsAmend$inboundSchema)),
    mo_reference: types.nullable(
      z.lazy(() => GetV1LegislationBillsMoReference$inboundSchema),
    ),
    source_url: types.string(),
    source_kind: GetV1LegislationBillsSourceKind$inboundSchema,
    document_version: types.string(),
    retrieved_at: types.date(),
    content_hash: types.string(),
    coverage_note: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chamber_first": "chamberFirst",
      "domain_tags": "domainTags",
      "current_stage": "currentStage",
      "registered_on": "registeredOn",
      "last_activity_on": "lastActivityOn",
      "mo_reference": "moReference",
      "source_url": "sourceUrl",
      "source_kind": "sourceKind",
      "document_version": "documentVersion",
      "retrieved_at": "retrievedAt",
      "content_hash": "contentHash",
      "coverage_note": "coverageNote",
    });
  }),
);

export function getV1LegislationBillsItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsData$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsData,
  unknown
> = z.pipe(
  z.object({
    items: z.array(z.lazy(() => GetV1LegislationBillsItem$inboundSchema)),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function getV1LegislationBillsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1LegislationBillsData$inboundSchema),
});

export function getV1LegislationBillsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1LegislationBillsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationBillsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsResponse' from JSON`,
  );
}
