/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 53970a75a30d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1BankIbanIbanRequest = {
  iban: string;
};

export type GetV1BankIbanIbanResult = {
  iban: string;
  valid: boolean;
  country: string;
  checkDigitsValid: boolean;
  bankCode: string | null;
  bankName: string | null;
  accountNumber: string | null;
};

export type GetV1BankIbanIbanData = {
  result: GetV1BankIbanIbanResult;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1BankIbanIbanResponseBody = {
  data: GetV1BankIbanIbanData;
};

export type GetV1BankIbanIbanResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1BankIbanIbanResponseBody;
};

/** @internal */
export type GetV1BankIbanIbanRequest$Outbound = {
  iban: string;
};

/** @internal */
export const GetV1BankIbanIbanRequest$outboundSchema: z.ZodMiniType<
  GetV1BankIbanIbanRequest$Outbound,
  GetV1BankIbanIbanRequest
> = z.object({
  iban: z.string(),
});

export function getV1BankIbanIbanRequestToJSON(
  getV1BankIbanIbanRequest: GetV1BankIbanIbanRequest,
): string {
  return JSON.stringify(
    GetV1BankIbanIbanRequest$outboundSchema.parse(getV1BankIbanIbanRequest),
  );
}

/** @internal */
export const GetV1BankIbanIbanResult$inboundSchema: z.ZodMiniType<
  GetV1BankIbanIbanResult,
  unknown
> = z.object({
  iban: types.string(),
  valid: types.boolean(),
  country: types.string(),
  checkDigitsValid: types.boolean(),
  bankCode: types.nullable(types.string()),
  bankName: types.nullable(types.string()),
  accountNumber: types.nullable(types.string()),
});

export function getV1BankIbanIbanResultFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankIbanIbanResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankIbanIbanResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankIbanIbanResult' from JSON`,
  );
}

/** @internal */
export const GetV1BankIbanIbanData$inboundSchema: z.ZodMiniType<
  GetV1BankIbanIbanData,
  unknown
> = z.object({
  result: z.lazy(() => GetV1BankIbanIbanResult$inboundSchema),
  checkedAt: types.date(),
});

export function getV1BankIbanIbanDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankIbanIbanData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankIbanIbanData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankIbanIbanData' from JSON`,
  );
}

/** @internal */
export const GetV1BankIbanIbanResponseBody$inboundSchema: z.ZodMiniType<
  GetV1BankIbanIbanResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1BankIbanIbanData$inboundSchema),
});

export function getV1BankIbanIbanResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankIbanIbanResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankIbanIbanResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankIbanIbanResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1BankIbanIbanResponse$inboundSchema: z.ZodMiniType<
  GetV1BankIbanIbanResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1BankIbanIbanResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1BankIbanIbanResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankIbanIbanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankIbanIbanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankIbanIbanResponse' from JSON`,
  );
}
