/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1a8ff9041b87
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1SearchRequest = {
  q: string;
  limit?: number | undefined;
};

/**
 * Success
 */
export type GetV1SearchResponseBody = {
  data: any;
};

export type GetV1SearchResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1SearchResponseBody;
};

/** @internal */
export type GetV1SearchRequest$Outbound = {
  q: string;
  limit?: number | undefined;
};

/** @internal */
export const GetV1SearchRequest$outboundSchema: z.ZodMiniType<
  GetV1SearchRequest$Outbound,
  GetV1SearchRequest
> = z.object({
  q: z.string(),
  limit: z.optional(z.int()),
});

export function getV1SearchRequestToJSON(
  getV1SearchRequest: GetV1SearchRequest,
): string {
  return JSON.stringify(
    GetV1SearchRequest$outboundSchema.parse(getV1SearchRequest),
  );
}

/** @internal */
export const GetV1SearchResponseBody$inboundSchema: z.ZodMiniType<
  GetV1SearchResponseBody,
  unknown
> = z.object({
  data: z.any(),
});

export function getV1SearchResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SearchResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SearchResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SearchResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1SearchResponse$inboundSchema: z.ZodMiniType<
  GetV1SearchResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1SearchResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1SearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SearchResponse' from JSON`,
  );
}
