/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dadcf4db5dfa
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1BankAccountsIdBalancesRequest = {
  id: string;
};

export type GetV1BankAccountsIdBalancesAmount = {
  value: string;
  currency: string;
};

export type Balance = {
  accountId: string;
  balanceType: string;
  amount: GetV1BankAccountsIdBalancesAmount;
  referenceDate: string | null;
  consentExpiresAt: string | null;
  source: "aggregator";
};

export type GetV1BankAccountsIdBalancesData = {
  accountId: string;
  balances: Array<Balance>;
};

/**
 * Success
 */
export type GetV1BankAccountsIdBalancesResponseBody = {
  data: GetV1BankAccountsIdBalancesData;
};

export type GetV1BankAccountsIdBalancesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1BankAccountsIdBalancesResponseBody;
};

/** @internal */
export type GetV1BankAccountsIdBalancesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1BankAccountsIdBalancesRequest$outboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdBalancesRequest$Outbound,
  GetV1BankAccountsIdBalancesRequest
> = z.object({
  id: z.string(),
});

export function getV1BankAccountsIdBalancesRequestToJSON(
  getV1BankAccountsIdBalancesRequest: GetV1BankAccountsIdBalancesRequest,
): string {
  return JSON.stringify(
    GetV1BankAccountsIdBalancesRequest$outboundSchema.parse(
      getV1BankAccountsIdBalancesRequest,
    ),
  );
}

/** @internal */
export const GetV1BankAccountsIdBalancesAmount$inboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdBalancesAmount,
  unknown
> = z.object({
  value: types.string(),
  currency: types.string(),
});

export function getV1BankAccountsIdBalancesAmountFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankAccountsIdBalancesAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankAccountsIdBalancesAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankAccountsIdBalancesAmount' from JSON`,
  );
}

/** @internal */
export const Balance$inboundSchema: z.ZodMiniType<Balance, unknown> = z.object({
  accountId: types.string(),
  balanceType: types.string(),
  amount: z.lazy(() => GetV1BankAccountsIdBalancesAmount$inboundSchema),
  referenceDate: types.nullable(types.string()),
  consentExpiresAt: types.nullable(types.string()),
  source: types.literal("aggregator"),
});

export function balanceFromJSON(
  jsonString: string,
): SafeParseResult<Balance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Balance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Balance' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdBalancesData$inboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdBalancesData,
  unknown
> = z.object({
  accountId: types.string(),
  balances: z.array(z.lazy(() => Balance$inboundSchema)),
});

export function getV1BankAccountsIdBalancesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankAccountsIdBalancesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1BankAccountsIdBalancesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankAccountsIdBalancesData' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdBalancesResponseBody$inboundSchema:
  z.ZodMiniType<GetV1BankAccountsIdBalancesResponseBody, unknown> = z.object({
    data: z.lazy(() => GetV1BankAccountsIdBalancesData$inboundSchema),
  });

export function getV1BankAccountsIdBalancesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1BankAccountsIdBalancesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BankAccountsIdBalancesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1BankAccountsIdBalancesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1BankAccountsIdBalancesResponse$inboundSchema: z.ZodMiniType<
  GetV1BankAccountsIdBalancesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1BankAccountsIdBalancesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1BankAccountsIdBalancesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1BankAccountsIdBalancesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BankAccountsIdBalancesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1BankAccountsIdBalancesResponse' from JSON`,
  );
}
