/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c6c1f868357f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ProcurementCpvCpvAnalysisRequest = {
  cpv: string;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type PerYear = {
  year: number;
  contracts: number;
  valueRon: number;
};

export type GetV1ProcurementCpvCpvAnalysisData = {
  cpv: string;
  totalContracts: number;
  totalValueRon: number;
  uniqueSuppliers: number;
  uniqueAuthorities: number;
  perYear: Array<PerYear>;
  source: string;
  sourceUrl: string;
};

/**
 * Success
 */
export type GetV1ProcurementCpvCpvAnalysisResponseBody = {
  data: GetV1ProcurementCpvCpvAnalysisData;
};

export type GetV1ProcurementCpvCpvAnalysisResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ProcurementCpvCpvAnalysisResponseBody;
};

/** @internal */
export type GetV1ProcurementCpvCpvAnalysisRequest$Outbound = {
  cpv: string;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const GetV1ProcurementCpvCpvAnalysisRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ProcurementCpvCpvAnalysisRequest$Outbound,
    GetV1ProcurementCpvCpvAnalysisRequest
  > = z.object({
    cpv: z.string(),
    dateFrom: z.optional(z.string()),
    dateTo: z.optional(z.string()),
    limit: z._default(z.int(), 25),
    offset: z._default(z.int(), 0),
  });

export function getV1ProcurementCpvCpvAnalysisRequestToJSON(
  getV1ProcurementCpvCpvAnalysisRequest: GetV1ProcurementCpvCpvAnalysisRequest,
): string {
  return JSON.stringify(
    GetV1ProcurementCpvCpvAnalysisRequest$outboundSchema.parse(
      getV1ProcurementCpvCpvAnalysisRequest,
    ),
  );
}

/** @internal */
export const PerYear$inboundSchema: z.ZodMiniType<PerYear, unknown> = z.object({
  year: types.number(),
  contracts: types.number(),
  valueRon: types.number(),
});

export function perYearFromJSON(
  jsonString: string,
): SafeParseResult<PerYear, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PerYear$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PerYear' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvAnalysisData$inboundSchema: z.ZodMiniType<
  GetV1ProcurementCpvCpvAnalysisData,
  unknown
> = z.pipe(
  z.object({
    cpv: types.string(),
    totalContracts: types.number(),
    totalValueRon: types.number(),
    uniqueSuppliers: types.number(),
    uniqueAuthorities: types.number(),
    perYear: z.array(z.lazy(() => PerYear$inboundSchema)),
    source: types.string(),
    source_url: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "source_url": "sourceUrl",
    });
  }),
);

export function getV1ProcurementCpvCpvAnalysisDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ProcurementCpvCpvAnalysisData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvAnalysisData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ProcurementCpvCpvAnalysisData' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvAnalysisResponseBody$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCpvCpvAnalysisResponseBody, unknown> = z.object(
    {
      data: z.lazy(() => GetV1ProcurementCpvCpvAnalysisData$inboundSchema),
    },
  );

export function getV1ProcurementCpvCpvAnalysisResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCpvCpvAnalysisResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvAnalysisResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCpvCpvAnalysisResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCpvCpvAnalysisResponse$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCpvCpvAnalysisResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1ProcurementCpvCpvAnalysisResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1ProcurementCpvCpvAnalysisResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ProcurementCpvCpvAnalysisResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCpvCpvAnalysisResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ProcurementCpvCpvAnalysisResponse' from JSON`,
  );
}
