/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4f4acf818a97
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationBillsChangesRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  since: Date;
  until?: Date | undefined;
};

export const GetV1LegislationBillsChangesCollection = {
  Bills: "bills",
  Acts: "acts",
  MonitorulOficial: "monitorul_oficial",
} as const;
export type GetV1LegislationBillsChangesCollection = OpenEnum<
  typeof GetV1LegislationBillsChangesCollection
>;

export const GetV1LegislationBillsChangesChangeType = {
  Created: "created",
  Updated: "updated",
  Removed: "removed",
} as const;
export type GetV1LegislationBillsChangesChangeType = OpenEnum<
  typeof GetV1LegislationBillsChangesChangeType
>;

export type GetV1LegislationBillsChangesItem = {
  id: string;
  collection: GetV1LegislationBillsChangesCollection;
  changeType: GetV1LegislationBillsChangesChangeType;
  previousHash: string | null;
  newHash: string;
  observedAt: Date;
};

export type GetV1LegislationBillsChangesData = {
  items: Array<GetV1LegislationBillsChangesItem>;
  nextCursor: string | null;
};

/**
 * Success
 */
export type GetV1LegislationBillsChangesResponseBody = {
  data: GetV1LegislationBillsChangesData;
};

export type GetV1LegislationBillsChangesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationBillsChangesResponseBody;
};

/** @internal */
export type GetV1LegislationBillsChangesRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  since: string;
  until?: string | undefined;
};

/** @internal */
export const GetV1LegislationBillsChangesRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationBillsChangesRequest$Outbound,
  GetV1LegislationBillsChangesRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 50),
  since: z.pipe(z.date(), z.transform(v => v.toISOString())),
  until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function getV1LegislationBillsChangesRequestToJSON(
  getV1LegislationBillsChangesRequest: GetV1LegislationBillsChangesRequest,
): string {
  return JSON.stringify(
    GetV1LegislationBillsChangesRequest$outboundSchema.parse(
      getV1LegislationBillsChangesRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationBillsChangesCollection$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsChangesCollection, unknown> = openEnums
    .inboundSchema(GetV1LegislationBillsChangesCollection);

/** @internal */
export const GetV1LegislationBillsChangesChangeType$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsChangesChangeType, unknown> = openEnums
    .inboundSchema(GetV1LegislationBillsChangesChangeType);

/** @internal */
export const GetV1LegislationBillsChangesItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsChangesItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    collection: GetV1LegislationBillsChangesCollection$inboundSchema,
    change_type: GetV1LegislationBillsChangesChangeType$inboundSchema,
    previous_hash: types.nullable(types.string()),
    new_hash: types.string(),
    observed_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "change_type": "changeType",
      "previous_hash": "previousHash",
      "new_hash": "newHash",
      "observed_at": "observedAt",
    });
  }),
);

export function getV1LegislationBillsChangesItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsChangesItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsChangesItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsChangesItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsChangesData$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsChangesData,
  unknown
> = z.pipe(
  z.object({
    items: z.array(
      z.lazy(() => GetV1LegislationBillsChangesItem$inboundSchema),
    ),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function getV1LegislationBillsChangesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsChangesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsChangesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsChangesData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsChangesResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsChangesResponseBody, unknown> = z.object({
    data: z.lazy(() => GetV1LegislationBillsChangesData$inboundSchema),
  });

export function getV1LegislationBillsChangesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationBillsChangesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsChangesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationBillsChangesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsChangesResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsChangesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() =>
      GetV1LegislationBillsChangesResponseBody$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationBillsChangesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsChangesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsChangesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsChangesResponse' from JSON`,
  );
}
