/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 219726156f75
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1EfacturaInvoicesIdDownloadRequest = {
  id: string;
};

export type GetV1EfacturaInvoicesIdDownloadData = {
  id: string;
  url: string;
  expiresAt: Date;
};

/**
 * Success
 */
export type GetV1EfacturaInvoicesIdDownloadResponseBody = {
  data: GetV1EfacturaInvoicesIdDownloadData;
};

export type GetV1EfacturaInvoicesIdDownloadResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1EfacturaInvoicesIdDownloadResponseBody;
};

/** @internal */
export type GetV1EfacturaInvoicesIdDownloadRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1EfacturaInvoicesIdDownloadRequest$outboundSchema:
  z.ZodMiniType<
    GetV1EfacturaInvoicesIdDownloadRequest$Outbound,
    GetV1EfacturaInvoicesIdDownloadRequest
  > = z.object({
    id: z.string(),
  });

export function getV1EfacturaInvoicesIdDownloadRequestToJSON(
  getV1EfacturaInvoicesIdDownloadRequest:
    GetV1EfacturaInvoicesIdDownloadRequest,
): string {
  return JSON.stringify(
    GetV1EfacturaInvoicesIdDownloadRequest$outboundSchema.parse(
      getV1EfacturaInvoicesIdDownloadRequest,
    ),
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdDownloadData$inboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdDownloadData,
  unknown
> = z.object({
  id: types.string(),
  url: types.string(),
  expiresAt: types.date(),
});

export function getV1EfacturaInvoicesIdDownloadDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaInvoicesIdDownloadData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EfacturaInvoicesIdDownloadData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaInvoicesIdDownloadData' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdDownloadResponseBody$inboundSchema:
  z.ZodMiniType<GetV1EfacturaInvoicesIdDownloadResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1EfacturaInvoicesIdDownloadData$inboundSchema),
    });

export function getV1EfacturaInvoicesIdDownloadResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1EfacturaInvoicesIdDownloadResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EfacturaInvoicesIdDownloadResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1EfacturaInvoicesIdDownloadResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdDownloadResponse$inboundSchema:
  z.ZodMiniType<GetV1EfacturaInvoicesIdDownloadResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1EfacturaInvoicesIdDownloadResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1EfacturaInvoicesIdDownloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1EfacturaInvoicesIdDownloadResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EfacturaInvoicesIdDownloadResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1EfacturaInvoicesIdDownloadResponse' from JSON`,
  );
}
