/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 375856a93460
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1SpvDocumentsIdRequest = {
  id: string;
};

export type GetV1SpvDocumentsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export type GetV1SpvDocumentsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1SpvDocumentsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1SpvDocumentsIdRequest$Outbound,
  GetV1SpvDocumentsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1SpvDocumentsIdRequestToJSON(
  getV1SpvDocumentsIdRequest: GetV1SpvDocumentsIdRequest,
): string {
  return JSON.stringify(
    GetV1SpvDocumentsIdRequest$outboundSchema.parse(getV1SpvDocumentsIdRequest),
  );
}

/** @internal */
export const GetV1SpvDocumentsIdResponse$inboundSchema: z.ZodMiniType<
  GetV1SpvDocumentsIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.custom<ReadableStream<Uint8Array>>(x =>
      x instanceof ReadableStream
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1SpvDocumentsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SpvDocumentsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SpvDocumentsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SpvDocumentsIdResponse' from JSON`,
  );
}
