/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e13625c2e16
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1JusticeCasesRequest = {
  number?: string | undefined;
  party?: string | undefined;
  object?: string | undefined;
  court?: string | undefined;
};

export type GetV1JusticeCasesParty = {
  name: string;
  role: string | null;
};

export type GetV1JusticeCasesHearing = {
  date: string | null;
  time: string | null;
  solution: string | null;
};

export type GetV1JusticeCasesCase = {
  number: string;
  oldNumber: string | null;
  date: string | null;
  modifiedAt: string | null;
  court: string | null;
  department: string | null;
  category: string | null;
  stage: string | null;
  subject: string | null;
  parties: Array<GetV1JusticeCasesParty>;
  hearings: Array<GetV1JusticeCasesHearing>;
};

export type GetV1JusticeCasesData = {
  cases: Array<GetV1JusticeCasesCase>;
  count: number;
  truncated: boolean;
  source: string;
  criminalMattersExcluded: true;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1JusticeCasesResponseBody = {
  data: GetV1JusticeCasesData;
};

export type GetV1JusticeCasesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1JusticeCasesResponseBody;
};

/** @internal */
export type GetV1JusticeCasesRequest$Outbound = {
  number?: string | undefined;
  party?: string | undefined;
  object?: string | undefined;
  court?: string | undefined;
};

/** @internal */
export const GetV1JusticeCasesRequest$outboundSchema: z.ZodMiniType<
  GetV1JusticeCasesRequest$Outbound,
  GetV1JusticeCasesRequest
> = z.object({
  number: z.optional(z.string()),
  party: z.optional(z.string()),
  object: z.optional(z.string()),
  court: z.optional(z.string()),
});

export function getV1JusticeCasesRequestToJSON(
  getV1JusticeCasesRequest: GetV1JusticeCasesRequest,
): string {
  return JSON.stringify(
    GetV1JusticeCasesRequest$outboundSchema.parse(getV1JusticeCasesRequest),
  );
}

/** @internal */
export const GetV1JusticeCasesParty$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesParty,
  unknown
> = z.object({
  name: types.string(),
  role: types.nullable(types.string()),
});

export function getV1JusticeCasesPartyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesParty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesParty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesParty' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesHearing$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesHearing,
  unknown
> = z.object({
  date: types.nullable(types.string()),
  time: types.nullable(types.string()),
  solution: types.nullable(types.string()),
});

export function getV1JusticeCasesHearingFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesHearing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesHearing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesHearing' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesCase$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesCase,
  unknown
> = z.object({
  number: types.string(),
  oldNumber: types.nullable(types.string()),
  date: types.nullable(types.string()),
  modifiedAt: types.nullable(types.string()),
  court: types.nullable(types.string()),
  department: types.nullable(types.string()),
  category: types.nullable(types.string()),
  stage: types.nullable(types.string()),
  subject: types.nullable(types.string()),
  parties: z.array(z.lazy(() => GetV1JusticeCasesParty$inboundSchema)),
  hearings: z.array(z.lazy(() => GetV1JusticeCasesHearing$inboundSchema)),
});

export function getV1JusticeCasesCaseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesCase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesCase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesCase' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesData$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesData,
  unknown
> = z.object({
  cases: z.array(z.lazy(() => GetV1JusticeCasesCase$inboundSchema)),
  count: types.number(),
  truncated: types.boolean(),
  source: types.string(),
  criminalMattersExcluded: types.literal(true),
  checkedAt: types.date(),
});

export function getV1JusticeCasesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesData' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1JusticeCasesData$inboundSchema),
});

export function getV1JusticeCasesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCasesResponse$inboundSchema: z.ZodMiniType<
  GetV1JusticeCasesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1JusticeCasesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1JusticeCasesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCasesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCasesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCasesResponse' from JSON`,
  );
}
