/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad9ab992be4d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationActsRequest = {
  type?: string | undefined;
  number?: string | undefined;
  year?: number | undefined;
  updatedSince?: Date | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
};

export const GetV1LegislationActsStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationActsStatus = OpenEnum<
  typeof GetV1LegislationActsStatus
>;

export type GetV1LegislationActsLink = {
  id: string | null;
  status: GetV1LegislationActsStatus;
  reason: string | null;
};

export type GetV1LegislationActsMoReference = {
  part: number | null;
  number: string | null;
  issuedOn: string | null;
  link: GetV1LegislationActsLink;
};

export const GetV1LegislationActsSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationActsSourceKind = OpenEnum<
  typeof GetV1LegislationActsSourceKind
>;

export type GetV1LegislationActsItem = {
  id: string;
  type: string;
  number: string;
  year: number;
  title: string;
  issuer: string | null;
  moReference: GetV1LegislationActsMoReference | null;
  inForceOn: string | null;
  currentVersion: string | null;
  sourceUrl: string;
  sourceKind: GetV1LegislationActsSourceKind;
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string | null;
};

export type GetV1LegislationActsData = {
  items: Array<GetV1LegislationActsItem>;
  nextCursor: string | null;
};

/**
 * Success
 */
export type GetV1LegislationActsResponseBody = {
  data: GetV1LegislationActsData;
};

export type GetV1LegislationActsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationActsResponseBody;
};

/** @internal */
export type GetV1LegislationActsRequest$Outbound = {
  type?: string | undefined;
  number?: string | undefined;
  year?: number | undefined;
  updated_since?: string | undefined;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const GetV1LegislationActsRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationActsRequest$Outbound,
  GetV1LegislationActsRequest
> = z.pipe(
  z.object({
    type: z.optional(z.string()),
    number: z.optional(z.string()),
    year: z.optional(z.int()),
    updatedSince: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
  }),
  z.transform((v) => {
    return remap$(v, {
      updatedSince: "updated_since",
    });
  }),
);

export function getV1LegislationActsRequestToJSON(
  getV1LegislationActsRequest: GetV1LegislationActsRequest,
): string {
  return JSON.stringify(
    GetV1LegislationActsRequest$outboundSchema.parse(
      getV1LegislationActsRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationActsStatus$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsStatus,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsStatus);

/** @internal */
export const GetV1LegislationActsLink$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsLink,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationActsStatus$inboundSchema,
  reason: types.nullable(types.string()),
});

export function getV1LegislationActsLinkFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsLink' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsMoReference$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsMoReference,
  unknown
> = z.pipe(
  z.object({
    part: types.nullable(types.number()),
    number: types.nullable(types.string()),
    issued_on: types.nullable(types.string()),
    link: z.lazy(() => GetV1LegislationActsLink$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issued_on": "issuedOn",
    });
  }),
);

export function getV1LegislationActsMoReferenceFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsMoReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsMoReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsMoReference' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsSourceKind$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsSourceKind,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsSourceKind);

/** @internal */
export const GetV1LegislationActsItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    type: types.string(),
    number: types.string(),
    year: types.number(),
    title: types.string(),
    issuer: types.nullable(types.string()),
    mo_reference: types.nullable(
      z.lazy(() => GetV1LegislationActsMoReference$inboundSchema),
    ),
    in_force_on: types.nullable(types.string()),
    current_version: types.nullable(types.string()),
    source_url: types.string(),
    source_kind: GetV1LegislationActsSourceKind$inboundSchema,
    document_version: types.string(),
    retrieved_at: types.date(),
    content_hash: types.string(),
    coverage_note: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mo_reference": "moReference",
      "in_force_on": "inForceOn",
      "current_version": "currentVersion",
      "source_url": "sourceUrl",
      "source_kind": "sourceKind",
      "document_version": "documentVersion",
      "retrieved_at": "retrievedAt",
      "content_hash": "contentHash",
      "coverage_note": "coverageNote",
    });
  }),
);

export function getV1LegislationActsItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsData$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsData,
  unknown
> = z.pipe(
  z.object({
    items: z.array(z.lazy(() => GetV1LegislationActsItem$inboundSchema)),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function getV1LegislationActsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1LegislationActsData$inboundSchema),
});

export function getV1LegislationActsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1LegislationActsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationActsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsResponse' from JSON`,
  );
}
