/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e44a0fa3321f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationActsIdRequest = {
  id: string;
};

export const GetV1LegislationActsIdStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationActsIdStatus = OpenEnum<
  typeof GetV1LegislationActsIdStatus
>;

export type GetV1LegislationActsIdLink = {
  id: string | null;
  status: GetV1LegislationActsIdStatus;
  reason: string | null;
};

export type GetV1LegislationActsIdMoReference = {
  part: number | null;
  number: string | null;
  issuedOn: string | null;
  link: GetV1LegislationActsIdLink;
};

export const GetV1LegislationActsIdSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationActsIdSourceKind = OpenEnum<
  typeof GetV1LegislationActsIdSourceKind
>;

export const GetV1LegislationActsIdKind = {
  Title: "title",
  Book: "book",
  Part: "part",
  Chapter: "chapter",
  Section: "section",
  Article: "article",
  Paragraph: "paragraph",
  Annex: "annex",
} as const;
export type GetV1LegislationActsIdKind = OpenEnum<
  typeof GetV1LegislationActsIdKind
>;

export type GetV1LegislationActsIdBody = {
  id: string;
  kind: GetV1LegislationActsIdKind;
  label: string;
  heading: string | null;
  text: string | null;
  children: Array<any>;
};

export type GetV1LegislationActsIdData = {
  id: string;
  type: string;
  number: string;
  year: number;
  title: string;
  issuer: string | null;
  moReference: GetV1LegislationActsIdMoReference | null;
  inForceOn: string | null;
  currentVersion: string | null;
  sourceUrl: string;
  sourceKind: GetV1LegislationActsIdSourceKind;
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string | null;
  body: Array<GetV1LegislationActsIdBody>;
  bodyText: string;
};

/**
 * Success
 */
export type GetV1LegislationActsIdResponseBody = {
  data: GetV1LegislationActsIdData;
};

export type GetV1LegislationActsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationActsIdResponseBody;
};

/** @internal */
export type GetV1LegislationActsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1LegislationActsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdRequest$Outbound,
  GetV1LegislationActsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1LegislationActsIdRequestToJSON(
  getV1LegislationActsIdRequest: GetV1LegislationActsIdRequest,
): string {
  return JSON.stringify(
    GetV1LegislationActsIdRequest$outboundSchema.parse(
      getV1LegislationActsIdRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationActsIdStatus$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdStatus,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsIdStatus);

/** @internal */
export const GetV1LegislationActsIdLink$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdLink,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationActsIdStatus$inboundSchema,
  reason: types.nullable(types.string()),
});

export function getV1LegislationActsIdLinkFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsIdLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdLink' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdMoReference$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdMoReference,
  unknown
> = z.pipe(
  z.object({
    part: types.nullable(types.number()),
    number: types.nullable(types.string()),
    issued_on: types.nullable(types.string()),
    link: z.lazy(() => GetV1LegislationActsIdLink$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issued_on": "issuedOn",
    });
  }),
);

export function getV1LegislationActsIdMoReferenceFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdMoReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsIdMoReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdMoReference' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdSourceKind$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdSourceKind,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsIdSourceKind);

/** @internal */
export const GetV1LegislationActsIdKind$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdKind,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsIdKind);

/** @internal */
export const GetV1LegislationActsIdBody$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdBody,
  unknown
> = z.object({
  id: types.string(),
  kind: GetV1LegislationActsIdKind$inboundSchema,
  label: types.string(),
  heading: types.nullable(types.string()),
  text: types.nullable(types.string()),
  children: z.array(z.any()),
});

export function getV1LegislationActsIdBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsIdBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdData$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    type: types.string(),
    number: types.string(),
    year: types.number(),
    title: types.string(),
    issuer: types.nullable(types.string()),
    mo_reference: types.nullable(
      z.lazy(() => GetV1LegislationActsIdMoReference$inboundSchema),
    ),
    in_force_on: types.nullable(types.string()),
    current_version: types.nullable(types.string()),
    source_url: types.string(),
    source_kind: GetV1LegislationActsIdSourceKind$inboundSchema,
    document_version: types.string(),
    retrieved_at: types.date(),
    content_hash: types.string(),
    coverage_note: types.nullable(types.string()),
    body: z.array(z.lazy(() => GetV1LegislationActsIdBody$inboundSchema)),
    body_text: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mo_reference": "moReference",
      "in_force_on": "inForceOn",
      "current_version": "currentVersion",
      "source_url": "sourceUrl",
      "source_kind": "sourceKind",
      "document_version": "documentVersion",
      "retrieved_at": "retrievedAt",
      "content_hash": "contentHash",
      "coverage_note": "coverageNote",
      "body_text": "bodyText",
    });
  }),
);

export function getV1LegislationActsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdResponseBody$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1LegislationActsIdData$inboundSchema),
});

export function getV1LegislationActsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1LegislationActsIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationActsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdResponse' from JSON`,
  );
}
