/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f35d4b947289
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1EtransportDeclarationsUitRequest = {
  uit: string;
};

export type GetV1EtransportDeclarationsUitData = {
  id: string;
  uit: string;
  status: string;
  detail: { [k: string]: any } | null;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1EtransportDeclarationsUitResponseBody = {
  data: GetV1EtransportDeclarationsUitData;
};

export type GetV1EtransportDeclarationsUitResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1EtransportDeclarationsUitResponseBody;
};

/** @internal */
export type GetV1EtransportDeclarationsUitRequest$Outbound = {
  uit: string;
};

/** @internal */
export const GetV1EtransportDeclarationsUitRequest$outboundSchema:
  z.ZodMiniType<
    GetV1EtransportDeclarationsUitRequest$Outbound,
    GetV1EtransportDeclarationsUitRequest
  > = z.object({
    uit: z.string(),
  });

export function getV1EtransportDeclarationsUitRequestToJSON(
  getV1EtransportDeclarationsUitRequest: GetV1EtransportDeclarationsUitRequest,
): string {
  return JSON.stringify(
    GetV1EtransportDeclarationsUitRequest$outboundSchema.parse(
      getV1EtransportDeclarationsUitRequest,
    ),
  );
}

/** @internal */
export const GetV1EtransportDeclarationsUitData$inboundSchema: z.ZodMiniType<
  GetV1EtransportDeclarationsUitData,
  unknown
> = z.object({
  id: types.string(),
  uit: types.string(),
  status: types.string(),
  detail: types.nullable(z.record(z.string(), z.any())),
  checkedAt: types.date(),
});

export function getV1EtransportDeclarationsUitDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EtransportDeclarationsUitData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EtransportDeclarationsUitData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EtransportDeclarationsUitData' from JSON`,
  );
}

/** @internal */
export const GetV1EtransportDeclarationsUitResponseBody$inboundSchema:
  z.ZodMiniType<GetV1EtransportDeclarationsUitResponseBody, unknown> = z.object(
    {
      data: z.lazy(() => GetV1EtransportDeclarationsUitData$inboundSchema),
    },
  );

export function getV1EtransportDeclarationsUitResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1EtransportDeclarationsUitResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EtransportDeclarationsUitResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1EtransportDeclarationsUitResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1EtransportDeclarationsUitResponse$inboundSchema:
  z.ZodMiniType<GetV1EtransportDeclarationsUitResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1EtransportDeclarationsUitResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1EtransportDeclarationsUitResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EtransportDeclarationsUitResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EtransportDeclarationsUitResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EtransportDeclarationsUitResponse' from JSON`,
  );
}
