/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a217e0356605
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationMonitorulOficialActsIdRequest = {
  id: string;
};

export type Issue = {
  id: string;
  part: number;
  number: string;
  issuedOn: string;
};

export const GetV1LegislationMonitorulOficialActsIdStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationMonitorulOficialActsIdStatus = OpenEnum<
  typeof GetV1LegislationMonitorulOficialActsIdStatus
>;

export type ConsolidatedAct = {
  id: string | null;
  status: GetV1LegislationMonitorulOficialActsIdStatus;
  reason: string | null;
};

export type GetV1LegislationMonitorulOficialActsIdData = {
  id: string;
  type: string;
  title: string;
  issuer: string | null;
  issue: Issue;
  consolidatedAct: ConsolidatedAct;
  sourceUrl: string;
  sourceKind: "derived";
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string;
};

/**
 * Success
 */
export type GetV1LegislationMonitorulOficialActsIdResponseBody = {
  data: GetV1LegislationMonitorulOficialActsIdData;
};

export type GetV1LegislationMonitorulOficialActsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationMonitorulOficialActsIdResponseBody;
};

/** @internal */
export type GetV1LegislationMonitorulOficialActsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1LegislationMonitorulOficialActsIdRequest$outboundSchema:
  z.ZodMiniType<
    GetV1LegislationMonitorulOficialActsIdRequest$Outbound,
    GetV1LegislationMonitorulOficialActsIdRequest
  > = z.object({
    id: z.string(),
  });

export function getV1LegislationMonitorulOficialActsIdRequestToJSON(
  getV1LegislationMonitorulOficialActsIdRequest:
    GetV1LegislationMonitorulOficialActsIdRequest,
): string {
  return JSON.stringify(
    GetV1LegislationMonitorulOficialActsIdRequest$outboundSchema.parse(
      getV1LegislationMonitorulOficialActsIdRequest,
    ),
  );
}

/** @internal */
export const Issue$inboundSchema: z.ZodMiniType<Issue, unknown> = z.pipe(
  z.object({
    id: types.string(),
    part: types.number(),
    number: types.string(),
    issued_on: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issued_on": "issuedOn",
    });
  }),
);

export function issueFromJSON(
  jsonString: string,
): SafeParseResult<Issue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Issue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Issue' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialActsIdStatus$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialActsIdStatus, unknown> =
    openEnums.inboundSchema(GetV1LegislationMonitorulOficialActsIdStatus);

/** @internal */
export const ConsolidatedAct$inboundSchema: z.ZodMiniType<
  ConsolidatedAct,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationMonitorulOficialActsIdStatus$inboundSchema,
  reason: types.nullable(types.string()),
});

export function consolidatedActFromJSON(
  jsonString: string,
): SafeParseResult<ConsolidatedAct, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConsolidatedAct$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConsolidatedAct' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialActsIdData$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialActsIdData, unknown> = z.pipe(
    z.object({
      id: types.string(),
      type: types.string(),
      title: types.string(),
      issuer: types.nullable(types.string()),
      issue: z.lazy(() => Issue$inboundSchema),
      consolidated_act: z.lazy(() => ConsolidatedAct$inboundSchema),
      source_url: types.string(),
      source_kind: types.literal("derived"),
      document_version: types.string(),
      retrieved_at: types.date(),
      content_hash: types.string(),
      coverage_note: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "consolidated_act": "consolidatedAct",
        "source_url": "sourceUrl",
        "source_kind": "sourceKind",
        "document_version": "documentVersion",
        "retrieved_at": "retrievedAt",
        "content_hash": "contentHash",
        "coverage_note": "coverageNote",
      });
    }),
  );

export function getV1LegislationMonitorulOficialActsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialActsIdData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialActsIdData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialActsIdData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialActsIdResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialActsIdResponseBody, unknown> = z
    .object({
      data: z.lazy(() =>
        GetV1LegislationMonitorulOficialActsIdData$inboundSchema
      ),
    });

export function getV1LegislationMonitorulOficialActsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialActsIdResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialActsIdResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialActsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialActsIdResponse$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialActsIdResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetV1LegislationMonitorulOficialActsIdResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getV1LegislationMonitorulOficialActsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialActsIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialActsIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialActsIdResponse' from JSON`,
  );
}
