/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 776f21875f23
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationActsIdVersionsRequest = {
  id: string;
};

export const GetV1LegislationActsIdVersionsStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationActsIdVersionsStatus = OpenEnum<
  typeof GetV1LegislationActsIdVersionsStatus
>;

export type GetV1LegislationActsIdVersionsAmendingAct = {
  id: string | null;
  status: GetV1LegislationActsIdVersionsStatus;
  reason: string | null;
  reference: string | null;
};

export type GetV1LegislationActsIdVersionsItem = {
  version: string;
  effectiveOn: string;
  amendingAct: GetV1LegislationActsIdVersionsAmendingAct;
  sourceDocumentId: string;
  contentHash: string;
};

export type GetV1LegislationActsIdVersionsData = {
  items: Array<GetV1LegislationActsIdVersionsItem>;
};

/**
 * Success
 */
export type GetV1LegislationActsIdVersionsResponseBody = {
  data: GetV1LegislationActsIdVersionsData;
};

export type GetV1LegislationActsIdVersionsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationActsIdVersionsResponseBody;
};

/** @internal */
export type GetV1LegislationActsIdVersionsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1LegislationActsIdVersionsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1LegislationActsIdVersionsRequest$Outbound,
    GetV1LegislationActsIdVersionsRequest
  > = z.object({
    id: z.string(),
  });

export function getV1LegislationActsIdVersionsRequestToJSON(
  getV1LegislationActsIdVersionsRequest: GetV1LegislationActsIdVersionsRequest,
): string {
  return JSON.stringify(
    GetV1LegislationActsIdVersionsRequest$outboundSchema.parse(
      getV1LegislationActsIdVersionsRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsStatus$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdVersionsStatus,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsIdVersionsStatus);

/** @internal */
export const GetV1LegislationActsIdVersionsAmendingAct$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsAmendingAct, unknown> = z.object({
    id: types.nullable(types.string()),
    status: GetV1LegislationActsIdVersionsStatus$inboundSchema,
    reason: types.nullable(types.string()),
    reference: types.nullable(types.string()),
  });

export function getV1LegislationActsIdVersionsAmendingActFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsAmendingAct,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsAmendingAct$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsAmendingAct' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdVersionsItem,
  unknown
> = z.pipe(
  z.object({
    version: types.string(),
    effective_on: types.string(),
    amending_act: z.lazy(() =>
      GetV1LegislationActsIdVersionsAmendingAct$inboundSchema
    ),
    source_document_id: types.string(),
    content_hash: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "effective_on": "effectiveOn",
      "amending_act": "amendingAct",
      "source_document_id": "sourceDocumentId",
      "content_hash": "contentHash",
    });
  }),
);

export function getV1LegislationActsIdVersionsItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdVersionsItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdVersionsItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsData$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsIdVersionsData,
  unknown
> = z.object({
  items: z.array(
    z.lazy(() => GetV1LegislationActsIdVersionsItem$inboundSchema),
  ),
});

export function getV1LegislationActsIdVersionsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdVersionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdVersionsData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsResponseBody, unknown> = z.object(
    {
      data: z.lazy(() => GetV1LegislationActsIdVersionsData$inboundSchema),
    },
  );

export function getV1LegislationActsIdVersionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsResponse$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1LegislationActsIdVersionsResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1LegislationActsIdVersionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsIdVersionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsIdVersionsResponse' from JSON`,
  );
}
