/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b5a94bfac67e
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1EfacturaMessagesRequest = {
  days?: number | undefined;
  cui?: string | undefined;
};

export type GetV1EfacturaMessagesMessage = {
  id: string;
  type: string;
  cui: string;
  createdAt: Date;
  detail: string | null;
};

export type GetV1EfacturaMessagesData = {
  messages: Array<GetV1EfacturaMessagesMessage>;
};

/**
 * Success
 */
export type GetV1EfacturaMessagesResponseBody = {
  data: GetV1EfacturaMessagesData;
};

export type GetV1EfacturaMessagesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1EfacturaMessagesResponseBody;
};

/** @internal */
export type GetV1EfacturaMessagesRequest$Outbound = {
  days?: number | undefined;
  cui?: string | undefined;
};

/** @internal */
export const GetV1EfacturaMessagesRequest$outboundSchema: z.ZodMiniType<
  GetV1EfacturaMessagesRequest$Outbound,
  GetV1EfacturaMessagesRequest
> = z.object({
  days: z.optional(z.int()),
  cui: z.optional(z.string()),
});

export function getV1EfacturaMessagesRequestToJSON(
  getV1EfacturaMessagesRequest: GetV1EfacturaMessagesRequest,
): string {
  return JSON.stringify(
    GetV1EfacturaMessagesRequest$outboundSchema.parse(
      getV1EfacturaMessagesRequest,
    ),
  );
}

/** @internal */
export const GetV1EfacturaMessagesMessage$inboundSchema: z.ZodMiniType<
  GetV1EfacturaMessagesMessage,
  unknown
> = z.object({
  id: types.string(),
  type: types.string(),
  cui: types.string(),
  createdAt: types.date(),
  detail: types.nullable(types.string()),
});

export function getV1EfacturaMessagesMessageFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaMessagesMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1EfacturaMessagesMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaMessagesMessage' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaMessagesData$inboundSchema: z.ZodMiniType<
  GetV1EfacturaMessagesData,
  unknown
> = z.object({
  messages: z.array(z.lazy(() => GetV1EfacturaMessagesMessage$inboundSchema)),
});

export function getV1EfacturaMessagesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaMessagesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1EfacturaMessagesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaMessagesData' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaMessagesResponseBody$inboundSchema: z.ZodMiniType<
  GetV1EfacturaMessagesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1EfacturaMessagesData$inboundSchema),
});

export function getV1EfacturaMessagesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaMessagesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1EfacturaMessagesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaMessagesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1EfacturaMessagesResponse$inboundSchema: z.ZodMiniType<
  GetV1EfacturaMessagesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1EfacturaMessagesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1EfacturaMessagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaMessagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1EfacturaMessagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaMessagesResponse' from JSON`,
  );
}
