/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0af7c3a38567
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationBillsIdRequest = {
  id: string;
};

export const GetV1LegislationBillsIdChamberFirst = {
  Cdep: "cdep",
  Senat: "senat",
} as const;
export type GetV1LegislationBillsIdChamberFirst = OpenEnum<
  typeof GetV1LegislationBillsIdChamberFirst
>;

export type GetV1LegislationBillsIdRegistration = {
  plx: string | null;
  l: string | null;
  e: string | null;
  bpi: string | null;
  senatB: string | null;
};

export type GetV1LegislationBillsIdInitiator = {
  name: string;
  function: string | null;
};

export const GetV1LegislationBillsIdAmendStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationBillsIdAmendStatus = OpenEnum<
  typeof GetV1LegislationBillsIdAmendStatus
>;

export type GetV1LegislationBillsIdAmend = {
  id: string | null;
  status: GetV1LegislationBillsIdAmendStatus;
  reason: string | null;
  reference: string;
};

export const GetV1LegislationBillsIdMoReferenceStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationBillsIdMoReferenceStatus = OpenEnum<
  typeof GetV1LegislationBillsIdMoReferenceStatus
>;

export type GetV1LegislationBillsIdLink = {
  id: string | null;
  status: GetV1LegislationBillsIdMoReferenceStatus;
  reason: string | null;
};

export type GetV1LegislationBillsIdMoReference = {
  part: number | null;
  number: string | null;
  issuedOn: string | null;
  link: GetV1LegislationBillsIdLink;
};

export const GetV1LegislationBillsIdSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationBillsIdSourceKind = OpenEnum<
  typeof GetV1LegislationBillsIdSourceKind
>;

export type GetV1LegislationBillsIdData = {
  id: string;
  chamberFirst: GetV1LegislationBillsIdChamberFirst;
  registration: GetV1LegislationBillsIdRegistration;
  title: string;
  initiators: Array<GetV1LegislationBillsIdInitiator>;
  domainTags: Array<string>;
  currentStage: string;
  status: string;
  registeredOn: string;
  lastActivityOn: string | null;
  amends: Array<GetV1LegislationBillsIdAmend>;
  moReference: GetV1LegislationBillsIdMoReference | null;
  sourceUrl: string;
  sourceKind: GetV1LegislationBillsIdSourceKind;
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string | null;
};

/**
 * Success
 */
export type GetV1LegislationBillsIdResponseBody = {
  data: GetV1LegislationBillsIdData;
};

export type GetV1LegislationBillsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationBillsIdResponseBody;
};

/** @internal */
export type GetV1LegislationBillsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1LegislationBillsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdRequest$Outbound,
  GetV1LegislationBillsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1LegislationBillsIdRequestToJSON(
  getV1LegislationBillsIdRequest: GetV1LegislationBillsIdRequest,
): string {
  return JSON.stringify(
    GetV1LegislationBillsIdRequest$outboundSchema.parse(
      getV1LegislationBillsIdRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationBillsIdChamberFirst$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdChamberFirst,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsIdChamberFirst);

/** @internal */
export const GetV1LegislationBillsIdRegistration$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdRegistration,
  unknown
> = z.pipe(
  z.object({
    plx: types.nullable(types.string()),
    l: types.nullable(types.string()),
    e: types.nullable(types.string()),
    bpi: types.nullable(types.string()),
    senat_b: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "senat_b": "senatB",
    });
  }),
);

export function getV1LegislationBillsIdRegistrationFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdRegistration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdRegistration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdRegistration' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdInitiator$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdInitiator,
  unknown
> = z.object({
  name: types.string(),
  function: types.nullable(types.string()),
});

export function getV1LegislationBillsIdInitiatorFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdInitiator, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdInitiator$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdInitiator' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdAmendStatus$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdAmendStatus,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsIdAmendStatus);

/** @internal */
export const GetV1LegislationBillsIdAmend$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdAmend,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationBillsIdAmendStatus$inboundSchema,
  reason: types.nullable(types.string()),
  reference: types.string(),
});

export function getV1LegislationBillsIdAmendFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdAmend, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdAmend$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdAmend' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdMoReferenceStatus$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsIdMoReferenceStatus, unknown> = openEnums
    .inboundSchema(GetV1LegislationBillsIdMoReferenceStatus);

/** @internal */
export const GetV1LegislationBillsIdLink$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdLink,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationBillsIdMoReferenceStatus$inboundSchema,
  reason: types.nullable(types.string()),
});

export function getV1LegislationBillsIdLinkFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdLink' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdMoReference$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdMoReference,
  unknown
> = z.pipe(
  z.object({
    part: types.nullable(types.number()),
    number: types.nullable(types.string()),
    issued_on: types.nullable(types.string()),
    link: z.lazy(() => GetV1LegislationBillsIdLink$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "issued_on": "issuedOn",
    });
  }),
);

export function getV1LegislationBillsIdMoReferenceFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdMoReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdMoReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdMoReference' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdSourceKind$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdSourceKind,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsIdSourceKind);

/** @internal */
export const GetV1LegislationBillsIdData$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    chamber_first: GetV1LegislationBillsIdChamberFirst$inboundSchema,
    registration: z.lazy(() =>
      GetV1LegislationBillsIdRegistration$inboundSchema
    ),
    title: types.string(),
    initiators: z.array(
      z.lazy(() => GetV1LegislationBillsIdInitiator$inboundSchema),
    ),
    domain_tags: z.array(types.string()),
    current_stage: types.string(),
    status: types.string(),
    registered_on: types.string(),
    last_activity_on: types.nullable(types.string()),
    amends: z.array(z.lazy(() => GetV1LegislationBillsIdAmend$inboundSchema)),
    mo_reference: types.nullable(
      z.lazy(() => GetV1LegislationBillsIdMoReference$inboundSchema),
    ),
    source_url: types.string(),
    source_kind: GetV1LegislationBillsIdSourceKind$inboundSchema,
    document_version: types.string(),
    retrieved_at: types.date(),
    content_hash: types.string(),
    coverage_note: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chamber_first": "chamberFirst",
      "domain_tags": "domainTags",
      "current_stage": "currentStage",
      "registered_on": "registeredOn",
      "last_activity_on": "lastActivityOn",
      "mo_reference": "moReference",
      "source_url": "sourceUrl",
      "source_kind": "sourceKind",
      "document_version": "documentVersion",
      "retrieved_at": "retrievedAt",
      "content_hash": "contentHash",
      "coverage_note": "coverageNote",
    });
  }),
);

export function getV1LegislationBillsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdResponseBody$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1LegislationBillsIdData$inboundSchema),
});

export function getV1LegislationBillsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1LegislationBillsIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationBillsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationBillsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdResponse' from JSON`,
  );
}
