/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4a0cb3840503
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1RegesJobsIdRequest = {
  id: string;
};

export const GetV1RegesJobsIdStatus = {
  Queued: "queued",
  Processing: "processing",
  Done: "done",
  Error: "error",
  Unknown: "unknown",
} as const;
export type GetV1RegesJobsIdStatus = OpenEnum<typeof GetV1RegesJobsIdStatus>;

export type GetV1RegesJobsIdData = {
  jobId: string;
  kind: string;
  status: GetV1RegesJobsIdStatus;
  resourceId: string | null;
  error: string | null;
  createdAt: Date;
  updatedAt: Date;
};

/**
 * Success
 */
export type GetV1RegesJobsIdResponseBody = {
  data: GetV1RegesJobsIdData;
};

export type GetV1RegesJobsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1RegesJobsIdResponseBody;
};

/** @internal */
export type GetV1RegesJobsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1RegesJobsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1RegesJobsIdRequest$Outbound,
  GetV1RegesJobsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1RegesJobsIdRequestToJSON(
  getV1RegesJobsIdRequest: GetV1RegesJobsIdRequest,
): string {
  return JSON.stringify(
    GetV1RegesJobsIdRequest$outboundSchema.parse(getV1RegesJobsIdRequest),
  );
}

/** @internal */
export const GetV1RegesJobsIdStatus$inboundSchema: z.ZodMiniType<
  GetV1RegesJobsIdStatus,
  unknown
> = openEnums.inboundSchema(GetV1RegesJobsIdStatus);

/** @internal */
export const GetV1RegesJobsIdData$inboundSchema: z.ZodMiniType<
  GetV1RegesJobsIdData,
  unknown
> = z.object({
  jobId: types.string(),
  kind: types.string(),
  status: GetV1RegesJobsIdStatus$inboundSchema,
  resourceId: types.nullable(types.string()),
  error: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function getV1RegesJobsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1RegesJobsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1RegesJobsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1RegesJobsIdData' from JSON`,
  );
}

/** @internal */
export const GetV1RegesJobsIdResponseBody$inboundSchema: z.ZodMiniType<
  GetV1RegesJobsIdResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1RegesJobsIdData$inboundSchema),
});

export function getV1RegesJobsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1RegesJobsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1RegesJobsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1RegesJobsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1RegesJobsIdResponse$inboundSchema: z.ZodMiniType<
  GetV1RegesJobsIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1RegesJobsIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1RegesJobsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1RegesJobsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1RegesJobsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1RegesJobsIdResponse' from JSON`,
  );
}
