/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 259a1c4bfeae
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationActsChangesRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  since: Date;
  until?: Date | undefined;
};

export const GetV1LegislationActsChangesCollection = {
  Bills: "bills",
  Acts: "acts",
  MonitorulOficial: "monitorul_oficial",
} as const;
export type GetV1LegislationActsChangesCollection = OpenEnum<
  typeof GetV1LegislationActsChangesCollection
>;

export const GetV1LegislationActsChangesChangeType = {
  Created: "created",
  Updated: "updated",
  Removed: "removed",
} as const;
export type GetV1LegislationActsChangesChangeType = OpenEnum<
  typeof GetV1LegislationActsChangesChangeType
>;

export type GetV1LegislationActsChangesItem = {
  id: string;
  collection: GetV1LegislationActsChangesCollection;
  changeType: GetV1LegislationActsChangesChangeType;
  previousHash: string | null;
  newHash: string;
  observedAt: Date;
};

export type GetV1LegislationActsChangesData = {
  items: Array<GetV1LegislationActsChangesItem>;
  nextCursor: string | null;
};

/**
 * Success
 */
export type GetV1LegislationActsChangesResponseBody = {
  data: GetV1LegislationActsChangesData;
};

export type GetV1LegislationActsChangesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationActsChangesResponseBody;
};

/** @internal */
export type GetV1LegislationActsChangesRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  since: string;
  until?: string | undefined;
};

/** @internal */
export const GetV1LegislationActsChangesRequest$outboundSchema: z.ZodMiniType<
  GetV1LegislationActsChangesRequest$Outbound,
  GetV1LegislationActsChangesRequest
> = z.object({
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 50),
  since: z.pipe(z.date(), z.transform(v => v.toISOString())),
  until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function getV1LegislationActsChangesRequestToJSON(
  getV1LegislationActsChangesRequest: GetV1LegislationActsChangesRequest,
): string {
  return JSON.stringify(
    GetV1LegislationActsChangesRequest$outboundSchema.parse(
      getV1LegislationActsChangesRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationActsChangesCollection$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsChangesCollection,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsChangesCollection);

/** @internal */
export const GetV1LegislationActsChangesChangeType$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsChangesChangeType,
  unknown
> = openEnums.inboundSchema(GetV1LegislationActsChangesChangeType);

/** @internal */
export const GetV1LegislationActsChangesItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsChangesItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    collection: GetV1LegislationActsChangesCollection$inboundSchema,
    change_type: GetV1LegislationActsChangesChangeType$inboundSchema,
    previous_hash: types.nullable(types.string()),
    new_hash: types.string(),
    observed_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "change_type": "changeType",
      "previous_hash": "previousHash",
      "new_hash": "newHash",
      "observed_at": "observedAt",
    });
  }),
);

export function getV1LegislationActsChangesItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsChangesItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsChangesItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsChangesItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsChangesData$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsChangesData,
  unknown
> = z.pipe(
  z.object({
    items: z.array(z.lazy(() => GetV1LegislationActsChangesItem$inboundSchema)),
    next_cursor: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function getV1LegislationActsChangesDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsChangesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1LegislationActsChangesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsChangesData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsChangesResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsChangesResponseBody, unknown> = z.object({
    data: z.lazy(() => GetV1LegislationActsChangesData$inboundSchema),
  });

export function getV1LegislationActsChangesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsChangesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsChangesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsChangesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsChangesResponse$inboundSchema: z.ZodMiniType<
  GetV1LegislationActsChangesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1LegislationActsChangesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1LegislationActsChangesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationActsChangesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsChangesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationActsChangesResponse' from JSON`,
  );
}
