/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a2230df7318b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1CompanyCuiVatStatusRequest = {
  cui: string;
};

export type GetV1CompanyCuiVatStatusData = {
  cui: string;
  vatActive: boolean;
  vatOnPayment: boolean;
  vatNumber: string | null;
  active: boolean;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1CompanyCuiVatStatusResponseBody = {
  data: GetV1CompanyCuiVatStatusData;
};

export type GetV1CompanyCuiVatStatusResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1CompanyCuiVatStatusResponseBody;
};

/** @internal */
export type GetV1CompanyCuiVatStatusRequest$Outbound = {
  cui: string;
};

/** @internal */
export const GetV1CompanyCuiVatStatusRequest$outboundSchema: z.ZodMiniType<
  GetV1CompanyCuiVatStatusRequest$Outbound,
  GetV1CompanyCuiVatStatusRequest
> = z.object({
  cui: z.string(),
});

export function getV1CompanyCuiVatStatusRequestToJSON(
  getV1CompanyCuiVatStatusRequest: GetV1CompanyCuiVatStatusRequest,
): string {
  return JSON.stringify(
    GetV1CompanyCuiVatStatusRequest$outboundSchema.parse(
      getV1CompanyCuiVatStatusRequest,
    ),
  );
}

/** @internal */
export const GetV1CompanyCuiVatStatusData$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiVatStatusData,
  unknown
> = z.object({
  cui: types.string(),
  vatActive: types.boolean(),
  vatOnPayment: types.boolean(),
  vatNumber: types.nullable(types.string()),
  active: types.boolean(),
  checkedAt: types.date(),
});

export function getV1CompanyCuiVatStatusDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiVatStatusData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiVatStatusData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiVatStatusData' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiVatStatusResponseBody$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiVatStatusResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1CompanyCuiVatStatusData$inboundSchema),
});

export function getV1CompanyCuiVatStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiVatStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1CompanyCuiVatStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiVatStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiVatStatusResponse$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiVatStatusResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1CompanyCuiVatStatusResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1CompanyCuiVatStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiVatStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiVatStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiVatStatusResponse' from JSON`,
  );
}
