/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 821e88ddca8f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1JusticeCourtsRequest = {
  q?: string | undefined;
};

export type GetV1JusticeCourtsData = {
  courts: Array<string>;
  count: number;
  source: string;
};

/**
 * Success
 */
export type GetV1JusticeCourtsResponseBody = {
  data: GetV1JusticeCourtsData;
};

export type GetV1JusticeCourtsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1JusticeCourtsResponseBody;
};

/** @internal */
export type GetV1JusticeCourtsRequest$Outbound = {
  q?: string | undefined;
};

/** @internal */
export const GetV1JusticeCourtsRequest$outboundSchema: z.ZodMiniType<
  GetV1JusticeCourtsRequest$Outbound,
  GetV1JusticeCourtsRequest
> = z.object({
  q: z.optional(z.string()),
});

export function getV1JusticeCourtsRequestToJSON(
  getV1JusticeCourtsRequest: GetV1JusticeCourtsRequest,
): string {
  return JSON.stringify(
    GetV1JusticeCourtsRequest$outboundSchema.parse(getV1JusticeCourtsRequest),
  );
}

/** @internal */
export const GetV1JusticeCourtsData$inboundSchema: z.ZodMiniType<
  GetV1JusticeCourtsData,
  unknown
> = z.object({
  courts: z.array(types.string()),
  count: types.number(),
  source: types.string(),
});

export function getV1JusticeCourtsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCourtsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCourtsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCourtsData' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCourtsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1JusticeCourtsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1JusticeCourtsData$inboundSchema),
});

export function getV1JusticeCourtsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCourtsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCourtsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCourtsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeCourtsResponse$inboundSchema: z.ZodMiniType<
  GetV1JusticeCourtsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1JusticeCourtsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1JusticeCourtsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeCourtsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeCourtsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeCourtsResponse' from JSON`,
  );
}
