/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9544fddae9c0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1JusticeHearingsRequest = {
  court: string;
  date: string;
};

export type GetV1JusticeHearingsCase = {
  number: string;
  oldNumber: string | null;
  date: string | null;
  time: string | null;
  category: string | null;
  stage: string | null;
};

export type Session = {
  department: string | null;
  panel: string | null;
  date: string | null;
  time: string | null;
  cases: Array<GetV1JusticeHearingsCase>;
};

export type GetV1JusticeHearingsData = {
  sessions: Array<Session>;
  count: number;
  source: string;
  criminalMattersExcluded: true;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1JusticeHearingsResponseBody = {
  data: GetV1JusticeHearingsData;
};

export type GetV1JusticeHearingsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1JusticeHearingsResponseBody;
};

/** @internal */
export type GetV1JusticeHearingsRequest$Outbound = {
  court: string;
  date: string;
};

/** @internal */
export const GetV1JusticeHearingsRequest$outboundSchema: z.ZodMiniType<
  GetV1JusticeHearingsRequest$Outbound,
  GetV1JusticeHearingsRequest
> = z.object({
  court: z.string(),
  date: z.string(),
});

export function getV1JusticeHearingsRequestToJSON(
  getV1JusticeHearingsRequest: GetV1JusticeHearingsRequest,
): string {
  return JSON.stringify(
    GetV1JusticeHearingsRequest$outboundSchema.parse(
      getV1JusticeHearingsRequest,
    ),
  );
}

/** @internal */
export const GetV1JusticeHearingsCase$inboundSchema: z.ZodMiniType<
  GetV1JusticeHearingsCase,
  unknown
> = z.object({
  number: types.string(),
  oldNumber: types.nullable(types.string()),
  date: types.nullable(types.string()),
  time: types.nullable(types.string()),
  category: types.nullable(types.string()),
  stage: types.nullable(types.string()),
});

export function getV1JusticeHearingsCaseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeHearingsCase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeHearingsCase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeHearingsCase' from JSON`,
  );
}

/** @internal */
export const Session$inboundSchema: z.ZodMiniType<Session, unknown> = z.object({
  department: types.nullable(types.string()),
  panel: types.nullable(types.string()),
  date: types.nullable(types.string()),
  time: types.nullable(types.string()),
  cases: z.array(z.lazy(() => GetV1JusticeHearingsCase$inboundSchema)),
});

export function sessionFromJSON(
  jsonString: string,
): SafeParseResult<Session, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Session$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Session' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeHearingsData$inboundSchema: z.ZodMiniType<
  GetV1JusticeHearingsData,
  unknown
> = z.object({
  sessions: z.array(z.lazy(() => Session$inboundSchema)),
  count: types.number(),
  source: types.string(),
  criminalMattersExcluded: types.literal(true),
  checkedAt: types.date(),
});

export function getV1JusticeHearingsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeHearingsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeHearingsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeHearingsData' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeHearingsResponseBody$inboundSchema: z.ZodMiniType<
  GetV1JusticeHearingsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1JusticeHearingsData$inboundSchema),
});

export function getV1JusticeHearingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeHearingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeHearingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeHearingsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1JusticeHearingsResponse$inboundSchema: z.ZodMiniType<
  GetV1JusticeHearingsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1JusticeHearingsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1JusticeHearingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1JusticeHearingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1JusticeHearingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1JusticeHearingsResponse' from JSON`,
  );
}
