/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 293088c1725e
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationMonitorulOficialChangesRequest = {
  cursor?: string | undefined;
  limit?: number | undefined;
  since: Date;
  until?: Date | undefined;
};

export const GetV1LegislationMonitorulOficialChangesCollection = {
  Bills: "bills",
  Acts: "acts",
  MonitorulOficial: "monitorul_oficial",
} as const;
export type GetV1LegislationMonitorulOficialChangesCollection = OpenEnum<
  typeof GetV1LegislationMonitorulOficialChangesCollection
>;

export const GetV1LegislationMonitorulOficialChangesChangeType = {
  Created: "created",
  Updated: "updated",
  Removed: "removed",
} as const;
export type GetV1LegislationMonitorulOficialChangesChangeType = OpenEnum<
  typeof GetV1LegislationMonitorulOficialChangesChangeType
>;

export type GetV1LegislationMonitorulOficialChangesItem = {
  id: string;
  collection: GetV1LegislationMonitorulOficialChangesCollection;
  changeType: GetV1LegislationMonitorulOficialChangesChangeType;
  previousHash: string | null;
  newHash: string;
  observedAt: Date;
};

export type GetV1LegislationMonitorulOficialChangesData = {
  items: Array<GetV1LegislationMonitorulOficialChangesItem>;
  nextCursor: string | null;
};

/**
 * Success
 */
export type GetV1LegislationMonitorulOficialChangesResponseBody = {
  data: GetV1LegislationMonitorulOficialChangesData;
};

export type GetV1LegislationMonitorulOficialChangesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationMonitorulOficialChangesResponseBody;
};

/** @internal */
export type GetV1LegislationMonitorulOficialChangesRequest$Outbound = {
  cursor?: string | undefined;
  limit: number;
  since: string;
  until?: string | undefined;
};

/** @internal */
export const GetV1LegislationMonitorulOficialChangesRequest$outboundSchema:
  z.ZodMiniType<
    GetV1LegislationMonitorulOficialChangesRequest$Outbound,
    GetV1LegislationMonitorulOficialChangesRequest
  > = z.object({
    cursor: z.optional(z.string()),
    limit: z._default(z.int(), 50),
    since: z.pipe(z.date(), z.transform(v => v.toISOString())),
    until: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  });

export function getV1LegislationMonitorulOficialChangesRequestToJSON(
  getV1LegislationMonitorulOficialChangesRequest:
    GetV1LegislationMonitorulOficialChangesRequest,
): string {
  return JSON.stringify(
    GetV1LegislationMonitorulOficialChangesRequest$outboundSchema.parse(
      getV1LegislationMonitorulOficialChangesRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialChangesCollection$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialChangesCollection, unknown> =
    openEnums.inboundSchema(GetV1LegislationMonitorulOficialChangesCollection);

/** @internal */
export const GetV1LegislationMonitorulOficialChangesChangeType$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialChangesChangeType, unknown> =
    openEnums.inboundSchema(GetV1LegislationMonitorulOficialChangesChangeType);

/** @internal */
export const GetV1LegislationMonitorulOficialChangesItem$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialChangesItem, unknown> = z.pipe(
    z.object({
      id: types.string(),
      collection:
        GetV1LegislationMonitorulOficialChangesCollection$inboundSchema,
      change_type:
        GetV1LegislationMonitorulOficialChangesChangeType$inboundSchema,
      previous_hash: types.nullable(types.string()),
      new_hash: types.string(),
      observed_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "change_type": "changeType",
        "previous_hash": "previousHash",
        "new_hash": "newHash",
        "observed_at": "observedAt",
      });
    }),
  );

export function getV1LegislationMonitorulOficialChangesItemFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialChangesItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialChangesItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialChangesItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialChangesData$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialChangesData, unknown> = z.pipe(
    z.object({
      items: z.array(z.lazy(() =>
        GetV1LegislationMonitorulOficialChangesItem$inboundSchema
      )),
      next_cursor: types.nullable(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "next_cursor": "nextCursor",
      });
    }),
  );

export function getV1LegislationMonitorulOficialChangesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialChangesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialChangesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialChangesData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialChangesResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialChangesResponseBody, unknown> =
    z.object({
      data: z.lazy(() =>
        GetV1LegislationMonitorulOficialChangesData$inboundSchema
      ),
    });

export function getV1LegislationMonitorulOficialChangesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialChangesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialChangesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialChangesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialChangesResponse$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialChangesResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetV1LegislationMonitorulOficialChangesResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getV1LegislationMonitorulOficialChangesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialChangesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialChangesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialChangesResponse' from JSON`,
  );
}
