/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 07d09c69a6b1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const GetV1ProcurementCompanyCuiDirectPurchasesRole = {
  Authority: "authority",
  Supplier: "supplier",
  Both: "both",
} as const;
export type GetV1ProcurementCompanyCuiDirectPurchasesRole = ClosedEnum<
  typeof GetV1ProcurementCompanyCuiDirectPurchasesRole
>;

export type GetV1ProcurementCompanyCuiDirectPurchasesRequest = {
  cui: string;
  role?: GetV1ProcurementCompanyCuiDirectPurchasesRole | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  cpv?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type GetV1ProcurementCompanyCuiDirectPurchasesSummary = {
  contractCount: number;
  authority: number;
  supplier: number;
  totalValue: number | null;
};

export type GetV1ProcurementCompanyCuiDirectPurchasesContract = {
  contractNumber: string;
  date: string;
  authorityCui: number;
  authorityName: string;
  supplierCui: number | null;
  supplierName: string | null;
  cpvCode: string;
  description: string;
  value: number;
  procedureType: string;
  link: string | null;
  source: string;
  sourceUrl: string;
};

export type GetV1ProcurementCompanyCuiDirectPurchasesData = {
  total: number;
  summary: GetV1ProcurementCompanyCuiDirectPurchasesSummary;
  contracts: Array<GetV1ProcurementCompanyCuiDirectPurchasesContract>;
};

/**
 * Success
 */
export type GetV1ProcurementCompanyCuiDirectPurchasesResponseBody = {
  data: GetV1ProcurementCompanyCuiDirectPurchasesData;
};

export type GetV1ProcurementCompanyCuiDirectPurchasesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ProcurementCompanyCuiDirectPurchasesResponseBody;
};

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesRole$outboundSchema:
  z.ZodMiniEnum<typeof GetV1ProcurementCompanyCuiDirectPurchasesRole> = z.enum(
    GetV1ProcurementCompanyCuiDirectPurchasesRole,
  );

/** @internal */
export type GetV1ProcurementCompanyCuiDirectPurchasesRequest$Outbound = {
  cui: string;
  role?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  cpv?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ProcurementCompanyCuiDirectPurchasesRequest$Outbound,
    GetV1ProcurementCompanyCuiDirectPurchasesRequest
  > = z.object({
    cui: z.string(),
    role: z.optional(
      GetV1ProcurementCompanyCuiDirectPurchasesRole$outboundSchema,
    ),
    dateFrom: z.optional(z.string()),
    dateTo: z.optional(z.string()),
    cpv: z.optional(z.string()),
    limit: z._default(z.int(), 25),
    offset: z._default(z.int(), 0),
  });

export function getV1ProcurementCompanyCuiDirectPurchasesRequestToJSON(
  getV1ProcurementCompanyCuiDirectPurchasesRequest:
    GetV1ProcurementCompanyCuiDirectPurchasesRequest,
): string {
  return JSON.stringify(
    GetV1ProcurementCompanyCuiDirectPurchasesRequest$outboundSchema.parse(
      getV1ProcurementCompanyCuiDirectPurchasesRequest,
    ),
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesSummary$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiDirectPurchasesSummary, unknown> = z
    .object({
      contractCount: types.number(),
      authority: types.number(),
      supplier: types.number(),
      totalValue: types.nullable(types.number()),
    });

export function getV1ProcurementCompanyCuiDirectPurchasesSummaryFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiDirectPurchasesSummary,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiDirectPurchasesSummary$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiDirectPurchasesSummary' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesContract$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiDirectPurchasesContract, unknown> = z
    .pipe(
      z.object({
        contract_number: types.string(),
        date: types.string(),
        authority_cui: types.number(),
        authority_name: types.string(),
        supplier_cui: types.nullable(types.number()),
        supplier_name: types.nullable(types.string()),
        cpv_code: types.string(),
        description: types.string(),
        value: types.number(),
        procedure_type: types.string(),
        link: types.nullable(types.string()),
        source: types.string(),
        source_url: types.string(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "contract_number": "contractNumber",
          "authority_cui": "authorityCui",
          "authority_name": "authorityName",
          "supplier_cui": "supplierCui",
          "supplier_name": "supplierName",
          "cpv_code": "cpvCode",
          "procedure_type": "procedureType",
          "source_url": "sourceUrl",
        });
      }),
    );

export function getV1ProcurementCompanyCuiDirectPurchasesContractFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiDirectPurchasesContract,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiDirectPurchasesContract$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiDirectPurchasesContract' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesData$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiDirectPurchasesData, unknown> = z
    .object({
      total: types.number(),
      summary: z.lazy(() =>
        GetV1ProcurementCompanyCuiDirectPurchasesSummary$inboundSchema
      ),
      contracts: z.array(
        z.lazy(() =>
          GetV1ProcurementCompanyCuiDirectPurchasesContract$inboundSchema
        ),
      ),
    });

export function getV1ProcurementCompanyCuiDirectPurchasesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiDirectPurchasesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiDirectPurchasesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiDirectPurchasesData' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesResponseBody$inboundSchema:
  z.ZodMiniType<
    GetV1ProcurementCompanyCuiDirectPurchasesResponseBody,
    unknown
  > = z.object({
    data: z.lazy(() =>
      GetV1ProcurementCompanyCuiDirectPurchasesData$inboundSchema
    ),
  });

export function getV1ProcurementCompanyCuiDirectPurchasesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiDirectPurchasesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiDirectPurchasesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiDirectPurchasesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ProcurementCompanyCuiDirectPurchasesResponse$inboundSchema:
  z.ZodMiniType<GetV1ProcurementCompanyCuiDirectPurchasesResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetV1ProcurementCompanyCuiDirectPurchasesResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getV1ProcurementCompanyCuiDirectPurchasesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1ProcurementCompanyCuiDirectPurchasesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1ProcurementCompanyCuiDirectPurchasesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1ProcurementCompanyCuiDirectPurchasesResponse' from JSON`,
  );
}
