/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4b0e5506f512
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationActsIdVersionsVersionRequest = {
  id: string;
  version: string;
};

export const GetV1LegislationActsIdVersionsVersionStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationActsIdVersionsVersionStatus = OpenEnum<
  typeof GetV1LegislationActsIdVersionsVersionStatus
>;

export type GetV1LegislationActsIdVersionsVersionAmendingAct = {
  id: string | null;
  status: GetV1LegislationActsIdVersionsVersionStatus;
  reason: string | null;
  reference: string | null;
};

export const GetV1LegislationActsIdVersionsVersionKind = {
  Title: "title",
  Book: "book",
  Part: "part",
  Chapter: "chapter",
  Section: "section",
  Article: "article",
  Paragraph: "paragraph",
  Annex: "annex",
} as const;
export type GetV1LegislationActsIdVersionsVersionKind = OpenEnum<
  typeof GetV1LegislationActsIdVersionsVersionKind
>;

export type GetV1LegislationActsIdVersionsVersionBody = {
  id: string;
  kind: GetV1LegislationActsIdVersionsVersionKind;
  label: string;
  heading: string | null;
  text: string | null;
  children: Array<any>;
};

export const GetV1LegislationActsIdVersionsVersionSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationActsIdVersionsVersionSourceKind = OpenEnum<
  typeof GetV1LegislationActsIdVersionsVersionSourceKind
>;

export type GetV1LegislationActsIdVersionsVersionData = {
  version: string;
  effectiveOn: string;
  amendingAct: GetV1LegislationActsIdVersionsVersionAmendingAct;
  sourceDocumentId: string;
  contentHash: string;
  body: Array<GetV1LegislationActsIdVersionsVersionBody>;
  bodyText: string;
  sourceUrl: string;
  sourceKind: GetV1LegislationActsIdVersionsVersionSourceKind;
  documentVersion: string;
  retrievedAt: Date;
  coverageNote: string | null;
};

/**
 * Success
 */
export type GetV1LegislationActsIdVersionsVersionResponseBody = {
  data: GetV1LegislationActsIdVersionsVersionData;
};

export type GetV1LegislationActsIdVersionsVersionResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationActsIdVersionsVersionResponseBody;
};

/** @internal */
export type GetV1LegislationActsIdVersionsVersionRequest$Outbound = {
  id: string;
  version: string;
};

/** @internal */
export const GetV1LegislationActsIdVersionsVersionRequest$outboundSchema:
  z.ZodMiniType<
    GetV1LegislationActsIdVersionsVersionRequest$Outbound,
    GetV1LegislationActsIdVersionsVersionRequest
  > = z.object({
    id: z.string(),
    version: z.string(),
  });

export function getV1LegislationActsIdVersionsVersionRequestToJSON(
  getV1LegislationActsIdVersionsVersionRequest:
    GetV1LegislationActsIdVersionsVersionRequest,
): string {
  return JSON.stringify(
    GetV1LegislationActsIdVersionsVersionRequest$outboundSchema.parse(
      getV1LegislationActsIdVersionsVersionRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsVersionStatus$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionStatus, unknown> =
    openEnums.inboundSchema(GetV1LegislationActsIdVersionsVersionStatus);

/** @internal */
export const GetV1LegislationActsIdVersionsVersionAmendingAct$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionAmendingAct, unknown> = z
    .object({
      id: types.nullable(types.string()),
      status: GetV1LegislationActsIdVersionsVersionStatus$inboundSchema,
      reason: types.nullable(types.string()),
      reference: types.nullable(types.string()),
    });

export function getV1LegislationActsIdVersionsVersionAmendingActFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsVersionAmendingAct,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsVersionAmendingAct$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsVersionAmendingAct' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsVersionKind$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionKind, unknown> = openEnums
    .inboundSchema(GetV1LegislationActsIdVersionsVersionKind);

/** @internal */
export const GetV1LegislationActsIdVersionsVersionBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionBody, unknown> = z.object({
    id: types.string(),
    kind: GetV1LegislationActsIdVersionsVersionKind$inboundSchema,
    label: types.string(),
    heading: types.nullable(types.string()),
    text: types.nullable(types.string()),
    children: z.array(z.any()),
  });

export function getV1LegislationActsIdVersionsVersionBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsVersionBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsVersionBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsVersionBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsVersionSourceKind$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionSourceKind, unknown> =
    openEnums.inboundSchema(GetV1LegislationActsIdVersionsVersionSourceKind);

/** @internal */
export const GetV1LegislationActsIdVersionsVersionData$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionData, unknown> = z.pipe(
    z.object({
      version: types.string(),
      effective_on: types.string(),
      amending_act: z.lazy(() =>
        GetV1LegislationActsIdVersionsVersionAmendingAct$inboundSchema
      ),
      source_document_id: types.string(),
      content_hash: types.string(),
      body: z.array(z.lazy(() =>
        GetV1LegislationActsIdVersionsVersionBody$inboundSchema
      )),
      body_text: types.string(),
      source_url: types.string(),
      source_kind:
        GetV1LegislationActsIdVersionsVersionSourceKind$inboundSchema,
      document_version: types.string(),
      retrieved_at: types.date(),
      coverage_note: types.nullable(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "effective_on": "effectiveOn",
        "amending_act": "amendingAct",
        "source_document_id": "sourceDocumentId",
        "content_hash": "contentHash",
        "body_text": "bodyText",
        "source_url": "sourceUrl",
        "source_kind": "sourceKind",
        "document_version": "documentVersion",
        "retrieved_at": "retrievedAt",
        "coverage_note": "coverageNote",
      });
    }),
  );

export function getV1LegislationActsIdVersionsVersionDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsVersionData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsVersionData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsVersionData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsVersionResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionResponseBody, unknown> = z
    .object({
      data: z.lazy(() =>
        GetV1LegislationActsIdVersionsVersionData$inboundSchema
      ),
    });

export function getV1LegislationActsIdVersionsVersionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsVersionResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsVersionResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsVersionResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationActsIdVersionsVersionResponse$inboundSchema:
  z.ZodMiniType<GetV1LegislationActsIdVersionsVersionResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetV1LegislationActsIdVersionsVersionResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getV1LegislationActsIdVersionsVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationActsIdVersionsVersionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationActsIdVersionsVersionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationActsIdVersionsVersionResponse' from JSON`,
  );
}
