/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1667e869e66c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationMonitorulOficialIssuesRequest = {
  part?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
  updatedSince?: Date | undefined;
  cursor?: string | undefined;
  limit?: number | undefined;
};

export const GetV1LegislationMonitorulOficialIssuesStatus = {
  Resolved: "resolved",
  Unresolved: "unresolved",
} as const;
export type GetV1LegislationMonitorulOficialIssuesStatus = OpenEnum<
  typeof GetV1LegislationMonitorulOficialIssuesStatus
>;

export type ActId = {
  id: string | null;
  status: GetV1LegislationMonitorulOficialIssuesStatus;
  reason: string | null;
};

export type Act = {
  actId: ActId;
  title: string;
  type: string;
};

export type GetV1LegislationMonitorulOficialIssuesItem = {
  id: string;
  part: number;
  number: string;
  issuedOn: string;
  acts: Array<Act>;
  sourceUrl: string;
  sourceKind: "derived";
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string;
};

export type GetV1LegislationMonitorulOficialIssuesData = {
  items: Array<GetV1LegislationMonitorulOficialIssuesItem>;
  nextCursor: string | null;
};

/**
 * Success
 */
export type GetV1LegislationMonitorulOficialIssuesResponseBody = {
  data: GetV1LegislationMonitorulOficialIssuesData;
};

export type GetV1LegislationMonitorulOficialIssuesResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationMonitorulOficialIssuesResponseBody;
};

/** @internal */
export type GetV1LegislationMonitorulOficialIssuesRequest$Outbound = {
  part?: number | undefined;
  from?: string | undefined;
  to?: string | undefined;
  updated_since?: string | undefined;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const GetV1LegislationMonitorulOficialIssuesRequest$outboundSchema:
  z.ZodMiniType<
    GetV1LegislationMonitorulOficialIssuesRequest$Outbound,
    GetV1LegislationMonitorulOficialIssuesRequest
  > = z.pipe(
    z.object({
      part: z.optional(z.int()),
      from: z.optional(z.string()),
      to: z.optional(z.string()),
      updatedSince: z.optional(
        z.pipe(z.date(), z.transform(v => v.toISOString())),
      ),
      cursor: z.optional(z.string()),
      limit: z._default(z.int(), 50),
    }),
    z.transform((v) => {
      return remap$(v, {
        updatedSince: "updated_since",
      });
    }),
  );

export function getV1LegislationMonitorulOficialIssuesRequestToJSON(
  getV1LegislationMonitorulOficialIssuesRequest:
    GetV1LegislationMonitorulOficialIssuesRequest,
): string {
  return JSON.stringify(
    GetV1LegislationMonitorulOficialIssuesRequest$outboundSchema.parse(
      getV1LegislationMonitorulOficialIssuesRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialIssuesStatus$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialIssuesStatus, unknown> =
    openEnums.inboundSchema(GetV1LegislationMonitorulOficialIssuesStatus);

/** @internal */
export const ActId$inboundSchema: z.ZodMiniType<ActId, unknown> = z.object({
  id: types.nullable(types.string()),
  status: GetV1LegislationMonitorulOficialIssuesStatus$inboundSchema,
  reason: types.nullable(types.string()),
});

export function actIdFromJSON(
  jsonString: string,
): SafeParseResult<ActId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActId' from JSON`,
  );
}

/** @internal */
export const Act$inboundSchema: z.ZodMiniType<Act, unknown> = z.pipe(
  z.object({
    act_id: z.lazy(() => ActId$inboundSchema),
    title: types.string(),
    type: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "act_id": "actId",
    });
  }),
);

export function actFromJSON(
  jsonString: string,
): SafeParseResult<Act, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Act$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Act' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialIssuesItem$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialIssuesItem, unknown> = z.pipe(
    z.object({
      id: types.string(),
      part: types.number(),
      number: types.string(),
      issued_on: types.string(),
      acts: z.array(z.lazy(() => Act$inboundSchema)),
      source_url: types.string(),
      source_kind: types.literal("derived"),
      document_version: types.string(),
      retrieved_at: types.date(),
      content_hash: types.string(),
      coverage_note: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "issued_on": "issuedOn",
        "source_url": "sourceUrl",
        "source_kind": "sourceKind",
        "document_version": "documentVersion",
        "retrieved_at": "retrievedAt",
        "content_hash": "contentHash",
        "coverage_note": "coverageNote",
      });
    }),
  );

export function getV1LegislationMonitorulOficialIssuesItemFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialIssuesItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialIssuesItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialIssuesItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialIssuesData$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialIssuesData, unknown> = z.pipe(
    z.object({
      items: z.array(z.lazy(() =>
        GetV1LegislationMonitorulOficialIssuesItem$inboundSchema
      )),
      next_cursor: types.nullable(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "next_cursor": "nextCursor",
      });
    }),
  );

export function getV1LegislationMonitorulOficialIssuesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialIssuesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialIssuesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialIssuesData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialIssuesResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialIssuesResponseBody, unknown> = z
    .object({
      data: z.lazy(() =>
        GetV1LegislationMonitorulOficialIssuesData$inboundSchema
      ),
    });

export function getV1LegislationMonitorulOficialIssuesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialIssuesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialIssuesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialIssuesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationMonitorulOficialIssuesResponse$inboundSchema:
  z.ZodMiniType<GetV1LegislationMonitorulOficialIssuesResponse, unknown> = z
    .pipe(
      z.object({
        Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
        Result: z.lazy(() =>
          GetV1LegislationMonitorulOficialIssuesResponseBody$inboundSchema
        ),
      }),
      z.transform((v) => {
        return remap$(v, {
          "Headers": "headers",
          "Result": "result",
        });
      }),
    );

export function getV1LegislationMonitorulOficialIssuesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationMonitorulOficialIssuesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationMonitorulOficialIssuesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationMonitorulOficialIssuesResponse' from JSON`,
  );
}
