/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 704133c9eda1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1FxConvertRequest = {
  from: string;
  to: string;
  amount: number;
};

export const GetV1FxConvertSource = {
  Bnr: "BNR",
  Ecb: "ECB",
} as const;
export type GetV1FxConvertSource = OpenEnum<typeof GetV1FxConvertSource>;

export type GetV1FxConvertData = {
  from: string;
  to: string;
  amount: number;
  result: number;
  rate: number;
  date: string;
  source: GetV1FxConvertSource;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1FxConvertResponseBody = {
  data: GetV1FxConvertData;
};

export type GetV1FxConvertResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1FxConvertResponseBody;
};

/** @internal */
export type GetV1FxConvertRequest$Outbound = {
  from: string;
  to: string;
  amount: number;
};

/** @internal */
export const GetV1FxConvertRequest$outboundSchema: z.ZodMiniType<
  GetV1FxConvertRequest$Outbound,
  GetV1FxConvertRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  amount: z.number(),
});

export function getV1FxConvertRequestToJSON(
  getV1FxConvertRequest: GetV1FxConvertRequest,
): string {
  return JSON.stringify(
    GetV1FxConvertRequest$outboundSchema.parse(getV1FxConvertRequest),
  );
}

/** @internal */
export const GetV1FxConvertSource$inboundSchema: z.ZodMiniType<
  GetV1FxConvertSource,
  unknown
> = openEnums.inboundSchema(GetV1FxConvertSource);

/** @internal */
export const GetV1FxConvertData$inboundSchema: z.ZodMiniType<
  GetV1FxConvertData,
  unknown
> = z.object({
  from: types.string(),
  to: types.string(),
  amount: types.number(),
  result: types.number(),
  rate: types.number(),
  date: types.string(),
  source: GetV1FxConvertSource$inboundSchema,
  checkedAt: types.date(),
});

export function getV1FxConvertDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1FxConvertData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1FxConvertData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1FxConvertData' from JSON`,
  );
}

/** @internal */
export const GetV1FxConvertResponseBody$inboundSchema: z.ZodMiniType<
  GetV1FxConvertResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1FxConvertData$inboundSchema),
});

export function getV1FxConvertResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1FxConvertResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1FxConvertResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1FxConvertResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1FxConvertResponse$inboundSchema: z.ZodMiniType<
  GetV1FxConvertResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1FxConvertResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1FxConvertResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1FxConvertResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1FxConvertResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1FxConvertResponse' from JSON`,
  );
}
