/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 677f94a5b214
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1EfacturaInvoicesIdZipRequest = {
  id: string;
  downloadId: string;
  expires: string;
  sig: string;
};

export type GetV1EfacturaInvoicesIdZipResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export type GetV1EfacturaInvoicesIdZipRequest$Outbound = {
  id: string;
  download_id: string;
  expires: string;
  sig: string;
};

/** @internal */
export const GetV1EfacturaInvoicesIdZipRequest$outboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdZipRequest$Outbound,
  GetV1EfacturaInvoicesIdZipRequest
> = z.pipe(
  z.object({
    id: z.string(),
    downloadId: z.string(),
    expires: z.string(),
    sig: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      downloadId: "download_id",
    });
  }),
);

export function getV1EfacturaInvoicesIdZipRequestToJSON(
  getV1EfacturaInvoicesIdZipRequest: GetV1EfacturaInvoicesIdZipRequest,
): string {
  return JSON.stringify(
    GetV1EfacturaInvoicesIdZipRequest$outboundSchema.parse(
      getV1EfacturaInvoicesIdZipRequest,
    ),
  );
}

/** @internal */
export const GetV1EfacturaInvoicesIdZipResponse$inboundSchema: z.ZodMiniType<
  GetV1EfacturaInvoicesIdZipResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.custom<ReadableStream<Uint8Array>>(x =>
      x instanceof ReadableStream
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1EfacturaInvoicesIdZipResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1EfacturaInvoicesIdZipResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EfacturaInvoicesIdZipResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1EfacturaInvoicesIdZipResponse' from JSON`,
  );
}
