/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e7cae2f9da33
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Tier = {
  code: string;
  nameRo: string;
  nameEn: string;
  rateLimitPerMin: number;
  includedConnections: number;
};

export const Scope = {
  CompanyRead: "company:read",
  SearchRead: "search:read",
  ConnectionsRead: "connections:read",
  ConnectionsWrite: "connections:write",
  EfacturaSend: "efactura:send",
  EfacturaRead: "efactura:read",
  EfacturaValidate: "efactura:validate",
  EtransportSend: "etransport:send",
  EtransportRead: "etransport:read",
  RegesWrite: "reges:write",
  RegesRead: "reges:read",
  SpvRead: "spv:read",
  BankRead: "bank:read",
  ProcurementRead: "procurement:read",
  LegislationRead: "legislation:read",
  JusticeRead: "justice:read",
} as const;
export type Scope = OpenEnum<typeof Scope>;

export type Limits = {
  rateLimitPerMin: number;
};

export type AuthenticationMcpOauth = {
  method: "mcp_oauth";
};

export type AuthenticationDpop = {
  method: "dpop";
  keyId: string;
  credentialId: string;
  generation: number;
  publicKeyThumbprint: string;
};

export type AuthenticationAPIKey = {
  method: "api_key";
  keyId: string;
};

export type Authentication =
  | AuthenticationAPIKey
  | AuthenticationDpop
  | AuthenticationMcpOauth
  | discriminatedUnionTypes.Unknown<"method">;

export type GetV1MeData = {
  businessId: string;
  businessName: string;
  tier: Tier;
  scopes: Array<Scope>;
  limits: Limits;
  authentication:
    | AuthenticationAPIKey
    | AuthenticationDpop
    | AuthenticationMcpOauth
    | discriminatedUnionTypes.Unknown<"method">;
};

/**
 * Success
 */
export type GetV1MeResponseBody = {
  data: GetV1MeData;
};

export type GetV1MeResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1MeResponseBody;
};

/** @internal */
export const Tier$inboundSchema: z.ZodMiniType<Tier, unknown> = z.object({
  code: types.string(),
  nameRo: types.string(),
  nameEn: types.string(),
  rateLimitPerMin: types.number(),
  includedConnections: types.number(),
});

export function tierFromJSON(
  jsonString: string,
): SafeParseResult<Tier, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tier$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tier' from JSON`,
  );
}

/** @internal */
export const Scope$inboundSchema: z.ZodMiniType<Scope, unknown> = openEnums
  .inboundSchema(Scope);

/** @internal */
export const Limits$inboundSchema: z.ZodMiniType<Limits, unknown> = z.object({
  rateLimitPerMin: types.number(),
});

export function limitsFromJSON(
  jsonString: string,
): SafeParseResult<Limits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Limits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Limits' from JSON`,
  );
}

/** @internal */
export const AuthenticationMcpOauth$inboundSchema: z.ZodMiniType<
  AuthenticationMcpOauth,
  unknown
> = z.object({
  method: types.literal("mcp_oauth"),
});

export function authenticationMcpOauthFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticationMcpOauth, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticationMcpOauth$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticationMcpOauth' from JSON`,
  );
}

/** @internal */
export const AuthenticationDpop$inboundSchema: z.ZodMiniType<
  AuthenticationDpop,
  unknown
> = z.object({
  method: types.literal("dpop"),
  keyId: types.string(),
  credentialId: types.string(),
  generation: types.number(),
  publicKeyThumbprint: types.string(),
});

export function authenticationDpopFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticationDpop, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticationDpop$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticationDpop' from JSON`,
  );
}

/** @internal */
export const AuthenticationAPIKey$inboundSchema: z.ZodMiniType<
  AuthenticationAPIKey,
  unknown
> = z.object({
  method: types.literal("api_key"),
  keyId: types.string(),
});

export function authenticationAPIKeyFromJSON(
  jsonString: string,
): SafeParseResult<AuthenticationAPIKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthenticationAPIKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthenticationAPIKey' from JSON`,
  );
}

/** @internal */
export const Authentication$inboundSchema: z.ZodMiniType<
  Authentication,
  unknown
> = discriminatedUnion("method", {
  api_key: z.lazy(() => AuthenticationAPIKey$inboundSchema),
  dpop: z.lazy(() => AuthenticationDpop$inboundSchema),
  mcp_oauth: z.lazy(() => AuthenticationMcpOauth$inboundSchema),
});

export function authenticationFromJSON(
  jsonString: string,
): SafeParseResult<Authentication, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Authentication$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Authentication' from JSON`,
  );
}

/** @internal */
export const GetV1MeData$inboundSchema: z.ZodMiniType<GetV1MeData, unknown> = z
  .object({
    businessId: types.string(),
    businessName: types.string(),
    tier: z.lazy(() => Tier$inboundSchema),
    scopes: z.array(Scope$inboundSchema),
    limits: z.lazy(() => Limits$inboundSchema),
    authentication: discriminatedUnion("method", {
      api_key: z.lazy(() => AuthenticationAPIKey$inboundSchema),
      dpop: z.lazy(() => AuthenticationDpop$inboundSchema),
      mcp_oauth: z.lazy(() => AuthenticationMcpOauth$inboundSchema),
    }),
  });

export function getV1MeDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MeData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MeData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MeData' from JSON`,
  );
}

/** @internal */
export const GetV1MeResponseBody$inboundSchema: z.ZodMiniType<
  GetV1MeResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1MeData$inboundSchema),
});

export function getV1MeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MeResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1MeResponse$inboundSchema: z.ZodMiniType<
  GetV1MeResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1MeResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1MeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MeResponse' from JSON`,
  );
}
