/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: acd8ba3cd7cc
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1CompanyCuiRequest = {
  cui: string;
};

export type GetV1CompanyCuiAddress = {
  street?: string | undefined;
  city?: string | undefined;
  county?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
};

export type GetV1CompanyCuiVat = {
  vatActive: boolean;
  vatOnPayment: boolean;
  vatNumber: string | null;
};

export const GetV1CompanyCuiSource = {
  Anaf: "anaf",
  Demoanaf: "demoanaf",
  Synthetic: "synthetic",
} as const;
export type GetV1CompanyCuiSource = OpenEnum<typeof GetV1CompanyCuiSource>;

export type GetV1CompanyCuiData = {
  cui: string;
  name: string;
  registrationNumber: string | null;
  address: GetV1CompanyCuiAddress | null;
  vat: GetV1CompanyCuiVat;
  active: boolean;
  checkedAt: Date;
  source?: GetV1CompanyCuiSource | undefined;
};

/**
 * Success
 */
export type GetV1CompanyCuiResponseBody = {
  data: GetV1CompanyCuiData;
};

export type GetV1CompanyCuiResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1CompanyCuiResponseBody;
};

/** @internal */
export type GetV1CompanyCuiRequest$Outbound = {
  cui: string;
};

/** @internal */
export const GetV1CompanyCuiRequest$outboundSchema: z.ZodMiniType<
  GetV1CompanyCuiRequest$Outbound,
  GetV1CompanyCuiRequest
> = z.object({
  cui: z.string(),
});

export function getV1CompanyCuiRequestToJSON(
  getV1CompanyCuiRequest: GetV1CompanyCuiRequest,
): string {
  return JSON.stringify(
    GetV1CompanyCuiRequest$outboundSchema.parse(getV1CompanyCuiRequest),
  );
}

/** @internal */
export const GetV1CompanyCuiAddress$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiAddress,
  unknown
> = z.object({
  street: types.optional(types.string()),
  city: types.optional(types.string()),
  county: types.optional(types.string()),
  postalCode: types.optional(types.string()),
  country: types.optional(types.string()),
});

export function getV1CompanyCuiAddressFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiAddress' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiVat$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiVat,
  unknown
> = z.object({
  vatActive: types.boolean(),
  vatOnPayment: types.boolean(),
  vatNumber: types.nullable(types.string()),
});

export function getV1CompanyCuiVatFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiVat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiVat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiVat' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiSource$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiSource,
  unknown
> = openEnums.inboundSchema(GetV1CompanyCuiSource);

/** @internal */
export const GetV1CompanyCuiData$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiData,
  unknown
> = z.object({
  cui: types.string(),
  name: types.string(),
  registrationNumber: types.nullable(types.string()),
  address: types.nullable(z.lazy(() => GetV1CompanyCuiAddress$inboundSchema)),
  vat: z.lazy(() => GetV1CompanyCuiVat$inboundSchema),
  active: types.boolean(),
  checkedAt: types.date(),
  source: types.optional(GetV1CompanyCuiSource$inboundSchema),
});

export function getV1CompanyCuiDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiData' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiResponseBody$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1CompanyCuiData$inboundSchema),
});

export function getV1CompanyCuiResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiResponse$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1CompanyCuiResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1CompanyCuiResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiResponse' from JSON`,
  );
}
