/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ca067c051951
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1LegislationBillsIdDocumentsRequest = {
  id: string;
};

export const GetV1LegislationBillsIdDocumentsKind = {
  BillText: "bill_text",
  Expose: "expose",
  CommitteeReport: "committee_report",
  Opinion: "opinion",
  Amendment: "amendment",
  AdoptedForm: "adopted_form",
  Other: "other",
} as const;
export type GetV1LegislationBillsIdDocumentsKind = OpenEnum<
  typeof GetV1LegislationBillsIdDocumentsKind
>;

export const GetV1LegislationBillsIdDocumentsSourceKind = {
  Cdep: "cdep",
  Senat: "senat",
  PortalLegislativ: "portal_legislativ",
  Derived: "derived",
} as const;
export type GetV1LegislationBillsIdDocumentsSourceKind = OpenEnum<
  typeof GetV1LegislationBillsIdDocumentsSourceKind
>;

export type GetV1LegislationBillsIdDocumentsItem = {
  id: string;
  kind: GetV1LegislationBillsIdDocumentsKind;
  label: string;
  fileUrl: string;
  fileSha256: string | null;
  bodyText: string | null;
  sourceUrl: string;
  sourceKind: GetV1LegislationBillsIdDocumentsSourceKind;
  documentVersion: string;
  retrievedAt: Date;
  contentHash: string;
  coverageNote: string | null;
};

export type GetV1LegislationBillsIdDocumentsData = {
  items: Array<GetV1LegislationBillsIdDocumentsItem>;
};

/**
 * Success
 */
export type GetV1LegislationBillsIdDocumentsResponseBody = {
  data: GetV1LegislationBillsIdDocumentsData;
};

export type GetV1LegislationBillsIdDocumentsResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1LegislationBillsIdDocumentsResponseBody;
};

/** @internal */
export type GetV1LegislationBillsIdDocumentsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1LegislationBillsIdDocumentsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1LegislationBillsIdDocumentsRequest$Outbound,
    GetV1LegislationBillsIdDocumentsRequest
  > = z.object({
    id: z.string(),
  });

export function getV1LegislationBillsIdDocumentsRequestToJSON(
  getV1LegislationBillsIdDocumentsRequest:
    GetV1LegislationBillsIdDocumentsRequest,
): string {
  return JSON.stringify(
    GetV1LegislationBillsIdDocumentsRequest$outboundSchema.parse(
      getV1LegislationBillsIdDocumentsRequest,
    ),
  );
}

/** @internal */
export const GetV1LegislationBillsIdDocumentsKind$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdDocumentsKind,
  unknown
> = openEnums.inboundSchema(GetV1LegislationBillsIdDocumentsKind);

/** @internal */
export const GetV1LegislationBillsIdDocumentsSourceKind$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsIdDocumentsSourceKind, unknown> = openEnums
    .inboundSchema(GetV1LegislationBillsIdDocumentsSourceKind);

/** @internal */
export const GetV1LegislationBillsIdDocumentsItem$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdDocumentsItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    kind: GetV1LegislationBillsIdDocumentsKind$inboundSchema,
    label: types.string(),
    file_url: types.string(),
    file_sha256: types.nullable(types.string()),
    body_text: types.nullable(types.string()),
    source_url: types.string(),
    source_kind: GetV1LegislationBillsIdDocumentsSourceKind$inboundSchema,
    document_version: types.string(),
    retrieved_at: types.date(),
    content_hash: types.string(),
    coverage_note: types.nullable(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "file_url": "fileUrl",
      "file_sha256": "fileSha256",
      "body_text": "bodyText",
      "source_url": "sourceUrl",
      "source_kind": "sourceKind",
      "document_version": "documentVersion",
      "retrieved_at": "retrievedAt",
      "content_hash": "contentHash",
      "coverage_note": "coverageNote",
    });
  }),
);

export function getV1LegislationBillsIdDocumentsItemFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdDocumentsItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdDocumentsItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdDocumentsItem' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdDocumentsData$inboundSchema: z.ZodMiniType<
  GetV1LegislationBillsIdDocumentsData,
  unknown
> = z.object({
  items: z.array(
    z.lazy(() => GetV1LegislationBillsIdDocumentsItem$inboundSchema),
  ),
});

export function getV1LegislationBillsIdDocumentsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1LegislationBillsIdDocumentsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdDocumentsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1LegislationBillsIdDocumentsData' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdDocumentsResponseBody$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsIdDocumentsResponseBody, unknown> = z
    .object({
      data: z.lazy(() => GetV1LegislationBillsIdDocumentsData$inboundSchema),
    });

export function getV1LegislationBillsIdDocumentsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationBillsIdDocumentsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdDocumentsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationBillsIdDocumentsResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1LegislationBillsIdDocumentsResponse$inboundSchema:
  z.ZodMiniType<GetV1LegislationBillsIdDocumentsResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        GetV1LegislationBillsIdDocumentsResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function getV1LegislationBillsIdDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1LegislationBillsIdDocumentsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1LegislationBillsIdDocumentsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1LegislationBillsIdDocumentsResponse' from JSON`,
  );
}
