/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d922f534edfb
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1CompanyCuiBalanceYearRequest = {
  cui: string;
  year: string;
};

export type GetV1CompanyCuiBalanceYearLine = {
  indicator: string;
  value: number;
};

export type GetV1CompanyCuiBalanceYearData = {
  cui: string;
  year: number;
  available: boolean;
  lines: Array<GetV1CompanyCuiBalanceYearLine>;
  checkedAt: Date;
};

/**
 * Success
 */
export type GetV1CompanyCuiBalanceYearResponseBody = {
  data: GetV1CompanyCuiBalanceYearData;
};

export type GetV1CompanyCuiBalanceYearResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1CompanyCuiBalanceYearResponseBody;
};

/** @internal */
export type GetV1CompanyCuiBalanceYearRequest$Outbound = {
  cui: string;
  year: string;
};

/** @internal */
export const GetV1CompanyCuiBalanceYearRequest$outboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceYearRequest$Outbound,
  GetV1CompanyCuiBalanceYearRequest
> = z.object({
  cui: z.string(),
  year: z.string(),
});

export function getV1CompanyCuiBalanceYearRequestToJSON(
  getV1CompanyCuiBalanceYearRequest: GetV1CompanyCuiBalanceYearRequest,
): string {
  return JSON.stringify(
    GetV1CompanyCuiBalanceYearRequest$outboundSchema.parse(
      getV1CompanyCuiBalanceYearRequest,
    ),
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceYearLine$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceYearLine,
  unknown
> = z.object({
  indicator: types.string(),
  value: types.number(),
});

export function getV1CompanyCuiBalanceYearLineFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceYearLine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiBalanceYearLine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceYearLine' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceYearData$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceYearData,
  unknown
> = z.object({
  cui: types.string(),
  year: types.number(),
  available: types.boolean(),
  lines: z.array(z.lazy(() => GetV1CompanyCuiBalanceYearLine$inboundSchema)),
  checkedAt: types.date(),
});

export function getV1CompanyCuiBalanceYearDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceYearData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1CompanyCuiBalanceYearData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceYearData' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceYearResponseBody$inboundSchema:
  z.ZodMiniType<GetV1CompanyCuiBalanceYearResponseBody, unknown> = z.object({
    data: z.lazy(() => GetV1CompanyCuiBalanceYearData$inboundSchema),
  });

export function getV1CompanyCuiBalanceYearResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceYearResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1CompanyCuiBalanceYearResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceYearResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1CompanyCuiBalanceYearResponse$inboundSchema: z.ZodMiniType<
  GetV1CompanyCuiBalanceYearResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1CompanyCuiBalanceYearResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1CompanyCuiBalanceYearResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1CompanyCuiBalanceYearResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1CompanyCuiBalanceYearResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1CompanyCuiBalanceYearResponse' from JSON`,
  );
}
