/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ad78b1ce97f0
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetV1ConnectionsIdRequest = {
  id: string;
};

export const GetV1ConnectionsIdService = {
  Efactura: "efactura",
  Etransport: "etransport",
  Reges: "reges",
  Spv: "spv",
  Bank: "bank",
} as const;
export type GetV1ConnectionsIdService = OpenEnum<
  typeof GetV1ConnectionsIdService
>;

export const GetV1ConnectionsIdStatus = {
  Pending: "pending",
  Active: "active",
  Error: "error",
  Revoked: "revoked",
} as const;
export type GetV1ConnectionsIdStatus = OpenEnum<
  typeof GetV1ConnectionsIdStatus
>;

export type GetV1ConnectionsIdData = {
  id: string;
  cui: string;
  service: GetV1ConnectionsIdService;
  status: GetV1ConnectionsIdStatus;
  expiresAt: Date | null;
  lastRefreshedAt: Date | null;
  createdAt: Date;
};

/**
 * Success
 */
export type GetV1ConnectionsIdResponseBody = {
  data: GetV1ConnectionsIdData;
};

export type GetV1ConnectionsIdResponse = {
  headers: { [k: string]: Array<string> };
  result: GetV1ConnectionsIdResponseBody;
};

/** @internal */
export type GetV1ConnectionsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetV1ConnectionsIdRequest$outboundSchema: z.ZodMiniType<
  GetV1ConnectionsIdRequest$Outbound,
  GetV1ConnectionsIdRequest
> = z.object({
  id: z.string(),
});

export function getV1ConnectionsIdRequestToJSON(
  getV1ConnectionsIdRequest: GetV1ConnectionsIdRequest,
): string {
  return JSON.stringify(
    GetV1ConnectionsIdRequest$outboundSchema.parse(getV1ConnectionsIdRequest),
  );
}

/** @internal */
export const GetV1ConnectionsIdService$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsIdService,
  unknown
> = openEnums.inboundSchema(GetV1ConnectionsIdService);

/** @internal */
export const GetV1ConnectionsIdStatus$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsIdStatus,
  unknown
> = openEnums.inboundSchema(GetV1ConnectionsIdStatus);

/** @internal */
export const GetV1ConnectionsIdData$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsIdData,
  unknown
> = z.object({
  id: types.string(),
  cui: types.string(),
  service: GetV1ConnectionsIdService$inboundSchema,
  status: GetV1ConnectionsIdStatus$inboundSchema,
  expiresAt: types.nullable(types.date()),
  lastRefreshedAt: types.nullable(types.date()),
  createdAt: types.date(),
});

export function getV1ConnectionsIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConnectionsIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConnectionsIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConnectionsIdData' from JSON`,
  );
}

/** @internal */
export const GetV1ConnectionsIdResponseBody$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsIdResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => GetV1ConnectionsIdData$inboundSchema),
});

export function getV1ConnectionsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConnectionsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConnectionsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConnectionsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetV1ConnectionsIdResponse$inboundSchema: z.ZodMiniType<
  GetV1ConnectionsIdResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => GetV1ConnectionsIdResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function getV1ConnectionsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1ConnectionsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1ConnectionsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1ConnectionsIdResponse' from JSON`,
  );
}
