/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ee68d58f158b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PatchV1EtransportDeclarationsUitRequestBody = {
  declaration: { [k: string]: any };
};

export type PatchV1EtransportDeclarationsUitRequest = {
  uit: string;
  body: PatchV1EtransportDeclarationsUitRequestBody;
};

export type PatchV1EtransportDeclarationsUitData = {
  id: string;
  uit: string;
  status: string;
  createdAt: Date;
};

/**
 * Success
 */
export type PatchV1EtransportDeclarationsUitResponseBody = {
  data: PatchV1EtransportDeclarationsUitData;
};

export type PatchV1EtransportDeclarationsUitResponse = {
  headers: { [k: string]: Array<string> };
  result: PatchV1EtransportDeclarationsUitResponseBody;
};

/** @internal */
export type PatchV1EtransportDeclarationsUitRequestBody$Outbound = {
  declaration: { [k: string]: any };
};

/** @internal */
export const PatchV1EtransportDeclarationsUitRequestBody$outboundSchema:
  z.ZodMiniType<
    PatchV1EtransportDeclarationsUitRequestBody$Outbound,
    PatchV1EtransportDeclarationsUitRequestBody
  > = z.object({
    declaration: z.record(z.string(), z.any()),
  });

export function patchV1EtransportDeclarationsUitRequestBodyToJSON(
  patchV1EtransportDeclarationsUitRequestBody:
    PatchV1EtransportDeclarationsUitRequestBody,
): string {
  return JSON.stringify(
    PatchV1EtransportDeclarationsUitRequestBody$outboundSchema.parse(
      patchV1EtransportDeclarationsUitRequestBody,
    ),
  );
}

/** @internal */
export type PatchV1EtransportDeclarationsUitRequest$Outbound = {
  uit: string;
  body: PatchV1EtransportDeclarationsUitRequestBody$Outbound;
};

/** @internal */
export const PatchV1EtransportDeclarationsUitRequest$outboundSchema:
  z.ZodMiniType<
    PatchV1EtransportDeclarationsUitRequest$Outbound,
    PatchV1EtransportDeclarationsUitRequest
  > = z.object({
    uit: z.string(),
    body: z.lazy(() =>
      PatchV1EtransportDeclarationsUitRequestBody$outboundSchema
    ),
  });

export function patchV1EtransportDeclarationsUitRequestToJSON(
  patchV1EtransportDeclarationsUitRequest:
    PatchV1EtransportDeclarationsUitRequest,
): string {
  return JSON.stringify(
    PatchV1EtransportDeclarationsUitRequest$outboundSchema.parse(
      patchV1EtransportDeclarationsUitRequest,
    ),
  );
}

/** @internal */
export const PatchV1EtransportDeclarationsUitData$inboundSchema: z.ZodMiniType<
  PatchV1EtransportDeclarationsUitData,
  unknown
> = z.object({
  id: types.string(),
  uit: types.string(),
  status: types.string(),
  createdAt: types.date(),
});

export function patchV1EtransportDeclarationsUitDataFromJSON(
  jsonString: string,
): SafeParseResult<PatchV1EtransportDeclarationsUitData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV1EtransportDeclarationsUitData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV1EtransportDeclarationsUitData' from JSON`,
  );
}

/** @internal */
export const PatchV1EtransportDeclarationsUitResponseBody$inboundSchema:
  z.ZodMiniType<PatchV1EtransportDeclarationsUitResponseBody, unknown> = z
    .object({
      data: z.lazy(() => PatchV1EtransportDeclarationsUitData$inboundSchema),
    });

export function patchV1EtransportDeclarationsUitResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV1EtransportDeclarationsUitResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV1EtransportDeclarationsUitResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV1EtransportDeclarationsUitResponseBody' from JSON`,
  );
}

/** @internal */
export const PatchV1EtransportDeclarationsUitResponse$inboundSchema:
  z.ZodMiniType<PatchV1EtransportDeclarationsUitResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PatchV1EtransportDeclarationsUitResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function patchV1EtransportDeclarationsUitResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV1EtransportDeclarationsUitResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV1EtransportDeclarationsUitResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV1EtransportDeclarationsUitResponse' from JSON`,
  );
}
