/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7832a1c396c7
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const OnlineEnum = {
  True: "true",
  False: "false",
} as const;
export type OnlineEnum = ClosedEnum<typeof OnlineEnum>;

export type PostV1EfacturaValidateRequestBody = {
  xml: string;
};

export type PostV1EfacturaValidateRequest = {
  online?: OnlineEnum | undefined;
  /**
   * Replays the first response for the same key, body and route (24h); a different body under the same key is a 409.
   */
  idempotencyKey?: string | undefined;
  body: PostV1EfacturaValidateRequestBody;
};

export const Severity3 = {
  Error: "error",
  Warning: "warning",
} as const;
export type Severity3 = OpenEnum<typeof Severity3>;

export type Finding3 = {
  severity: Severity3;
  code: string | null;
  message: string;
};

export const OnlineSeverity2 = {
  Error: "error",
  Warning: "warning",
} as const;
export type OnlineSeverity2 = OpenEnum<typeof OnlineSeverity2>;

export type OnlineFinding2 = {
  severity: OnlineSeverity2;
  code: string | null;
  message: string;
};

export type OnlineSkipped = {
  status: "skipped";
  traceId: any | null;
  findings: Array<OnlineFinding2>;
};

export const OnlineSeverity1 = {
  Error: "error",
  Warning: "warning",
} as const;
export type OnlineSeverity1 = OpenEnum<typeof OnlineSeverity1>;

export type OnlineFinding1 = {
  severity: OnlineSeverity1;
  code: string | null;
  message: string;
};

export type OnlineNok = {
  status: "nok";
  traceId: string;
  findings: Array<OnlineFinding1>;
};

export type Online =
  | OnlineNok
  | OnlineSkipped
  | discriminatedUnionTypes.Unknown<"status">;

export type PostV1EfacturaValidateData3 = {
  valid: false;
  findings: Array<Finding3>;
  online: OnlineNok | OnlineSkipped | discriminatedUnionTypes.Unknown<"status">;
};

export const Severity2 = {
  Error: "error",
  Warning: "warning",
} as const;
export type Severity2 = OpenEnum<typeof Severity2>;

export type Finding2 = {
  severity: Severity2;
  code: string | null;
  message: string;
};

export const SeverityOk = {
  Error: "error",
  Warning: "warning",
} as const;
export type SeverityOk = OpenEnum<typeof SeverityOk>;

export type FindingOk = {
  severity: SeverityOk;
  code: string | null;
  message: string;
};

export type OnlineOk = {
  status: "ok";
  traceId: string;
  findings: Array<FindingOk>;
};

export type PostV1EfacturaValidateData2 = {
  valid: true;
  findings: Array<Finding2>;
  online: OnlineOk;
};

export const Severity1 = {
  Error: "error",
  Warning: "warning",
} as const;
export type Severity1 = OpenEnum<typeof Severity1>;

export type Finding1 = {
  severity: Severity1;
  code: string | null;
  message: string;
};

export type PostV1EfacturaValidateData1 = {
  valid: boolean;
  findings: Array<Finding1>;
};

export type Data =
  | PostV1EfacturaValidateData2
  | PostV1EfacturaValidateData3
  | PostV1EfacturaValidateData1;

/**
 * Success
 */
export type PostV1EfacturaValidateResponseBody = {
  data:
    | PostV1EfacturaValidateData2
    | PostV1EfacturaValidateData3
    | PostV1EfacturaValidateData1;
};

export type PostV1EfacturaValidateResponse = {
  headers: { [k: string]: Array<string> };
  result: PostV1EfacturaValidateResponseBody;
};

/** @internal */
export const OnlineEnum$outboundSchema: z.ZodMiniEnum<typeof OnlineEnum> = z
  .enum(OnlineEnum);

/** @internal */
export type PostV1EfacturaValidateRequestBody$Outbound = {
  xml: string;
};

/** @internal */
export const PostV1EfacturaValidateRequestBody$outboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateRequestBody$Outbound,
  PostV1EfacturaValidateRequestBody
> = z.object({
  xml: z.string(),
});

export function postV1EfacturaValidateRequestBodyToJSON(
  postV1EfacturaValidateRequestBody: PostV1EfacturaValidateRequestBody,
): string {
  return JSON.stringify(
    PostV1EfacturaValidateRequestBody$outboundSchema.parse(
      postV1EfacturaValidateRequestBody,
    ),
  );
}

/** @internal */
export type PostV1EfacturaValidateRequest$Outbound = {
  online?: string | undefined;
  "Idempotency-Key"?: string | undefined;
  body: PostV1EfacturaValidateRequestBody$Outbound;
};

/** @internal */
export const PostV1EfacturaValidateRequest$outboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateRequest$Outbound,
  PostV1EfacturaValidateRequest
> = z.pipe(
  z.object({
    online: z.optional(OnlineEnum$outboundSchema),
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => PostV1EfacturaValidateRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function postV1EfacturaValidateRequestToJSON(
  postV1EfacturaValidateRequest: PostV1EfacturaValidateRequest,
): string {
  return JSON.stringify(
    PostV1EfacturaValidateRequest$outboundSchema.parse(
      postV1EfacturaValidateRequest,
    ),
  );
}

/** @internal */
export const Severity3$inboundSchema: z.ZodMiniType<Severity3, unknown> =
  openEnums.inboundSchema(Severity3);

/** @internal */
export const Finding3$inboundSchema: z.ZodMiniType<Finding3, unknown> = z
  .object({
    severity: Severity3$inboundSchema,
    code: types.nullable(types.string()),
    message: types.string(),
  });

export function finding3FromJSON(
  jsonString: string,
): SafeParseResult<Finding3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Finding3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Finding3' from JSON`,
  );
}

/** @internal */
export const OnlineSeverity2$inboundSchema: z.ZodMiniType<
  OnlineSeverity2,
  unknown
> = openEnums.inboundSchema(OnlineSeverity2);

/** @internal */
export const OnlineFinding2$inboundSchema: z.ZodMiniType<
  OnlineFinding2,
  unknown
> = z.object({
  severity: OnlineSeverity2$inboundSchema,
  code: types.nullable(types.string()),
  message: types.string(),
});

export function onlineFinding2FromJSON(
  jsonString: string,
): SafeParseResult<OnlineFinding2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OnlineFinding2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OnlineFinding2' from JSON`,
  );
}

/** @internal */
export const OnlineSkipped$inboundSchema: z.ZodMiniType<
  OnlineSkipped,
  unknown
> = z.object({
  status: types.literal("skipped"),
  traceId: types.nullable(z.any()),
  findings: z.array(z.lazy(() => OnlineFinding2$inboundSchema)),
});

export function onlineSkippedFromJSON(
  jsonString: string,
): SafeParseResult<OnlineSkipped, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OnlineSkipped$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OnlineSkipped' from JSON`,
  );
}

/** @internal */
export const OnlineSeverity1$inboundSchema: z.ZodMiniType<
  OnlineSeverity1,
  unknown
> = openEnums.inboundSchema(OnlineSeverity1);

/** @internal */
export const OnlineFinding1$inboundSchema: z.ZodMiniType<
  OnlineFinding1,
  unknown
> = z.object({
  severity: OnlineSeverity1$inboundSchema,
  code: types.nullable(types.string()),
  message: types.string(),
});

export function onlineFinding1FromJSON(
  jsonString: string,
): SafeParseResult<OnlineFinding1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OnlineFinding1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OnlineFinding1' from JSON`,
  );
}

/** @internal */
export const OnlineNok$inboundSchema: z.ZodMiniType<OnlineNok, unknown> = z
  .object({
    status: types.literal("nok"),
    traceId: types.string(),
    findings: z.array(z.lazy(() => OnlineFinding1$inboundSchema)),
  });

export function onlineNokFromJSON(
  jsonString: string,
): SafeParseResult<OnlineNok, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OnlineNok$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OnlineNok' from JSON`,
  );
}

/** @internal */
export const Online$inboundSchema: z.ZodMiniType<Online, unknown> =
  discriminatedUnion("status", {
    nok: z.lazy(() => OnlineNok$inboundSchema),
    skipped: z.lazy(() => OnlineSkipped$inboundSchema),
  });

export function onlineFromJSON(
  jsonString: string,
): SafeParseResult<Online, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Online$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Online' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaValidateData3$inboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateData3,
  unknown
> = z.object({
  valid: types.literal(false),
  findings: z.array(z.lazy(() => Finding3$inboundSchema)),
  online: discriminatedUnion("status", {
    nok: z.lazy(() => OnlineNok$inboundSchema),
    skipped: z.lazy(() => OnlineSkipped$inboundSchema),
  }),
});

export function postV1EfacturaValidateData3FromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaValidateData3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EfacturaValidateData3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaValidateData3' from JSON`,
  );
}

/** @internal */
export const Severity2$inboundSchema: z.ZodMiniType<Severity2, unknown> =
  openEnums.inboundSchema(Severity2);

/** @internal */
export const Finding2$inboundSchema: z.ZodMiniType<Finding2, unknown> = z
  .object({
    severity: Severity2$inboundSchema,
    code: types.nullable(types.string()),
    message: types.string(),
  });

export function finding2FromJSON(
  jsonString: string,
): SafeParseResult<Finding2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Finding2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Finding2' from JSON`,
  );
}

/** @internal */
export const SeverityOk$inboundSchema: z.ZodMiniType<SeverityOk, unknown> =
  openEnums.inboundSchema(SeverityOk);

/** @internal */
export const FindingOk$inboundSchema: z.ZodMiniType<FindingOk, unknown> = z
  .object({
    severity: SeverityOk$inboundSchema,
    code: types.nullable(types.string()),
    message: types.string(),
  });

export function findingOkFromJSON(
  jsonString: string,
): SafeParseResult<FindingOk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindingOk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindingOk' from JSON`,
  );
}

/** @internal */
export const OnlineOk$inboundSchema: z.ZodMiniType<OnlineOk, unknown> = z
  .object({
    status: types.literal("ok"),
    traceId: types.string(),
    findings: z.array(z.lazy(() => FindingOk$inboundSchema)),
  });

export function onlineOkFromJSON(
  jsonString: string,
): SafeParseResult<OnlineOk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OnlineOk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OnlineOk' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaValidateData2$inboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateData2,
  unknown
> = z.object({
  valid: types.literal(true),
  findings: z.array(z.lazy(() => Finding2$inboundSchema)),
  online: z.lazy(() => OnlineOk$inboundSchema),
});

export function postV1EfacturaValidateData2FromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaValidateData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EfacturaValidateData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaValidateData2' from JSON`,
  );
}

/** @internal */
export const Severity1$inboundSchema: z.ZodMiniType<Severity1, unknown> =
  openEnums.inboundSchema(Severity1);

/** @internal */
export const Finding1$inboundSchema: z.ZodMiniType<Finding1, unknown> = z
  .object({
    severity: Severity1$inboundSchema,
    code: types.nullable(types.string()),
    message: types.string(),
  });

export function finding1FromJSON(
  jsonString: string,
): SafeParseResult<Finding1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Finding1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Finding1' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaValidateData1$inboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateData1,
  unknown
> = z.object({
  valid: types.boolean(),
  findings: z.array(z.lazy(() => Finding1$inboundSchema)),
});

export function postV1EfacturaValidateData1FromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaValidateData1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EfacturaValidateData1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaValidateData1' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = smartUnion([
  z.lazy(() => PostV1EfacturaValidateData2$inboundSchema),
  z.lazy(() => PostV1EfacturaValidateData3$inboundSchema),
  z.lazy(() => PostV1EfacturaValidateData1$inboundSchema),
]);

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaValidateResponseBody$inboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateResponseBody,
  unknown
> = z.object({
  data: smartUnion([
    z.lazy(() => PostV1EfacturaValidateData2$inboundSchema),
    z.lazy(() => PostV1EfacturaValidateData3$inboundSchema),
    z.lazy(() => PostV1EfacturaValidateData1$inboundSchema),
  ]),
});

export function postV1EfacturaValidateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaValidateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1EfacturaValidateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaValidateResponseBody' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaValidateResponse$inboundSchema: z.ZodMiniType<
  PostV1EfacturaValidateResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => PostV1EfacturaValidateResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function postV1EfacturaValidateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaValidateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EfacturaValidateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaValidateResponse' from JSON`,
  );
}
