/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ea0793906fe8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1RegesContractsIdTerminateRequestBody = {
  termination: { [k: string]: any };
};

export type PostV1RegesContractsIdTerminateRequest = {
  id: string;
  /**
   * Replays the first response for the same key, body and route (24h); a different body under the same key is a 409.
   */
  idempotencyKey?: string | undefined;
  body: PostV1RegesContractsIdTerminateRequestBody;
};

export const PostV1RegesContractsIdTerminateStatus = {
  Queued: "queued",
  Processing: "processing",
  Done: "done",
  Error: "error",
  Unknown: "unknown",
} as const;
export type PostV1RegesContractsIdTerminateStatus = OpenEnum<
  typeof PostV1RegesContractsIdTerminateStatus
>;

export type PostV1RegesContractsIdTerminateData = {
  jobId: string;
  status: PostV1RegesContractsIdTerminateStatus;
};

/**
 * Success
 */
export type PostV1RegesContractsIdTerminateResponseBody = {
  data: PostV1RegesContractsIdTerminateData;
};

export type PostV1RegesContractsIdTerminateResponse = {
  headers: { [k: string]: Array<string> };
  result: PostV1RegesContractsIdTerminateResponseBody;
};

/** @internal */
export type PostV1RegesContractsIdTerminateRequestBody$Outbound = {
  termination: { [k: string]: any };
};

/** @internal */
export const PostV1RegesContractsIdTerminateRequestBody$outboundSchema:
  z.ZodMiniType<
    PostV1RegesContractsIdTerminateRequestBody$Outbound,
    PostV1RegesContractsIdTerminateRequestBody
  > = z.object({
    termination: z.record(z.string(), z.any()),
  });

export function postV1RegesContractsIdTerminateRequestBodyToJSON(
  postV1RegesContractsIdTerminateRequestBody:
    PostV1RegesContractsIdTerminateRequestBody,
): string {
  return JSON.stringify(
    PostV1RegesContractsIdTerminateRequestBody$outboundSchema.parse(
      postV1RegesContractsIdTerminateRequestBody,
    ),
  );
}

/** @internal */
export type PostV1RegesContractsIdTerminateRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: PostV1RegesContractsIdTerminateRequestBody$Outbound;
};

/** @internal */
export const PostV1RegesContractsIdTerminateRequest$outboundSchema:
  z.ZodMiniType<
    PostV1RegesContractsIdTerminateRequest$Outbound,
    PostV1RegesContractsIdTerminateRequest
  > = z.pipe(
    z.object({
      id: z.string(),
      idempotencyKey: z.optional(z.string()),
      body: z.lazy(() =>
        PostV1RegesContractsIdTerminateRequestBody$outboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        idempotencyKey: "Idempotency-Key",
      });
    }),
  );

export function postV1RegesContractsIdTerminateRequestToJSON(
  postV1RegesContractsIdTerminateRequest:
    PostV1RegesContractsIdTerminateRequest,
): string {
  return JSON.stringify(
    PostV1RegesContractsIdTerminateRequest$outboundSchema.parse(
      postV1RegesContractsIdTerminateRequest,
    ),
  );
}

/** @internal */
export const PostV1RegesContractsIdTerminateStatus$inboundSchema: z.ZodMiniType<
  PostV1RegesContractsIdTerminateStatus,
  unknown
> = openEnums.inboundSchema(PostV1RegesContractsIdTerminateStatus);

/** @internal */
export const PostV1RegesContractsIdTerminateData$inboundSchema: z.ZodMiniType<
  PostV1RegesContractsIdTerminateData,
  unknown
> = z.object({
  jobId: types.string(),
  status: PostV1RegesContractsIdTerminateStatus$inboundSchema,
});

export function postV1RegesContractsIdTerminateDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1RegesContractsIdTerminateData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1RegesContractsIdTerminateData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1RegesContractsIdTerminateData' from JSON`,
  );
}

/** @internal */
export const PostV1RegesContractsIdTerminateResponseBody$inboundSchema:
  z.ZodMiniType<PostV1RegesContractsIdTerminateResponseBody, unknown> = z
    .object({
      data: z.lazy(() => PostV1RegesContractsIdTerminateData$inboundSchema),
    });

export function postV1RegesContractsIdTerminateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1RegesContractsIdTerminateResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1RegesContractsIdTerminateResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1RegesContractsIdTerminateResponseBody' from JSON`,
  );
}

/** @internal */
export const PostV1RegesContractsIdTerminateResponse$inboundSchema:
  z.ZodMiniType<PostV1RegesContractsIdTerminateResponse, unknown> = z.pipe(
    z.object({
      Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
      Result: z.lazy(() =>
        PostV1RegesContractsIdTerminateResponseBody$inboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    }),
  );

export function postV1RegesContractsIdTerminateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1RegesContractsIdTerminateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1RegesContractsIdTerminateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1RegesContractsIdTerminateResponse' from JSON`,
  );
}
