/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 38a56f0aca12
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1RegesContractsRequestBody = {
  contract: { [k: string]: any };
};

export type PostV1RegesContractsRequest = {
  /**
   * Replays the first response for the same key, body and route (24h); a different body under the same key is a 409.
   */
  idempotencyKey?: string | undefined;
  body: PostV1RegesContractsRequestBody;
};

export const PostV1RegesContractsStatus = {
  Queued: "queued",
  Processing: "processing",
  Done: "done",
  Error: "error",
  Unknown: "unknown",
} as const;
export type PostV1RegesContractsStatus = OpenEnum<
  typeof PostV1RegesContractsStatus
>;

export type PostV1RegesContractsData = {
  jobId: string;
  status: PostV1RegesContractsStatus;
};

/**
 * Success
 */
export type PostV1RegesContractsResponseBody = {
  data: PostV1RegesContractsData;
};

export type PostV1RegesContractsResponse = {
  headers: { [k: string]: Array<string> };
  result: PostV1RegesContractsResponseBody;
};

/** @internal */
export type PostV1RegesContractsRequestBody$Outbound = {
  contract: { [k: string]: any };
};

/** @internal */
export const PostV1RegesContractsRequestBody$outboundSchema: z.ZodMiniType<
  PostV1RegesContractsRequestBody$Outbound,
  PostV1RegesContractsRequestBody
> = z.object({
  contract: z.record(z.string(), z.any()),
});

export function postV1RegesContractsRequestBodyToJSON(
  postV1RegesContractsRequestBody: PostV1RegesContractsRequestBody,
): string {
  return JSON.stringify(
    PostV1RegesContractsRequestBody$outboundSchema.parse(
      postV1RegesContractsRequestBody,
    ),
  );
}

/** @internal */
export type PostV1RegesContractsRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: PostV1RegesContractsRequestBody$Outbound;
};

/** @internal */
export const PostV1RegesContractsRequest$outboundSchema: z.ZodMiniType<
  PostV1RegesContractsRequest$Outbound,
  PostV1RegesContractsRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => PostV1RegesContractsRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function postV1RegesContractsRequestToJSON(
  postV1RegesContractsRequest: PostV1RegesContractsRequest,
): string {
  return JSON.stringify(
    PostV1RegesContractsRequest$outboundSchema.parse(
      postV1RegesContractsRequest,
    ),
  );
}

/** @internal */
export const PostV1RegesContractsStatus$inboundSchema: z.ZodMiniType<
  PostV1RegesContractsStatus,
  unknown
> = openEnums.inboundSchema(PostV1RegesContractsStatus);

/** @internal */
export const PostV1RegesContractsData$inboundSchema: z.ZodMiniType<
  PostV1RegesContractsData,
  unknown
> = z.object({
  jobId: types.string(),
  status: PostV1RegesContractsStatus$inboundSchema,
});

export function postV1RegesContractsDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1RegesContractsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1RegesContractsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1RegesContractsData' from JSON`,
  );
}

/** @internal */
export const PostV1RegesContractsResponseBody$inboundSchema: z.ZodMiniType<
  PostV1RegesContractsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => PostV1RegesContractsData$inboundSchema),
});

export function postV1RegesContractsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostV1RegesContractsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1RegesContractsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1RegesContractsResponseBody' from JSON`,
  );
}

/** @internal */
export const PostV1RegesContractsResponse$inboundSchema: z.ZodMiniType<
  PostV1RegesContractsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => PostV1RegesContractsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function postV1RegesContractsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1RegesContractsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1RegesContractsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1RegesContractsResponse' from JSON`,
  );
}
