/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f4bc541a5402
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const TypeCode = {
  ThreeHundredAndEighty: "380",
  ThreeHundredAndEightyOne: "381",
  ThreeHundredAndEightyFour: "384",
  SevenHundredAndFiftyOne: "751",
} as const;
export type TypeCode = ClosedEnum<typeof TypeCode>;

export type PrecedingInvoice = {
  number: string;
  issueDate?: string | undefined;
};

export type DeliveryAddress = {
  street: string;
  additionalStreet?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  countrySubdivision?: string | undefined;
  country: string;
};

export type InvoicingPeriod = {
  start?: string | undefined;
  end?: string | undefined;
};

export type SellerAddress = {
  street: string;
  additionalStreet?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  countrySubdivision?: string | undefined;
  country: string;
};

export type SellerContact = {
  name?: string | undefined;
  phone?: string | undefined;
  email?: string | undefined;
};

export type Seller = {
  name: string;
  tradingName?: string | undefined;
  identifier?: string | undefined;
  legalRegistrationId?: string | undefined;
  vatId?: string | undefined;
  taxRegistrationId?: string | undefined;
  address: SellerAddress;
  contact?: SellerContact | undefined;
};

export type BuyerAddress = {
  street: string;
  additionalStreet?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  countrySubdivision?: string | undefined;
  country: string;
};

export type BuyerContact = {
  name?: string | undefined;
  phone?: string | undefined;
  email?: string | undefined;
};

export type Buyer = {
  name: string;
  tradingName?: string | undefined;
  identifier?: string | undefined;
  legalRegistrationId?: string | undefined;
  vatId?: string | undefined;
  address: BuyerAddress;
  contact?: BuyerContact | undefined;
};

export type Payment = {
  meansCode: string;
  iban?: string | undefined;
  accountName?: string | undefined;
  bic?: string | undefined;
  terms?: string | undefined;
  remittanceInfo?: string | undefined;
};

export const AllowanceVatCategory = {
  S: "S",
  Z: "Z",
  E: "E",
  Ae: "AE",
  K: "K",
  G: "G",
  O: "O",
} as const;
export type AllowanceVatCategory = ClosedEnum<typeof AllowanceVatCategory>;

export type Allowance = {
  amount: string;
  vatCategory: AllowanceVatCategory;
  vatRate?: string | undefined;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

export const ChargeVatCategory = {
  S: "S",
  Z: "Z",
  E: "E",
  Ae: "AE",
  K: "K",
  G: "G",
  O: "O",
} as const;
export type ChargeVatCategory = ClosedEnum<typeof ChargeVatCategory>;

export type Charge = {
  amount: string;
  vatCategory: ChargeVatCategory;
  vatRate?: string | undefined;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

export const VatExemptionVatCategory = {
  S: "S",
  Z: "Z",
  E: "E",
  Ae: "AE",
  K: "K",
  G: "G",
  O: "O",
} as const;
export type VatExemptionVatCategory = ClosedEnum<
  typeof VatExemptionVatCategory
>;

export type VatExemption = {
  vatCategory: VatExemptionVatCategory;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

export const LineVatCategory = {
  S: "S",
  Z: "Z",
  E: "E",
  Ae: "AE",
  K: "K",
  G: "G",
  O: "O",
} as const;
export type LineVatCategory = ClosedEnum<typeof LineVatCategory>;

export type Classification = {
  code: string;
  listId: string;
};

export type PostV1EfacturaInvoicesItem = {
  name: string;
  description?: string | undefined;
  sellerId?: string | undefined;
  classification?: Classification | undefined;
};

export type LineAllowance = {
  amount: string;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

export type LineCharge = {
  amount: string;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

export type PostV1EfacturaInvoicesLine = {
  id: string;
  note?: string | undefined;
  quantity: string;
  unitCode: string;
  unitPrice: string;
  baseQuantity?: string | undefined;
  vatCategory: LineVatCategory;
  vatRate?: string | undefined;
  item: PostV1EfacturaInvoicesItem;
  allowances?: Array<LineAllowance> | undefined;
  charges?: Array<LineCharge> | undefined;
};

export type ExpectedTotals = {
  lineNet?: string | undefined;
  taxExclusive?: string | undefined;
  vatTotal?: string | undefined;
  taxInclusive?: string | undefined;
  payable?: string | undefined;
};

export type Invoice = {
  typeCode: TypeCode;
  number: string;
  issueDate: string;
  dueDate?: string | undefined;
  currency: string;
  vatTotalRon?: string | undefined;
  notes?: Array<string> | undefined;
  buyerReference?: string | undefined;
  projectReference?: string | undefined;
  contractReference?: string | undefined;
  orderReference?: string | undefined;
  precedingInvoice?: PrecedingInvoice | undefined;
  deliveryDate?: string | undefined;
  deliveryAddress?: DeliveryAddress | undefined;
  invoicingPeriod?: InvoicingPeriod | undefined;
  seller: Seller;
  buyer: Buyer;
  payment?: Payment | undefined;
  allowances?: Array<Allowance> | undefined;
  charges?: Array<Charge> | undefined;
  vatExemptions?: Array<VatExemption> | undefined;
  lines: Array<PostV1EfacturaInvoicesLine>;
  expectedTotals?: ExpectedTotals | undefined;
};

export type Json = {
  format: "json";
  invoice: Invoice;
};

export type Ubl = {
  format: "ubl";
  xml: string;
};

export type PostV1EfacturaInvoicesRequestBody = Ubl | Json;

export type PostV1EfacturaInvoicesRequest = {
  /**
   * Replays the first response for the same key, body and route (24h); a different body under the same key is a 409.
   */
  idempotencyKey?: string | undefined;
  body: Ubl | Json;
};

export type PostV1EfacturaInvoicesData = {
  id: string;
  idIncarcare: string;
  status: string;
};

/**
 * Success
 */
export type PostV1EfacturaInvoicesResponseBody = {
  data: PostV1EfacturaInvoicesData;
};

export type PostV1EfacturaInvoicesResponse = {
  headers: { [k: string]: Array<string> };
  result: PostV1EfacturaInvoicesResponseBody;
};

/** @internal */
export const TypeCode$outboundSchema: z.ZodMiniEnum<typeof TypeCode> = z.enum(
  TypeCode,
);

/** @internal */
export type PrecedingInvoice$Outbound = {
  number: string;
  issueDate?: string | undefined;
};

/** @internal */
export const PrecedingInvoice$outboundSchema: z.ZodMiniType<
  PrecedingInvoice$Outbound,
  PrecedingInvoice
> = z.object({
  number: z.string(),
  issueDate: z.optional(z.string()),
});

export function precedingInvoiceToJSON(
  precedingInvoice: PrecedingInvoice,
): string {
  return JSON.stringify(
    PrecedingInvoice$outboundSchema.parse(precedingInvoice),
  );
}

/** @internal */
export type DeliveryAddress$Outbound = {
  street: string;
  additionalStreet?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  countrySubdivision?: string | undefined;
  country: string;
};

/** @internal */
export const DeliveryAddress$outboundSchema: z.ZodMiniType<
  DeliveryAddress$Outbound,
  DeliveryAddress
> = z.object({
  street: z.string(),
  additionalStreet: z.optional(z.string()),
  city: z.string(),
  postalCode: z.optional(z.string()),
  countrySubdivision: z.optional(z.string()),
  country: z.string(),
});

export function deliveryAddressToJSON(
  deliveryAddress: DeliveryAddress,
): string {
  return JSON.stringify(DeliveryAddress$outboundSchema.parse(deliveryAddress));
}

/** @internal */
export type InvoicingPeriod$Outbound = {
  start?: string | undefined;
  end?: string | undefined;
};

/** @internal */
export const InvoicingPeriod$outboundSchema: z.ZodMiniType<
  InvoicingPeriod$Outbound,
  InvoicingPeriod
> = z.object({
  start: z.optional(z.string()),
  end: z.optional(z.string()),
});

export function invoicingPeriodToJSON(
  invoicingPeriod: InvoicingPeriod,
): string {
  return JSON.stringify(InvoicingPeriod$outboundSchema.parse(invoicingPeriod));
}

/** @internal */
export type SellerAddress$Outbound = {
  street: string;
  additionalStreet?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  countrySubdivision?: string | undefined;
  country: string;
};

/** @internal */
export const SellerAddress$outboundSchema: z.ZodMiniType<
  SellerAddress$Outbound,
  SellerAddress
> = z.object({
  street: z.string(),
  additionalStreet: z.optional(z.string()),
  city: z.string(),
  postalCode: z.optional(z.string()),
  countrySubdivision: z.optional(z.string()),
  country: z.string(),
});

export function sellerAddressToJSON(sellerAddress: SellerAddress): string {
  return JSON.stringify(SellerAddress$outboundSchema.parse(sellerAddress));
}

/** @internal */
export type SellerContact$Outbound = {
  name?: string | undefined;
  phone?: string | undefined;
  email?: string | undefined;
};

/** @internal */
export const SellerContact$outboundSchema: z.ZodMiniType<
  SellerContact$Outbound,
  SellerContact
> = z.object({
  name: z.optional(z.string()),
  phone: z.optional(z.string()),
  email: z.optional(z.string()),
});

export function sellerContactToJSON(sellerContact: SellerContact): string {
  return JSON.stringify(SellerContact$outboundSchema.parse(sellerContact));
}

/** @internal */
export type Seller$Outbound = {
  name: string;
  tradingName?: string | undefined;
  identifier?: string | undefined;
  legalRegistrationId?: string | undefined;
  vatId?: string | undefined;
  taxRegistrationId?: string | undefined;
  address: SellerAddress$Outbound;
  contact?: SellerContact$Outbound | undefined;
};

/** @internal */
export const Seller$outboundSchema: z.ZodMiniType<Seller$Outbound, Seller> = z
  .object({
    name: z.string(),
    tradingName: z.optional(z.string()),
    identifier: z.optional(z.string()),
    legalRegistrationId: z.optional(z.string()),
    vatId: z.optional(z.string()),
    taxRegistrationId: z.optional(z.string()),
    address: z.lazy(() => SellerAddress$outboundSchema),
    contact: z.optional(z.lazy(() => SellerContact$outboundSchema)),
  });

export function sellerToJSON(seller: Seller): string {
  return JSON.stringify(Seller$outboundSchema.parse(seller));
}

/** @internal */
export type BuyerAddress$Outbound = {
  street: string;
  additionalStreet?: string | undefined;
  city: string;
  postalCode?: string | undefined;
  countrySubdivision?: string | undefined;
  country: string;
};

/** @internal */
export const BuyerAddress$outboundSchema: z.ZodMiniType<
  BuyerAddress$Outbound,
  BuyerAddress
> = z.object({
  street: z.string(),
  additionalStreet: z.optional(z.string()),
  city: z.string(),
  postalCode: z.optional(z.string()),
  countrySubdivision: z.optional(z.string()),
  country: z.string(),
});

export function buyerAddressToJSON(buyerAddress: BuyerAddress): string {
  return JSON.stringify(BuyerAddress$outboundSchema.parse(buyerAddress));
}

/** @internal */
export type BuyerContact$Outbound = {
  name?: string | undefined;
  phone?: string | undefined;
  email?: string | undefined;
};

/** @internal */
export const BuyerContact$outboundSchema: z.ZodMiniType<
  BuyerContact$Outbound,
  BuyerContact
> = z.object({
  name: z.optional(z.string()),
  phone: z.optional(z.string()),
  email: z.optional(z.string()),
});

export function buyerContactToJSON(buyerContact: BuyerContact): string {
  return JSON.stringify(BuyerContact$outboundSchema.parse(buyerContact));
}

/** @internal */
export type Buyer$Outbound = {
  name: string;
  tradingName?: string | undefined;
  identifier?: string | undefined;
  legalRegistrationId?: string | undefined;
  vatId?: string | undefined;
  address: BuyerAddress$Outbound;
  contact?: BuyerContact$Outbound | undefined;
};

/** @internal */
export const Buyer$outboundSchema: z.ZodMiniType<Buyer$Outbound, Buyer> = z
  .object({
    name: z.string(),
    tradingName: z.optional(z.string()),
    identifier: z.optional(z.string()),
    legalRegistrationId: z.optional(z.string()),
    vatId: z.optional(z.string()),
    address: z.lazy(() => BuyerAddress$outboundSchema),
    contact: z.optional(z.lazy(() => BuyerContact$outboundSchema)),
  });

export function buyerToJSON(buyer: Buyer): string {
  return JSON.stringify(Buyer$outboundSchema.parse(buyer));
}

/** @internal */
export type Payment$Outbound = {
  meansCode: string;
  iban?: string | undefined;
  accountName?: string | undefined;
  bic?: string | undefined;
  terms?: string | undefined;
  remittanceInfo?: string | undefined;
};

/** @internal */
export const Payment$outboundSchema: z.ZodMiniType<Payment$Outbound, Payment> =
  z.object({
    meansCode: z.string(),
    iban: z.optional(z.string()),
    accountName: z.optional(z.string()),
    bic: z.optional(z.string()),
    terms: z.optional(z.string()),
    remittanceInfo: z.optional(z.string()),
  });

export function paymentToJSON(payment: Payment): string {
  return JSON.stringify(Payment$outboundSchema.parse(payment));
}

/** @internal */
export const AllowanceVatCategory$outboundSchema: z.ZodMiniEnum<
  typeof AllowanceVatCategory
> = z.enum(AllowanceVatCategory);

/** @internal */
export type Allowance$Outbound = {
  amount: string;
  vatCategory: string;
  vatRate?: string | undefined;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

/** @internal */
export const Allowance$outboundSchema: z.ZodMiniType<
  Allowance$Outbound,
  Allowance
> = z.object({
  amount: z.string(),
  vatCategory: AllowanceVatCategory$outboundSchema,
  vatRate: z.optional(z.string()),
  reason: z.optional(z.string()),
  reasonCode: z.optional(z.string()),
});

export function allowanceToJSON(allowance: Allowance): string {
  return JSON.stringify(Allowance$outboundSchema.parse(allowance));
}

/** @internal */
export const ChargeVatCategory$outboundSchema: z.ZodMiniEnum<
  typeof ChargeVatCategory
> = z.enum(ChargeVatCategory);

/** @internal */
export type Charge$Outbound = {
  amount: string;
  vatCategory: string;
  vatRate?: string | undefined;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

/** @internal */
export const Charge$outboundSchema: z.ZodMiniType<Charge$Outbound, Charge> = z
  .object({
    amount: z.string(),
    vatCategory: ChargeVatCategory$outboundSchema,
    vatRate: z.optional(z.string()),
    reason: z.optional(z.string()),
    reasonCode: z.optional(z.string()),
  });

export function chargeToJSON(charge: Charge): string {
  return JSON.stringify(Charge$outboundSchema.parse(charge));
}

/** @internal */
export const VatExemptionVatCategory$outboundSchema: z.ZodMiniEnum<
  typeof VatExemptionVatCategory
> = z.enum(VatExemptionVatCategory);

/** @internal */
export type VatExemption$Outbound = {
  vatCategory: string;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

/** @internal */
export const VatExemption$outboundSchema: z.ZodMiniType<
  VatExemption$Outbound,
  VatExemption
> = z.object({
  vatCategory: VatExemptionVatCategory$outboundSchema,
  reason: z.optional(z.string()),
  reasonCode: z.optional(z.string()),
});

export function vatExemptionToJSON(vatExemption: VatExemption): string {
  return JSON.stringify(VatExemption$outboundSchema.parse(vatExemption));
}

/** @internal */
export const LineVatCategory$outboundSchema: z.ZodMiniEnum<
  typeof LineVatCategory
> = z.enum(LineVatCategory);

/** @internal */
export type Classification$Outbound = {
  code: string;
  listId: string;
};

/** @internal */
export const Classification$outboundSchema: z.ZodMiniType<
  Classification$Outbound,
  Classification
> = z.object({
  code: z.string(),
  listId: z.string(),
});

export function classificationToJSON(classification: Classification): string {
  return JSON.stringify(Classification$outboundSchema.parse(classification));
}

/** @internal */
export type PostV1EfacturaInvoicesItem$Outbound = {
  name: string;
  description?: string | undefined;
  sellerId?: string | undefined;
  classification?: Classification$Outbound | undefined;
};

/** @internal */
export const PostV1EfacturaInvoicesItem$outboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesItem$Outbound,
  PostV1EfacturaInvoicesItem
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  sellerId: z.optional(z.string()),
  classification: z.optional(z.lazy(() => Classification$outboundSchema)),
});

export function postV1EfacturaInvoicesItemToJSON(
  postV1EfacturaInvoicesItem: PostV1EfacturaInvoicesItem,
): string {
  return JSON.stringify(
    PostV1EfacturaInvoicesItem$outboundSchema.parse(postV1EfacturaInvoicesItem),
  );
}

/** @internal */
export type LineAllowance$Outbound = {
  amount: string;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

/** @internal */
export const LineAllowance$outboundSchema: z.ZodMiniType<
  LineAllowance$Outbound,
  LineAllowance
> = z.object({
  amount: z.string(),
  reason: z.optional(z.string()),
  reasonCode: z.optional(z.string()),
});

export function lineAllowanceToJSON(lineAllowance: LineAllowance): string {
  return JSON.stringify(LineAllowance$outboundSchema.parse(lineAllowance));
}

/** @internal */
export type LineCharge$Outbound = {
  amount: string;
  reason?: string | undefined;
  reasonCode?: string | undefined;
};

/** @internal */
export const LineCharge$outboundSchema: z.ZodMiniType<
  LineCharge$Outbound,
  LineCharge
> = z.object({
  amount: z.string(),
  reason: z.optional(z.string()),
  reasonCode: z.optional(z.string()),
});

export function lineChargeToJSON(lineCharge: LineCharge): string {
  return JSON.stringify(LineCharge$outboundSchema.parse(lineCharge));
}

/** @internal */
export type PostV1EfacturaInvoicesLine$Outbound = {
  id: string;
  note?: string | undefined;
  quantity: string;
  unitCode: string;
  unitPrice: string;
  baseQuantity?: string | undefined;
  vatCategory: string;
  vatRate?: string | undefined;
  item: PostV1EfacturaInvoicesItem$Outbound;
  allowances?: Array<LineAllowance$Outbound> | undefined;
  charges?: Array<LineCharge$Outbound> | undefined;
};

/** @internal */
export const PostV1EfacturaInvoicesLine$outboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesLine$Outbound,
  PostV1EfacturaInvoicesLine
> = z.object({
  id: z.string(),
  note: z.optional(z.string()),
  quantity: z.string(),
  unitCode: z.string(),
  unitPrice: z.string(),
  baseQuantity: z.optional(z.string()),
  vatCategory: LineVatCategory$outboundSchema,
  vatRate: z.optional(z.string()),
  item: z.lazy(() => PostV1EfacturaInvoicesItem$outboundSchema),
  allowances: z.optional(z.array(z.lazy(() => LineAllowance$outboundSchema))),
  charges: z.optional(z.array(z.lazy(() => LineCharge$outboundSchema))),
});

export function postV1EfacturaInvoicesLineToJSON(
  postV1EfacturaInvoicesLine: PostV1EfacturaInvoicesLine,
): string {
  return JSON.stringify(
    PostV1EfacturaInvoicesLine$outboundSchema.parse(postV1EfacturaInvoicesLine),
  );
}

/** @internal */
export type ExpectedTotals$Outbound = {
  lineNet?: string | undefined;
  taxExclusive?: string | undefined;
  vatTotal?: string | undefined;
  taxInclusive?: string | undefined;
  payable?: string | undefined;
};

/** @internal */
export const ExpectedTotals$outboundSchema: z.ZodMiniType<
  ExpectedTotals$Outbound,
  ExpectedTotals
> = z.object({
  lineNet: z.optional(z.string()),
  taxExclusive: z.optional(z.string()),
  vatTotal: z.optional(z.string()),
  taxInclusive: z.optional(z.string()),
  payable: z.optional(z.string()),
});

export function expectedTotalsToJSON(expectedTotals: ExpectedTotals): string {
  return JSON.stringify(ExpectedTotals$outboundSchema.parse(expectedTotals));
}

/** @internal */
export type Invoice$Outbound = {
  typeCode: string;
  number: string;
  issueDate: string;
  dueDate?: string | undefined;
  currency: string;
  vatTotalRon?: string | undefined;
  notes?: Array<string> | undefined;
  buyerReference?: string | undefined;
  projectReference?: string | undefined;
  contractReference?: string | undefined;
  orderReference?: string | undefined;
  precedingInvoice?: PrecedingInvoice$Outbound | undefined;
  deliveryDate?: string | undefined;
  deliveryAddress?: DeliveryAddress$Outbound | undefined;
  invoicingPeriod?: InvoicingPeriod$Outbound | undefined;
  seller: Seller$Outbound;
  buyer: Buyer$Outbound;
  payment?: Payment$Outbound | undefined;
  allowances?: Array<Allowance$Outbound> | undefined;
  charges?: Array<Charge$Outbound> | undefined;
  vatExemptions?: Array<VatExemption$Outbound> | undefined;
  lines: Array<PostV1EfacturaInvoicesLine$Outbound>;
  expectedTotals?: ExpectedTotals$Outbound | undefined;
};

/** @internal */
export const Invoice$outboundSchema: z.ZodMiniType<Invoice$Outbound, Invoice> =
  z.object({
    typeCode: TypeCode$outboundSchema,
    number: z.string(),
    issueDate: z.string(),
    dueDate: z.optional(z.string()),
    currency: z.string(),
    vatTotalRon: z.optional(z.string()),
    notes: z.optional(z.array(z.string())),
    buyerReference: z.optional(z.string()),
    projectReference: z.optional(z.string()),
    contractReference: z.optional(z.string()),
    orderReference: z.optional(z.string()),
    precedingInvoice: z.optional(z.lazy(() => PrecedingInvoice$outboundSchema)),
    deliveryDate: z.optional(z.string()),
    deliveryAddress: z.optional(z.lazy(() => DeliveryAddress$outboundSchema)),
    invoicingPeriod: z.optional(z.lazy(() => InvoicingPeriod$outboundSchema)),
    seller: z.lazy(() => Seller$outboundSchema),
    buyer: z.lazy(() => Buyer$outboundSchema),
    payment: z.optional(z.lazy(() => Payment$outboundSchema)),
    allowances: z.optional(z.array(z.lazy(() => Allowance$outboundSchema))),
    charges: z.optional(z.array(z.lazy(() => Charge$outboundSchema))),
    vatExemptions: z.optional(
      z.array(z.lazy(() => VatExemption$outboundSchema)),
    ),
    lines: z.array(z.lazy(() => PostV1EfacturaInvoicesLine$outboundSchema)),
    expectedTotals: z.optional(z.lazy(() => ExpectedTotals$outboundSchema)),
  });

export function invoiceToJSON(invoice: Invoice): string {
  return JSON.stringify(Invoice$outboundSchema.parse(invoice));
}

/** @internal */
export type Json$Outbound = {
  format: "json";
  invoice: Invoice$Outbound;
};

/** @internal */
export const Json$outboundSchema: z.ZodMiniType<Json$Outbound, Json> = z.object(
  {
    format: z.literal("json"),
    invoice: z.lazy(() => Invoice$outboundSchema),
  },
);

export function jsonToJSON(json: Json): string {
  return JSON.stringify(Json$outboundSchema.parse(json));
}

/** @internal */
export type Ubl$Outbound = {
  format: "ubl";
  xml: string;
};

/** @internal */
export const Ubl$outboundSchema: z.ZodMiniType<Ubl$Outbound, Ubl> = z.object({
  format: z.literal("ubl"),
  xml: z.string(),
});

export function ublToJSON(ubl: Ubl): string {
  return JSON.stringify(Ubl$outboundSchema.parse(ubl));
}

/** @internal */
export type PostV1EfacturaInvoicesRequestBody$Outbound =
  | Ubl$Outbound
  | Json$Outbound;

/** @internal */
export const PostV1EfacturaInvoicesRequestBody$outboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesRequestBody$Outbound,
  PostV1EfacturaInvoicesRequestBody
> = z.union([
  z.lazy(() => Ubl$outboundSchema),
  z.lazy(() => Json$outboundSchema),
]);

export function postV1EfacturaInvoicesRequestBodyToJSON(
  postV1EfacturaInvoicesRequestBody: PostV1EfacturaInvoicesRequestBody,
): string {
  return JSON.stringify(
    PostV1EfacturaInvoicesRequestBody$outboundSchema.parse(
      postV1EfacturaInvoicesRequestBody,
    ),
  );
}

/** @internal */
export type PostV1EfacturaInvoicesRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: Ubl$Outbound | Json$Outbound;
};

/** @internal */
export const PostV1EfacturaInvoicesRequest$outboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesRequest$Outbound,
  PostV1EfacturaInvoicesRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: z.union([
      z.lazy(() => Ubl$outboundSchema),
      z.lazy(() => Json$outboundSchema),
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function postV1EfacturaInvoicesRequestToJSON(
  postV1EfacturaInvoicesRequest: PostV1EfacturaInvoicesRequest,
): string {
  return JSON.stringify(
    PostV1EfacturaInvoicesRequest$outboundSchema.parse(
      postV1EfacturaInvoicesRequest,
    ),
  );
}

/** @internal */
export const PostV1EfacturaInvoicesData$inboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesData,
  unknown
> = z.object({
  id: types.string(),
  idIncarcare: types.string(),
  status: types.string(),
});

export function postV1EfacturaInvoicesDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaInvoicesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EfacturaInvoicesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaInvoicesData' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaInvoicesResponseBody$inboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => PostV1EfacturaInvoicesData$inboundSchema),
});

export function postV1EfacturaInvoicesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaInvoicesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1EfacturaInvoicesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaInvoicesResponseBody' from JSON`,
  );
}

/** @internal */
export const PostV1EfacturaInvoicesResponse$inboundSchema: z.ZodMiniType<
  PostV1EfacturaInvoicesResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => PostV1EfacturaInvoicesResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function postV1EfacturaInvoicesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EfacturaInvoicesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EfacturaInvoicesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EfacturaInvoicesResponse' from JSON`,
  );
}
