/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2257610b0d91
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PostV1EtransportDeclarationsRequestBody = {
  declaration: { [k: string]: any };
};

export type PostV1EtransportDeclarationsRequest = {
  /**
   * Replays the first response for the same key, body and route (24h); a different body under the same key is a 409.
   */
  idempotencyKey?: string | undefined;
  body: PostV1EtransportDeclarationsRequestBody;
};

export type PostV1EtransportDeclarationsData = {
  id: string;
  uit: string;
  status: string;
  createdAt: Date;
};

/**
 * Success
 */
export type PostV1EtransportDeclarationsResponseBody = {
  data: PostV1EtransportDeclarationsData;
};

export type PostV1EtransportDeclarationsResponse = {
  headers: { [k: string]: Array<string> };
  result: PostV1EtransportDeclarationsResponseBody;
};

/** @internal */
export type PostV1EtransportDeclarationsRequestBody$Outbound = {
  declaration: { [k: string]: any };
};

/** @internal */
export const PostV1EtransportDeclarationsRequestBody$outboundSchema:
  z.ZodMiniType<
    PostV1EtransportDeclarationsRequestBody$Outbound,
    PostV1EtransportDeclarationsRequestBody
  > = z.object({
    declaration: z.record(z.string(), z.any()),
  });

export function postV1EtransportDeclarationsRequestBodyToJSON(
  postV1EtransportDeclarationsRequestBody:
    PostV1EtransportDeclarationsRequestBody,
): string {
  return JSON.stringify(
    PostV1EtransportDeclarationsRequestBody$outboundSchema.parse(
      postV1EtransportDeclarationsRequestBody,
    ),
  );
}

/** @internal */
export type PostV1EtransportDeclarationsRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: PostV1EtransportDeclarationsRequestBody$Outbound;
};

/** @internal */
export const PostV1EtransportDeclarationsRequest$outboundSchema: z.ZodMiniType<
  PostV1EtransportDeclarationsRequest$Outbound,
  PostV1EtransportDeclarationsRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => PostV1EtransportDeclarationsRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function postV1EtransportDeclarationsRequestToJSON(
  postV1EtransportDeclarationsRequest: PostV1EtransportDeclarationsRequest,
): string {
  return JSON.stringify(
    PostV1EtransportDeclarationsRequest$outboundSchema.parse(
      postV1EtransportDeclarationsRequest,
    ),
  );
}

/** @internal */
export const PostV1EtransportDeclarationsData$inboundSchema: z.ZodMiniType<
  PostV1EtransportDeclarationsData,
  unknown
> = z.object({
  id: types.string(),
  uit: types.string(),
  status: types.string(),
  createdAt: types.date(),
});

export function postV1EtransportDeclarationsDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EtransportDeclarationsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1EtransportDeclarationsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EtransportDeclarationsData' from JSON`,
  );
}

/** @internal */
export const PostV1EtransportDeclarationsResponseBody$inboundSchema:
  z.ZodMiniType<PostV1EtransportDeclarationsResponseBody, unknown> = z.object({
    data: z.lazy(() => PostV1EtransportDeclarationsData$inboundSchema),
  });

export function postV1EtransportDeclarationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1EtransportDeclarationsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1EtransportDeclarationsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1EtransportDeclarationsResponseBody' from JSON`,
  );
}

/** @internal */
export const PostV1EtransportDeclarationsResponse$inboundSchema: z.ZodMiniType<
  PostV1EtransportDeclarationsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() =>
      PostV1EtransportDeclarationsResponseBody$inboundSchema
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function postV1EtransportDeclarationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1EtransportDeclarationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1EtransportDeclarationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1EtransportDeclarationsResponse' from JSON`,
  );
}
