/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f5f5a7002d51
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const PostV1ConnectionsService = {
  Efactura: "efactura",
  Etransport: "etransport",
  Reges: "reges",
  Spv: "spv",
  Bank: "bank",
} as const;
export type PostV1ConnectionsService = ClosedEnum<
  typeof PostV1ConnectionsService
>;

export type PostV1ConnectionsRequestBody = {
  cui: string;
  service: PostV1ConnectionsService;
  redirectUri: string;
  institutionId?: string | undefined;
};

export type PostV1ConnectionsRequest = {
  /**
   * Replays the first response for the same key, body and route (24h); a different body under the same key is a 409.
   */
  idempotencyKey?: string | undefined;
  body: PostV1ConnectionsRequestBody;
};

export type PostV1ConnectionsData = {
  sessionId: string;
  connectUrl: string;
  expiresAt: Date;
};

/**
 * Success
 */
export type PostV1ConnectionsResponseBody = {
  data: PostV1ConnectionsData;
};

export type PostV1ConnectionsResponse = {
  headers: { [k: string]: Array<string> };
  result: PostV1ConnectionsResponseBody;
};

/** @internal */
export const PostV1ConnectionsService$outboundSchema: z.ZodMiniEnum<
  typeof PostV1ConnectionsService
> = z.enum(PostV1ConnectionsService);

/** @internal */
export type PostV1ConnectionsRequestBody$Outbound = {
  cui: string;
  service: string;
  redirectUri: string;
  institutionId?: string | undefined;
};

/** @internal */
export const PostV1ConnectionsRequestBody$outboundSchema: z.ZodMiniType<
  PostV1ConnectionsRequestBody$Outbound,
  PostV1ConnectionsRequestBody
> = z.object({
  cui: z.string(),
  service: PostV1ConnectionsService$outboundSchema,
  redirectUri: z.string(),
  institutionId: z.optional(z.string()),
});

export function postV1ConnectionsRequestBodyToJSON(
  postV1ConnectionsRequestBody: PostV1ConnectionsRequestBody,
): string {
  return JSON.stringify(
    PostV1ConnectionsRequestBody$outboundSchema.parse(
      postV1ConnectionsRequestBody,
    ),
  );
}

/** @internal */
export type PostV1ConnectionsRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: PostV1ConnectionsRequestBody$Outbound;
};

/** @internal */
export const PostV1ConnectionsRequest$outboundSchema: z.ZodMiniType<
  PostV1ConnectionsRequest$Outbound,
  PostV1ConnectionsRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => PostV1ConnectionsRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function postV1ConnectionsRequestToJSON(
  postV1ConnectionsRequest: PostV1ConnectionsRequest,
): string {
  return JSON.stringify(
    PostV1ConnectionsRequest$outboundSchema.parse(postV1ConnectionsRequest),
  );
}

/** @internal */
export const PostV1ConnectionsData$inboundSchema: z.ZodMiniType<
  PostV1ConnectionsData,
  unknown
> = z.object({
  sessionId: types.string(),
  connectUrl: types.string(),
  expiresAt: types.date(),
});

export function postV1ConnectionsDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ConnectionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ConnectionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ConnectionsData' from JSON`,
  );
}

/** @internal */
export const PostV1ConnectionsResponseBody$inboundSchema: z.ZodMiniType<
  PostV1ConnectionsResponseBody,
  unknown
> = z.object({
  data: z.lazy(() => PostV1ConnectionsData$inboundSchema),
});

export function postV1ConnectionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ConnectionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ConnectionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ConnectionsResponseBody' from JSON`,
  );
}

/** @internal */
export const PostV1ConnectionsResponse$inboundSchema: z.ZodMiniType<
  PostV1ConnectionsResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: z.lazy(() => PostV1ConnectionsResponseBody$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function postV1ConnectionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1ConnectionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1ConnectionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1ConnectionsResponse' from JSON`,
  );
}
