/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5d75f99d432b
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ErrorCode = {
  Unauthorized: "unauthorized",
  Forbidden: "forbidden",
  NotFound: "not_found",
  RateLimited: "rate_limited",
  IdempotencyKeyReuse: "idempotency_key_reuse",
  IdempotencyInProgress: "idempotency_in_progress",
  OperationPending: "operation_pending",
  NotImplemented: "not_implemented",
  HardeningGateUnmet: "hardening_gate_unmet",
  ImpersonationReadonly: "impersonation_readonly",
  PasskeyRequired: "passkey_required",
  PasskeyElevationRequired: "passkey_elevation_required",
  EdgeBindingRejected: "edge_binding_rejected",
  ScopeRequired: "scope_required",
  ValidationError: "validation_error",
  UpstreamError: "upstream_error",
  Conflict: "conflict",
  ConnectionLimitReached: "connection_limit_reached",
  BusinessOffboarding: "business_offboarding",
  ConnectInProgress: "connect_in_progress",
  ConnectionUnsupported: "connection_unsupported",
  ConnectExpired: "connect_expired",
  ScopeRetired: "scope_retired",
  ConnectionUnauthorized: "connection_unauthorized",
  FeatureDisabled: "feature_disabled",
  FeatureStateUnknown: "feature_state_unknown",
  ValidatorUnavailable: "validator_unavailable",
  AuthenticationUnavailable: "authentication_unavailable",
  VaultUnavailable: "vault_unavailable",
  MethodNotAllowed: "method_not_allowed",
  ContractViolation: "contract_violation",
  InternalError: "internal_error",
} as const;
export type ErrorCode = OpenEnum<typeof ErrorCode>;

/** @internal */
export const ErrorCode$inboundSchema: z.ZodMiniType<ErrorCode, unknown> =
  openEnums.inboundSchema(ErrorCode);
