/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1925d97ab6b3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ErrorCode, ErrorCode$inboundSchema } from "./error-code.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ErrorT = {
  code: ErrorCode;
  message: string;
  details?: { [k: string]: any } | undefined;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  code: ErrorCode$inboundSchema,
  message: types.string(),
  details: types.optional(z.record(z.string(), z.any())),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}
